### ISSUE TITLE
Support for K8S 1.16 CRD API V1 Changes

### ISSUE THREAD

**Issue by kramvan1** [operator-framework/operator-lifecycle-manager#1034]
## Type of question

General Context question of support of newer K8S versions

## Question

**What did you do?**
New release of K8S 1.16 has new version of CRD spec, v1.    When will that be supported?

**What did you expect to see?**

Support statement for 1.16 CRD v1

**What did you see instead? Under which circumstances?**

Still using the old CRD API.

**Environment**
* operator-lifecycle-manager version:
0.11.0

* Kubernetes version information:

1.16.0
  
* Kubernetes cluster kind: 
Any

**Comment by ecordell** [comment]
Good question - 

We intend to split OLM into upstream and downstream repos. For upstream (this repo), we haven't planned an exact schedule for how closely to track upstream, but ideally we would track closely (supporting 1.16 apis before 1.16 is GA).

For downstream openshift releases, it's important that OLM vendors the same kube apis that are used in openshift, so currently this repo tracks master of openshift - which is still on 1.14.

We intend to work on this split within the next month or so.

**Comment by kramvan1** [comment]
@ecordell Thx for the update.   Might be nice to make it more clear in the release notes what k8s versions are supported/recommended.

**Comment by kramvan1** [comment]
all good on 1.16+ closing
