### ISSUE TITLE
catalog-operator no version tags for configmap-operator-registry image

### ISSUE THREAD

**Issue by kramvan1** [operator-framework/operator-lifecycle-manager#1045]
## Bug Report

The catalog-operator image does not seem to have any released versions.
https://quay.io/repository/operator-framework/configmap-operator-registry?tag=latest&tab=tags 

Just latest and master.

How to track changes in this catalog image when running with catalog configmap source?  We are using that instead of a catalog hub to allow more control of the catalog contents.

**What did you do?**

Deploy catalog-operator with 
https://github.com/operator-framework/operator-lifecycle-manager/blob/master/deploy/upstream/manifests/0.11.0/0000_50_olm_08-catalog-operator.deployment.yaml

**What did you expect to see?**

The configmap-operator-registry would have released versions.

**What did you see instead? Under which circumstances?**

Just latest and master for the configmap-operator-registry image.

**Environment**
* operator-lifecycle-manager version:
0.11.0

* Kubernetes version information:

1.13

* Kubernetes cluster kind: 

IBM Cloud

**Possible Solution**

Tags the image along side the OLM image.

**Additional context**

**Comment by ecordell** [comment]
Thanks @kramvan1 - this has been missing for a while.

Quay is now building tagged versions of operator-registry: https://quay.io/repository/operator-framework/configmap-operator-registry?tab=tags

I'll leave this open, because we should also be referencing these tags in our release artifacts instead of latest.

**Comment by kramvan1** [comment]
@ecordell Thx for the update.

**Comment by kramvan1** [comment]
Fixed enough for me.
