### ISSUE TITLE
How to add 3rd party CRD to my operator CSV

### ISSUE THREAD

**Issue by MatousJobanek** [operator-framework/operator-lifecycle-manager#1060]
## Type of question

**I'm asking how to nicely solve a specific case and if there is any best practices for such cases. If such a case hasn't been even considered, could we treat this issue as a feature request?**

## Question

**What did you do?**
In our operator, we need to use one CRD from different 3rd party project. In particular, in our [host-operator](https://github.com/codeready-toolchain/host-operator/) we have a set of [CRDs](https://github.com/codeready-toolchain/host-operator/tree/master/deploy/crds) including one called [KubeFedCluster](https://github.com/codeready-toolchain/host-operator/blob/master/deploy/crds/core_v1beta1_kubefedcluster_crd.yaml) - that one has been taken from [KubeFed](https://github.com/kubernetes-sigs/kubefed) project and we use also one specific controller from that project, but nothing more. In other words, we need to use only this particular CRD and not the whole KubeFed controller.

When I worked on our [CSV](https://github.com/codeready-toolchain/host-operator/blob/master/deploy/olm-catalog/host-operator/0.0.1/host-operator.v0.0.1.clusterserviceversion.yaml) I didn't know where I should put the `KubeFedCluster` CRD, because:
* I thought that I shouldn't put it into the `owned` section, because it's not our CRD (for now I kept it there). In addition, I'm not sure how it would work in case anyone would use the `KubeFedCluster` CRD as the required one - which operator would be installed as the dependency? KubeFed or our host-operator?
* I couldn't add it to required CRD because I don't want to install the whole KubeFed operator

The only way to achieve that I can see is a workaround of creating the `KubeFedCluster` CRD programatically. Before controllers are started it would [ensure](https://github.com/MatousJobanek/host-operator/blob/csv-host-with-lazy-deployment/pkg/controller/kubefedcluster.go#L21-L37) that the CRD exists in the cluster. Is it an expected and intended solution? Or is there any other one? Do you have any plan to support such a feature in the future?

**What did you expect to see?**
Any section where I could add 3rd party CRD that wouldn't trigger the installation of the whole operator and would only ensure that the CRD would be available in the cluster.

**What did you see instead? Under which circumstances?**
No way I could add 3rd party CRD without installing the whole operator nor specifying as the owned one.

**Environment**
* operator-lifecycle-manager version:
I'm not sure how to get the version - I tried that using:
  * OpenShift 4.2.0-0.nightly-2019-09-24-194016
  * operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+68e229c", GitCommit:"68e229c", GitTreeState:"clean", BuildDate:"2019-08-06T18:30:32Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+73b5d76", GitCommit:"73b5d76", GitTreeState:"clean", BuildDate:"2019-09-23T16:18:51Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
```
  

* Kubernetes cluster kind: 
OpenShift

**Comment by dmesser** [comment]
There is an undocumented feature called `nativeAPI` in the [CSV](https://github.com/operator-framework/operator-lifecycle-manager/blob/2760276f78584ab485d448fa53abda8025fe5cb0/pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go#L150) that will essentially block installation if that API is not present on the cluster. It was originally intended to be used for depending on Kubernetes core features (e.g. Deployment/v1) but can also be used to validate existence of CRDs.

**Comment by MatousJobanek** [comment]
> that will essentially block installation if that API is not present on the cluster

but I don't want to block it, I want olm to create the needed CRD while installing my operator (but without installing the whole 3rd party operator)

**Comment by dmesser** [comment]
I see. That is not supported in the dependency model. You will either own the CRD or require it. What's the problem / consequence of the 3rd party Operator getting pulled in? If it's too big maybe it needs to be broken down more?

**Comment by MatousJobanek** [comment]
> What's the problem / consequence of the 3rd party Operator getting pulled in?

let say that we need only one small piece of the whole operator functionality, so installing the whole operator looks like an overkill.

> If it's too big maybe it needs to be broken down more?

sure, that is something I can ask them for. For now, I was trying to figure out what kind of options we have and if there is any plan to support such functionality in OLM.

So, to sum up: the recommended way is to put it into the `required` ones and install the whole operator, right? Am I correct that putting it into the `owned` ones is not a good idea at all? What would happen if there are two operators having the the same CRD in the `owned` list?

**Comment by dmesser** [comment]
Yes, you are corrected - the CRD should go into the `required` section. `owned` is not a good idea as it would prevent another Operator, actually _owning_ that CRD from getting installed. OLM prevents two Operators owning the same CRD by GVK.

**Comment by ecordell** [comment]
This looks resolved to me - please re-open if we need further discussion.
