### ISSUE TITLE
make run-console-local dont exists anymore

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-lifecycle-manager#1064]
## Bug Report

The README.md page of this project [mentions](https://github.com/operator-framework/operator-lifecycle-manager#user-interface) that we can launch this make rule `make run-console-local` to run a local OpenShift console but this command dont exist anymore

Questions:
- Is the rule `run-console-local` deprecated` or replaced by another one ?
- If the rule `run-console-local` is deprecated, then the doc should be updated and the section `user-interface` removed ?

![Screenshot 2019-10-07 10 17 30](https://user-images.githubusercontent.com/463790/66295472-b4376a80-e8eb-11e9-910d-f11a00efe1e4.png)

**Comment by skitt** [comment]
> The README.md page of this project [mentions](https://github.com/operator-framework/operator-lifecycle-manager#user-interface) that we can launch this make rule `make run-console-local` to run a local OpenShift console but this command dont exist anymore

Could you check again? The command still works for me on master, and [the relevant part of the `Makefile`](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Makefile#L237) hasn’t changed since May.

**Comment by ecordell** [comment]
I just ran `make run-console-local` and verified that it works. Please reopen if you're still having problems.
