### ISSUE TITLE
OLM: Subscription/InstallPlan for namespace scoped operator with required for cluster only scoped operator fails to install required operator

### ISSUE THREAD

**Issue by dacleyra** [operator-framework/operator-lifecycle-manager#1084]
## Bug Report

**What did you do?**
* Create a Namespace scoped operator with a `required` api/csv that is part of a Cluster only scoped operator, such as serverless-operator.v1.0.0
* Deploy the Namespace scoped operator using OLM Subscription, allowing OLM to emit an InstallPlan to install the required api/csv operator

**What did you expect to see?**
* Both Operators are installed correctly

**What did you see instead? Under which circumstances?**
* Required api/csv Operator fails to install with message

`Failed: OwnNamespace InstallModeType not supported, cannot configure to watch own namespace`

It appears the parent is passing down its InstallMode to the required operator in the InstallPlan, even though it is not supported. OLM could possibly figure out what InstallModes are supported, and choose another.

**Environment**
* operator-lifecycle-manager version: 

OLM 0.11.0 on OCP 4.2, also tried 0.12.0 with override

* Kubernetes version information:

Kubernetes Version: v1.14.6+2e5ed54

* Kubernetes cluster kind: 

OCP 4.2

**Possible Solution**

**Additional context**

**Comment by awgreene** [comment]
Hello @dacleyra,

Thank you for submitting an Issue.

Based on the problem you described, it appears that you've created an `OperatorGroup` where its `spec.targetNamespace` is to equal the `metadata.namespace` field. This configuration requires that any operators deployed within support the `OwnNamespace installMode` as defined in [operatorgroups.md](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/operatorgroups.md):

> * OwnNamespace: If supported, the operator can be a member of an OperatorGroup that selects its own namespace 

Based on the logs you provided, it does not appear that the operator providing the `required` APIs supports the `OwnNamespace InstallMode`. The operator that `owns` the `required` APIs must be deployed in an `OperatorGroup` that matches an `InstallMode` that it supports.

**Comment by dacleyra** [comment]
Yes, by installing a namespace scoped operator, the OLM UI creates a Subscription and the OperatorGroup where its spec.targetNamespace is to equal the metadata.namespace field, as you say.

The problem is that that in OLM the Subscription automatically generates an InstallPlan with an unsupported InstallMode for the required apis / operators.

**Comment by dinhxuanvu** [comment]
Unfortunately, the OLM resolver simply doesn't take into account the OperatorGroup settings (AKA InstallModes) during resolution. So it is unable to tell if this operator is not installable in this specific namespace. We currently don't have a plan to change the resolver to do so. However, we do have a plan to "descope" the operator so that they will become singleton operators. As a result, the InstallModes will be obsolete in the future. You can take a look at the issue #2437 for more information.
