### ISSUE TITLE
how to shutdown operator instance when last subscription is removed?

### ISSUE THREAD

**Issue by kramvan1** [operator-framework/operator-lifecycle-manager#1088]
## Type of question

Catalog subscription and life of operator

## Question

**What did you do?**

Have a catalog with a valid package/CSV/CRD.
Create the subscription for that  and the operator comes to life.
Remove the subscription

**What did you expect to see?**

Since it was the only/last use of the operator, I expected it to be shutdown (delete CSV, CRD, operator resources).   No need to have operator running without any active subscriptions.

**What did you see instead? Under which circumstances?**

The operator remains running, doing nothing as there are no subscriptions for it. 

**Environment**

olm 0.12.0

* Kubernetes version information:

1.16

* Kubernetes cluster kind: 

IKS

**Additional context**

I don't want a bunch of idle operators sitting around.  And I don't want to have to find/know about each CSV/CRD to manually shut them down.   I want something automatic for operator shutdown based upon subscriptions.

Wondering if there could be a field in the CSV that specifies to trigger a cleanup when the last subscription is deleted.    This would allow the Catalog to look if there are any other active subscriptions for this package/CSV, and if not, trigger the delete of the CSV and CRD and hence the operator.

If there's another way to trigger the delete of the CSV/CRD with some olm/catalog API, I would like to hear about it.      Since Catalog creates the CSVs/CRDs, it should have an API to clean them up.

**Comment by ecordell** [comment]
The Subscription indicates a desire for updates, so removing just the subscription will disconnect your operator from updates, but will not remove the operator. 

You can delete the CSV to completely remove the running operator.

This trips up users frequently, we have proposals for review to address this: https://github.com/openshift/enhancements/blob/master/enhancements/olm/simplify-apis.md#proposal

**Comment by kramvan1** [comment]
@ecordell Thx for the link.    My basic issue is about general cleanup.   Any API that creates resources on behalf of the user, should have a straight forward and same high level way to remove them.     At quick glance, I don't see much coverage in the proposal for how cleanup will work, maybe that should be a new topic?

**Comment by kramvan1** [comment]
closing, will wait an see what new proposal brings.
