### ISSUE TITLE
MinKubeVersion error msg as a requirement can cause misunderstandings 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lifecycle-manager#1093]
## Bug Report

**What did you do?**
Create a CSV without spec the minKubeVersion
 
**What did you expect to see?**
All worked

**What did you see instead? Under which circumstances?**

```
 "requirementStatus": [
    {
      "group": "operators.coreos.com",
      "kind": "ClusterServiceVersion",
      "message": "CSV missing minimum kube version specification",
      "name": "memcachedoperator.v0.0.1",
      "status": "NotPresent",
      "version": "v1alpha1"
    },

```
**Possible Solution**
Do not show this msg since the minKubeVersion is not a requirement. 

**Additional context**
Avoid users believes that the issues faced by them are because of it. E.g https://github.com/operator-framework/getting-started/issues/43

**Comment by dinhxuanvu** [comment]
Is solved with this PR #1094

**Comment by dinhxuanvu** [comment]
The PR is merged so this issue is now resolved. Thanks.

**Comment by camilamacedo86** [comment]
Really tks @dinhxuanvu 🥇
