### ISSUE TITLE
Slack channel?

### ISSUE THREAD

**Issue by gflarity** [operator-framework/operator-lifecycle-manager#1117]
## Type of question

Community

## Question

Hi, is there channel where people meet to chat about the operator-lifecycle-manager or the operator-framework in general maybe?

Thanks,
Geoff

**Comment by dinhxuanvu** [comment]
Hey Geoff,

You can use #kubernetes-operators in kubernetes.slack.com to ask questions regarding OLM and operator-framework. Please keep it mind, that channel is for all things operators, not just OLM and operator-framework exclusively.

Also, you can use operator-framework Google Group (https://groups.google.com/forum/#!forum/operator-framework). This one is exclusive for us.

Thanks,
Vu
