### ISSUE TITLE
Support configMap in OLM

### ISSUE THREAD

**Issue by srinivas-kandula** [operator-framework/operator-lifecycle-manager#1120]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I am working with RedHat partner connect team to build operator for a application that need to be hosted in Operatorhub.io. While building CSV using operator-sdk olm-catalog gen-csv came across this limitation of operator-sdk. The operator deploys a application that needs default configMap to be present in the namespace before the application is deployed else the application fails to start.
Raised this feature request in operator-sdk project https://github.com/operator-framework/operator-sdk/issues/2176. Once the sdk supports this new feature OLM need to handle the same, hence raising new feature request under OLM as well.

**Describe the solution you'd like**
Once the operator-sdk supports configMap, OLM need to create configMap resource before deploying the application that needs it.

**Comment by ecordell** [comment]
ConfigMaps are now supported in operator bundles
