### ISSUE TITLE
Expected handling of minor release updates

### ISSUE THREAD

**Issue by lulf** [operator-framework/operator-lifecycle-manager#1124]
## Type of question

About best practices for CSV and release management.

## Question

When maintaining multiple minor versions of an operator and updating those due to CVE updates etc, what is the best practices for the .spec.replaces field when supporting multiple major.minor versions?

I.e. lets assume the following releases are made (in order)

* version 1.1.0
* version 1.2.0 (with replaces: 1.1.0)

Now, if a version 1.1.1 needs to be released, what should the replaces point to? It clearly replaces 1.1.0, but it doesn't replace 1.2.0.

What is the effect of specifying/not specifying replaces?

Should the replaces only cover the latest micro of a particular minor?

**Comment by Bowenislandsong** [comment]
Hi @lulf, I think you would benefit from the design document that describes [Replaces / Channels](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/how-to-update-operators.md#replaces--channels). The entire [doc](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/how-to-update-operators.md) should help describe the best practice for designing your operator upgrades.

**Comment by lulf** [comment]
Hi @Bowenislandsong, that document was helpful, thanks! 

So, would I model my scenario as having a channel per minor? I.e.

channel: 1.1
   csv: 1.1.0
   csv: 1.1.1 (replaces 1.1.0)
channel: 1.2
  csv: 1.2.0 (replaces 1.1.0)

I'm struggling to understand how a user would get upgraded from 1.1.1 to 1.2.0.

Or is my scenario simply not supported?

**Comment by Bowenislandsong** [comment]
Your scenario seems fine. Subscribers might have to change channels in this way. An alternative can be that you create a third channel to define 1.1.0 -> 1.1.1 -> 1.2.0. It all depends on how you would want your subscribers to consume your operator. You are in full control over your upgrade paths and alternatives.
