### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by AllAppreg3** [operator-framework/operator-lifecycle-manager#1126]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

**Comment by AllAppreg3** [comment]
Testing

**Comment by AllAppreg3** [comment]
Testing2

**Comment by awgreene** [comment]
My gut says that this is a bot.
