### ISSUE TITLE
All installPlans fail to be created when one fails

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/operator-lifecycle-manager#1128]
## Bug Report

I'm testing automation of a full environment that involves Ansible creating several subscriptions in the "Operators" namespace at once. When doing this, if one subscription can't find its CSV, it'll keep all installPlans from being created. If you are focused on debugging a functional operator, this can send you down a bit of a rabbit trail as the logs don't identify why the functional subscription isn't proceeding.

**What did you do?**
Created a bad subscription as a batch of subscriptions. 

**What did you expect to see?**
Good subscriptions continue creating an install plan and installing, bad subscription fail. 

**What did you see instead? Under which circumstances?**
All subscriptions currently fail to proceed when one can't create an install plan, but doesn't indicate this in the logs in reference to the good subscriptions.

**Environment**
* operator-lifecycle-manager version:

`0.12.0`
Previously seen on `0.6.0` also. See #1113 

* Kubernetes version information:
```
$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://REDACTED:8443
openshift v3.11.153
kubernetes v1.11.0+d4cacc0
```

* Kubernetes cluster kind: 
Red Hat OpenShift 3.11

**Possible Solution**
Allow install plans for functional subscriptions to continue even when other subscriptions are failing.

Alternative: Put an error in the logs to indicate that all subscription processing ceases until subscription X is fixed or something like that. 

**Additional context**
I previously saw this with issue #1113 and closed it when I cleared the bad subscriptions, That was back when I was running OLM 0.6.0. I have upgraded to 0.12.0, but ran into this again and I think I have better characterized the problem so submitting it as a bug.

**Comment by flickerfly** [comment]
This should be able to be reproducible by 

1. creating a broken subscription (bad catalog name or catalog namespace) 
2. creating a good subscription after that

So far, I've only tried this on global operators.

**Comment by njhale** [comment]
@flickerfly Thank you for reporting this!

We actually noticed this recently too. We'll be working on a fix soon and I'll let you know as soon as a PR is up.

**Comment by flickerfly** [comment]
I noticed something similar when the InstallPlan is generated, but one of them can't be performed. They all cease to be installed. Seems like they were bundled together into the same install plan even though they weren't related. Do you want a separate issue for that or is it sufficiently related?

**Comment by njhale** [comment]
By design, OLM resolves all `Subscriptions` in a namespace using a single `InstallPlan`. This avoids some more [subtle dependency issues](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/dependency-resolution.md#example-version-deadlock), but can lead to the problems you've pointed out.

We've been working on rethinking our installation and dependency resolution process, so be on the lookout for that in the coming months.

That being said, I think they are two distinct issues, but the latter is expected behavior.

**Comment by flickerfly** [comment]
Okay, thanks!
