### ISSUE TITLE
Dead links in README.md to examples cause confusion

### ISSUE THREAD

**Issue by lisa** [operator-framework/operator-lifecycle-manager#1133]
## Bug Report

**What did you do?**
Reading the README.md for examples of bundles and observed the `EtcdCluster CRD` and `EtcdBackup CRD` links point to locations which do not exist.

**What did you expect to see?**
I expect to see valid links.

**What did you see instead? Under which circumstances?**
404 error pages from Github.

**Environment**
* operator-lifecycle-manager version: `master`, or, specifically 16619cd27fa56af837c26a49ba9badc7b6566fd8

* Kubernetes version information: NA

* Kubernetes cluster kind:  NA

**Comment by timflannagan** [comment]
Closing this out as this appears to have already been resolved and both of those links that reference the `Etcd*` CRDs now point to the correct directory in the community-operators repository.
