### ISSUE TITLE
Beya

### ISSUE THREAD

**Issue by TriTiger** [operator-framework/operator-lifecycle-manager#1139]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

**Comment by njhale** [comment]
It looks like this account is a bot. Closing.
