### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TriTiger** [operator-framework/operator-lifecycle-manager#1141]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

  

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by njhale** [comment]
It looks like this account is a bot. Closing.
