### ISSUE TITLE
[Question] What does `alm` means?

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-lifecycle-manager#1193]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

I found in the example and source code, there are a lot of concept named as `alm-xxx` etc, what does `alm` means here?

/cc @camilamacedo86 @njhale 

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

  

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by awgreene** [comment]
Hello @gyliu513,

Operator-Lifecycle-Manager (olm) was once called Application-Lifecycle-Manager (ALM). The `alm-xxx` code that you see lying around are legacy artifacts.

Closing this issue for now, please reopen if you have additional questions.

**Comment by gyliu513** [comment]
Good to know, thanks @awgreene 

FYI @clyang82

**Comment by awgreene** [comment]
@ecordell should we consider removing `alm-xxx` references? I believe that there are CI/CD tests that rely on some of these labels but we may benefit from a refactor - could be marked as a good first issue.
