### ISSUE TITLE
operator-framework command

### ISSUE THREAD

**Issue by clyang82** [operator-framework/operator-lifecycle-manager#1206]
## Question

From this [enhancement document](https://github.com/openshift/enhancements/blob/master/enhancements/olm/operator-bundle.md), there has a command `operator-framework`. if we have such `operator-framework` in future, I think we should add the `operator verify` as a sub-command to replace https://github.com/operator-framework/api/tree/master/cmd/operator-verify.  WDYT?

@kevinrizza @awgreene

**Comment by ecordell** [comment]
Hi @clyang82, great idea!

The "operator-framework" was a strawman design. We have implemented it as `opm` in operator-registry: https://github.com/operator-framework/operator-registry/tree/master/cmd/opm

The `operator-verify` functionality will be included in both `opm` and `operator-sdk` in the near future 😄 

Typically we suggest `operator-sdk` for operations with respect to a single operator, and `opm` for managing collections. The bundle support in sdk and the entire opm command are new, and docs and examples will be coming in shortly.

**Comment by clyang82** [comment]
That's is clear design. Thanks for sharing. Let me close this issue.
