### ISSUE TITLE
Instance creation for dependency operator

### ISSUE THREAD

**Issue by vincent-pli** [operator-framework/operator-lifecycle-manager#1214]
## Type of question
The dependency resolution.

## Question

**What did you do?**
I have a operator depends on several community operators,
I defined my CSV with `required crd`, and it works, the depends operators are installed.

My question is, what about the instance of depends operator, should I create these `instance/cr` in my operator, what's the best practice for this case.

**What did you expect to see?**
Depends `application/instance/cr` was create before my application ready.

**Comment by clyang82** [comment]
Here are some explanations and best practices - https://github.com/operator-framework/operator-sdk/issues/2304#issuecomment-564972205

**Comment by vincent-pli** [comment]
@clyang82 
It's helpful, thanks
