### ISSUE TITLE
[Bug] Cannot import a customresourcedefinition that has been exported via 'oc get -o yaml'

### ISSUE THREAD

**Issue by radtriste** [operator-framework/operator-lifecycle-manager#1259]
**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

**Comment by benluddy** [comment]
Looks like this was accidentally filed twice (https://github.com/operator-framework/operator-lifecycle-manager/issues/1260 has the full report).
