### ISSUE TITLE
Not able to view resources via Openshift Admin console for a K8s Cluster on GCP

### ISSUE THREAD

**Issue by vaishali-prophecy** [operator-framework/operator-lifecycle-manager#1275]
Getting the following error - 

pods is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "pods" in API group "" in the namespace "default"

kubectl version - 
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.23", GitCommit:"93457f9dac45d5f95c2c609232e1ff2343c72684", GitTreeState:"clean", BuildDate:"2020-01-14T06:01:01Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

Also, hitting on Events button generates these errors - "2020-02-04T12:57:33Z Failed to dial backend: 'websocket: bad handshake' Status: '403 Forbidden' URL: 'https://35.192.52.180/api/v1/namespaces/default/events?watch=true'"

I am new to openshift and this operator framework. Any help in this regard would be highly appreciated.

**Comment by benluddy** [comment]
Hi Vaishali! This question might be a better fit for the https://github.com/openshift/console project. I just checked open issues there, and it seems that someone else has reported the same problem you've encountered in https://github.com/openshift/console/issues/1377.

**Comment by vaishali-prophecy** [comment]
Thanks @benluddy ..
