### ISSUE TITLE
We cannot install another CSV using a different channel 

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-lifecycle-manager#1285]
## Bug Report

We cannot install a different version of the CSV using a different channel defined within the subscription

This config fails and always deploy the version `0.8.2` of `openshift-pipelines-operator` and not `v0.10.4`

## Test 1

Subscription used
```
spec:
  channel: canary
  startingCSV: openshift-pipelines-operator.v0.10.4
  installPlanApproval: Manual
  name: openshift-pipelines-operator
```

## Test 2 

Subscription used
```
  channel: canary
  installPlanApproval: Automatic
  name: openshift-pipelines-operator
```

## Information

- Kubernetes cluster : 1.14
- OLM deployed : 0.14.1
- Package definition: https://github.com/operator-framework/community-operators/blob/master/community-operators/openshift-pipelines-operator/openshift-pipelines-operator.package.yaml
- Subscription tested: https://github.com/halkyonio/container-images/blob/12bf0d80a15104208fcd36fb330a700b4515138b/sandbox/olm/tekton-subscription.yml#L12

I'm using the same too https://github.com/halkyonio/container-images/blob/12bf0d80a15104208fcd36fb330a700b4515138b/sandbox/olm/tekton-subscription.yml#L12

but 0.8.2 is always installed
```
kc get clusterserviceversion -n marketplace       
NAME                                  DISPLAY                        VERSION   REPLACES   PHASE
openshift-pipelines-operator.v0.8.2   OpenShift Pipelines Operator   0.8.2                Succeeded
```

**Comment by ecordell** [comment]
Could you provide the OperatorSource or CatalogSource you are using for the catalog? Based on the information here, my guess is that the package and channel are not published, or there is some error preventing the use of the indicated channel.

The logs for the pod corresponding to the operatorsource or catalogsource would be helpful as well.

**Comment by cmoulliard** [comment]
I re-created a new cluster and fixed the problem as multiple catalogs were mixed during my initial installation.
That was related to the fact that, when we install OLM, a catalogSource is deployed using as source the image from operatorhub and I was also deploying the same catalog using the operator-marketplace
