### ISSUE TITLE
Is there a way to list ClusterServiceVersions in v1?

### ISSUE THREAD

**Issue by dharmit** [operator-framework/operator-lifecycle-manager#1317]
## Type of question

I'm seeking help around usage of OLM APIs.

## Question

**What did you do?**
In [odo project](https://github.com/openshift/odo/), we're trying to provide users with the functionality to create operator backed services using the `odo` CLI. `odo` is a developer focussed CLI tool and is different from `oc` in the way it abstracts things for enterprise developers.

We have a [bunch of issues](https://github.com/openshift/odo/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%2Fservice-operators) around this that we're working on to support creation of operation backed services. First among these is listing the operators and we're using the `List` method on `ClusterServiceVersion` provided by `v1alpha1` APIs of OLM. We went with `v1alpha1` because I didn't see this in [`v1` APIs](https://github.com/operator-framework/operator-lifecycle-manager/tree/release-4.1/pkg/api/client/clientset/versioned/typed/operators/v1).

**What did you expect to see?**
Availability of methods to perform operations on or related to `ClusterServiceVersions` in `v1`.

**What did you see instead? Under which circumstances?**
I didn't see such methods/types in `v1`.

**Environment**
* operator-lifecycle-manager version: `release-4.1`.

* Kubernetes version information:   OCP 4.x

* Kubernetes cluster kind: NA

**Additional context**
We're trying to develop things around OperatorHub using the OLM API. Is there a place to look at for the documentation of these APIs?

**Comment by dharmit** [comment]
After opening the issue, I looked around a bit. This seems to be a `release-4.1` thing. In the latest `master`, I see CSV related structs and methods outside the `v1alpha1`. So maybe we can use the `v1` APIs of OLM when we change our dependency to something newer than `release-4.1`. Is my understanding correct?

**Comment by dinhxuanvu** [comment]
This issue is stale. Closed. Please feel free to reopen if needed.
