### ISSUE TITLE
Operators not getting updated as expected

### ISSUE THREAD

**Issue by mcurran-us** [operator-framework/operator-lifecycle-manager#1327]
## Bug Report

**What did you do?**

- Create a subscription in the openshift-operators namespace, at the cluster scope with a custom 
   catalog source and InstallPlanApproval set to Automatic.

```
NAME                                    PACKAGE             SOURCE                               CHANNEL
ibm-cp-applications-kiali-ossm          kiali-ossm          ibm-cp-applications-catalog          stable
```
   The following CSV is created:
```
NAME                           DISPLAY                 VERSION         REPLACES                       PHASE
kiali-operator.v1.0.7          Kiali Operator          1.0.7           kiali-operator.v1.0.6          Succeeded
```

- Update the existing subscription to change the source to redhat-operators and apply the change.

```
NAME                                    PACKAGE             SOURCE                    CHANNEL
ibm-cp-applications-kiali-ossm          kiali-ossm          redhat-operators          stable
```

The version of the operator did not change even though there are updates available. 
```
NAME                           DISPLAY                 VERSION        REPLACES                       PHASE
kiali-operator.v1.0.7          Kiali Operator          1.0.7          kiali-operator.v1.0.6          Succeeded
```
```
 oc describe sub ibm-cp-applications-kiali-ossm -n openshift-operators

  Install Plan Ref:  
    API Version:       operators.coreos.com/v1alpha1  
    Kind:              InstallPlan  
    Name:              install-w7gpq  
    Namespace:         openshift-operators  
    Resource Version:  3257972  
    UID:               5b4960c4-12e7-477f-9503-fff82bd9a490  
  Installed CSV:       kiali-operator.v1.0.7  
  Installplan:  
    API Version:  operators.coreos.com/v1alpha1  
    Kind:         InstallPlan  
    Name:         install-w7gpq  
    Uuid:         5b4960c4-12e7-477f-9503-fff82bd9a490  
  Last Updated:   2020-02-25T23:42:29Z  
  State:          UpgradeAvailable
```

**What did you expect to see?**
I expected that with the Approval set to Automatic, the operator should have been updated to the latest level.

**What did you see instead? Under which circumstances?**
The operator did not get upgraded, but remained at the previous level.

**Environment**
* operator-lifecycle-manager version:  

`0.13.0`

* Kubernetes version information:
```
oc version
Client Version: v4.2.7
Server Version: 4.3.0
Kubernetes Version: v1.16.2
```
* Kubernetes cluster kind: 
Red Hat OpenShift 4.3.0

**Possible Solution**

**Additional context**

**Comment by ecordell** [comment]
Can you share the installplan referenced there? `install-w7gpq`?

**Comment by mcurran-us** [comment]
Here is the output of the InstallPlan:
[install-w7gpq.txt](https://github.com/operator-framework/operator-lifecycle-manager/files/4257749/install-w7gpq.txt)

**Comment by ecordell** [comment]
Thanks @mcurran-us - could you also share logs for the `catalog-operator` and the status of any `CatalogSource` and `OperatorSource` in your cluster?

I should've asked for those as well originally, sorry - I was thinking we'd see something different in your installplan.

**Comment by mcurran-us** [comment]
No problem at all.  
[catalog-operator.log](https://github.com/operator-framework/operator-lifecycle-manager/files/4257917/catalog-operator.log)
[CatalogSource.txt](https://github.com/operator-framework/operator-lifecycle-manager/files/4257919/CatalogSource.txt)
[OperatorSource.txt](https://github.com/operator-framework/operator-lifecycle-manager/files/4257920/OperatorSource.txt)

**Comment by dinhxuanvu** [comment]
This issue is stale. Closed. Please feel free to reopen if needed.
