### ISSUE TITLE
OLM web console display incorrect resource title for the Operator Details

### ISSUE THREAD

**Issue by DanielXLee** [operator-framework/operator-lifecycle-manager#1328]
## Type of question
OLM web console display plural word have some problem

## Question

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).
I defined a `displayName: OperandRegistry` in my csv yaml file for the `customresourcedefinitions`, and then I create this operator from web console, under the Operator Details page, the title name show `OperandRegistrys`
**What did you expect to see?**
I want to see the title show `OperandRegistries`
how do we handle these special case of singular and plural?

**What did you see instead? Under which circumstances?**
I see the title show `OperandRegistrys`
![image](https://user-images.githubusercontent.com/3355374/75415402-7d2f2780-5966-11ea-985a-9964d29d3083.png)

**Environment**
* operator-lifecycle-manager version:
I don't know how to get the version, just list image version of the olm pod.
```bash
oc -n openshift-operator-lifecycle-manager get po olm-operator-6d454db9dd-dh5bj -oyaml | grep "image:"
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:dbde7140eb5c05e05252e2bc2891f47761aecf465803d08831c6b20c84bebbb8
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:dbde7140eb5c05e05252e2bc2891f47761aecf465803d08831c6b20c84bebbb8
```

* Kubernetes version information:

  ```bash
# oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0+b4261e0", GitCommit:"b4261e07ed", GitTreeState:"clean", BuildDate:"2019-10-06T23:21:44Z", GoVersion:"go1.13.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"4320e48", GitTreeState:"clean", BuildDate:"2020-01-21T19:50:59Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
OCP 4.3.0
Release Image
`quay.io/openshift-release-dev/ocp-release@sha256:3a516480dfd68e0f87f702b4d7bdd6f6a0acfdac5cd2e9767b838ceede34d70d`
**Additional context**
Add any other context about the question here.

**Comment by timflannagan** [comment]
I'd be surprised if this hasn't been fixed in the OCP console by now, but I'd imagine this falls under them to make that manipulation when serving the package contents. In any case, upstream has been decoupled from housing OCP builds so closing this out.
