### ISSUE TITLE
How to update CR when an operator is upgraded

### ISSUE THREAD

**Issue by 27149chen** [operator-framework/operator-lifecycle-manager#1354]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
community best practices

## Question

When an operator is upgraded to a new version by olm, should the fields of the previous cr be upgraded too?
There are some situations (The premise of this question is that one version of operator can only manage one version of application):
1. no crd changes, but some fields are changes in cr, like the image link, should these fields be upgraded automatically (because usually new operator means new application, new images)?
2. crd is changed, but api version is not, should the CR be upgraded to new version automatically? like setting some default values for new fields? (I guess the answer is yes, because it is handled in operator reconcile loop, is it?)
3. crd and its api version is changed, should the CR be migrated to new api version automatically during operator upgrade?

**Environment**
* Kubernetes cluster kind: 
OpenShift

**Comment by awgreene** [comment]
The Operator Framework Mailing List recently had a wonderful [exchange](https://groups.google.com/g/operator-framework/c/K7zwQiCJVYg) on this topic.

**Comment by dinhxuanvu** [comment]
This issue is stale. Closed. Please feel free to reopen if needed.

**Comment by wslaasya** [comment]
Can someone address this problem. I didnt find the answer to this problem anywhere. I am not able to reopen this case too

**Comment by wslaasya** [comment]
@dinhxuanvu can you please reopen this thread i am looking for a solution to this problem
