### ISSUE TITLE
subscription in the namespace with manual approval will invalidate following subscription with automatic approval

### ISSUE THREAD

**Issue by just1900** [operator-framework/operator-lifecycle-manager#1355]
After Create a subscription with manual approval in one namespace, all the subscription with automatic approval will be invalidated, thus every generated installplan need to be approved manually.
After digging into the code below, I wonder what's the purpose of this design and when will this be fixed? 
https://github.com/operator-framework/operator-lifecycle-manager/blob/8985872bfd5888c8d7d49e4dfc9be162a87691e7/pkg/controller/operators/catalog/operator.go#L813

**Comment by flickerfly** [comment]
#1128 Might have some information that is related. Basically, OLM gets all Subscriptions as one InstallPlan. @njhale mentioned that was being rethought back in November, but there are also some dependency resolution issues at play for which [he pointed me to this doc](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/dependency-resolution.md#example-version-deadlock).

I know that's not an answer, but hopefully moves the discussion forward. I'm also trying to gain a more holistic understanding of how all this works.

**Comment by just1900** [comment]
@njhale @flickerfly That's to say, in order to avoid the dependency issue，OLM will try to resolve an installplan for all the subscriptions under one namespace. 
So, one subscription is related to one installplan only, but an installplan is related to multiple subscriptions, alright?

**Comment by dinhxuanvu** [comment]
This issue is stale. Closed. Please feel free to reopen if needed.
