### ISSUE TITLE
How to add nodeSelector to operator

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-lifecycle-manager#1359]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

**What did you do?**
I want to add `nodeSelector` to operator so that I can define where I want the operator to run. But for now, I did not found a good solution for this yet besides hardcode the `nodeSelector` in CSV file, can this be configurable? Or any best practise for this?

**Comment by joelanford** [comment]
@gyliu513 you may have already found this, but the node selector can be configured in the Subscription in `spec.config.nodeSelector`.
