### ISSUE TITLE
install.sh 0.14.1 - CSV "packageserver" failed to reach phase succeeded

### ISSUE THREAD

**Issue by dkirrane** [operator-framework/operator-lifecycle-manager#1360]
## Bug Report

**What did you do?**
I deployed a K8s 1.17.3 cluster (with kubeadm)

Then tried to install OLM with
```
wget https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.14.1/install.sh
bash install.sh 0.14.1
```

*I hit this error*
```
Package server phase: Installing
CSV "packageserver" failed to reach phase succeeded
```

*I checked it and it is stuck in Installing*.
```
kubectl get csv -n olm packageserver
NAME            DISPLAY          VERSION   REPLACES   PHASE
packageserver   Package Server   0.14.1               Installing
```

*logs*:
```
kubectl logs -n olm csv/packageserver
error: no kind "ClusterServiceVersion" is registered for version "operators.coreos.com/v1alpha1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```

**Environment**
* operator-lifecycle-manager version: 0.14.1

* Kubernetes version information: 1.17.3

* Kubernetes cluster kind: kubeadm 1.17.3 & kubectl 1.17.3

**Comment by exdx** [comment]
hi @dkirrane, we sometimes see this flakiness when setting up OLM via the script for multiple reasons. I think in this case it may be the CSV CRD didn't get installed fast enough on the api-server before being used elsewhere in the install script. 

Could you try again by chance? I'm reasonably sure it would work. We do need to address this flakiness though, it occurs both locally on minikube and in live clusters.

**Comment by csantanapr** [comment]
I just hit this same problem this on IBM Cloud IKS 1.16 
The script has a 50 retries with sleep 1 (1 second), after a few minutes debugging the the packageserver  was "succeed".

I think increasing the sleep maybe to 10, would go a long way. What do you think @exdx ?
