### ISSUE TITLE
What is the best practise to migrate from helm release to Go based operator

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-lifecycle-manager#1364]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

I have a metering helm release deployed in my cluster, and the metering service depend on MongoDB to persist some data.

I was now migrating the metering helm release to operators, does there are any best practise for how to migrate from a helm release to operator?

**Comment by flickerfly** [comment]
What would you expect to be different from simply starting fresh with a new Go or Ansible operator?

**Comment by gyliu513** [comment]
The major concern for a Go based operator is how to migrate some data, like some PV/PVC etc.

Some PVC are dynamically generated like some statefulset etc, so how to migrate those resources is a challenge for me.

**Comment by flickerfly** [comment]
Oh, like migrating the operator after it has already been deployed? Interesting and something I'd also like to see more information on.

**Comment by gyliu513** [comment]
This is exactly my case :)

Upgrade from a helm release with PV to Go based operators.

**Comment by flickerfly** [comment]
I opened the conversation about this in Slack: https://kubernetes.slack.com/archives/CAW0GV7A5/p1584365499243600

@fabiand said:

> unfortunately I don't think there's an easy answer, you'd have to manually migrate the data over. Probably you'd deploy the new application and manually migrate the data from the old to the new, then kill the old resources once you're sure the migration was successful. Pretty much the same as old-school redeployment/migration, AFAIK there's nothing in Kubernetes/operators to make this easier

**Comment by fabianvf** [comment]
that would be @fabianvf :)

**Comment by flickerfly** [comment]
@fabianvf My apologies! Corrected! 

Also, thanks for all the awesome work on the Ansible operator stuff. I'm standing on that foundation daily. Such a great tool!

**Comment by gyliu513** [comment]
Thanks @flickerfly and @fabianvf for the great discussion here!

So seems the best pracise for such case is 
1) Migrate data for helm releaes
2) Kill the helm release
3) Deploy the operator bind to the data in step 1)

Is this right? Thanks!

**Comment by miran248** [comment]
Interesting battle going on in here.

**Comment by dinhxuanvu** [comment]
This issue is stale. Closed. Please feel free to reopen if needed.
