### ISSUE TITLE
OLM fails to install packageserver with FailedDiscoveryCheck error 

### ISSUE THREAD

**Issue by aneeshkp** [operator-framework/operator-lifecycle-manager#1368]
## Bug Report

**What did you do?**
Running curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.14.1/install.sh | bash -s 0.14.1  on a fresh kubeadm 1.17.3 cluster

**What did you expect to see?**
CSV "packageserver"  succeeded

**What did you see instead? Under which circumstances?**
Package server phase: Installing
CSV "packageserver" failed to reach phase succeeded

**Environment**
operator-lifecycle-manager version: 0.14.1

Kubernetes version information: 1.17.3

Kubernetes cluster kind: kubeadm 1.17.3 & kubectl 1.17.3
**More Data**
*kubectl describe csv packageserver -n olm*
 shows  InstallWaiting       30s (x4 over 5m32s)  operator-lifecycle-manager  APIServices not installed 
 *oc get apiservice*
`v1.packages.operators.coreos.com       olm/v1-packages-operators-coreos-com   False (FailedDiscoveryCheck)   40m`
*kubectl get services*
`olm           v1-packages-operators-coreos-com              ClusterIP   10.100.189.147   <none>        443/TCP                  3m10s`
```
 grpc: addrConn.createTransport failed to connect to {operatorhubio-catalog.olm.svc:50051 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.110.249.27:50051: connect: connection refused". Reconnecting...
Services
olm           operatorhubio-catalog                         ClusterIP   10.110.249.27    <none>        50051/TCP                22m
olm           v1-packages-operators-coreos-com              ClusterIP   10.106.114.247   <none>        443/TCP                  3m31s
```
*kubectl get apiservices v1.packages.operators.coreos.com -o yaml*

```status:
  conditions:
  - lastTransitionTime: "2020-03-11T20:09:19Z"
    message: 'failing or missing response from https://10.97.129.138:443/apis/packages.operators.coreos.com/v1:
      Get https://10.97.129.138:443/apis/packages.operators.coreos.com/v1: net/http:
      request canceled while waiting for connection (Client.Timeout exceeded while
      awaiting headers)```
    reason: FailedDiscoveryCheck
`

**Comment by aneeshkp** [comment]
logs http://pastebin.test.redhat.com/843950

**Comment by aneeshkp** [comment]
Closing this issue. I found this morning it finally succeeded.

**Comment by davi5e** [comment]
What changed to make it work?

Same problem here...

**Comment by aneeshkp** [comment]
I worked after a few hours, but I was not successful in deploying Prometheus via operators. Moved on to kube-Prometheus on Kind cluster.

**Comment by mootezbessifi** [comment]
any useful answer here, package server is pending on installing status 
please see below pic 

![image](https://user-images.githubusercontent.com/5040743/114050791-3e6fde80-9895-11eb-867b-28441f654bda.png)

**Comment by alegmal** [comment]
@mootezbessifi Same issue here... GKE 1.19.8-gke.1600
tried olm 0.18.0 - same result

**Comment by fjammes** [comment]
I met the very same problem on GKE v1.20.6-gke.1400, does anybody have an idea please? Would it be possible to re-open the issue?

**Comment by shalin-hudda** [comment]
I am having the same issue with 1.19.9-gke.1900. I would appreciate some help as well.

**Comment by timflannagan** [comment]
@shalin-hudda It looks like https://github.com/operator-framework/operator-lifecycle-manager/issues/2234 is now tracking this failure.
