### ISSUE TITLE
The best practice for operator to watch all namespaces

### ISSUE THREAD

**Issue by chenzhiwei** [operator-framework/operator-lifecycle-manager#1385]
I found there are ways to make an operator watch all namespaces:

1. Set `WATCH_NAMESPACE=""` and install operator to a specific namespace

    The install mode is `A specific namespace on the cluster`.

2. Set `WATCH_NAMESPACE=""` and install operator to all namespaces

    The install mode is `All namespaces on the cluster`.

    The benefit is that the CRs managed by the operator can be viewed and edited in OpenShift Web Console.

    The annoying thing is that the operator CSV will be copied to all namespaces, if a single cluster have multiple users, they may confused that why this is an operator that installed on my namespace.

My operator needs to watch all namespaces, which one should I choose? Are there any other differences between them?

**Comment by raffaelespazzoli** [comment]
I have the same issue.

**Comment by chenzhiwei** [comment]
close this issue as we choose to set the namespace to "".
