### ISSUE TITLE
How to upgrade required operators

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-lifecycle-manager#1394]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

**What did you do?**

![image](https://user-images.githubusercontent.com/4461983/77050779-37193100-6a05-11ea-800d-50500432b8d5.png)

- I installed two operators, operator1 in namespace ns1 and operator2 in namespace ns2
- When I upgrade operator1, operator1 will also trigger upgrade of operator3, and the CRD of operator3 need to be upgraded
- For this case, how to upgrade operator3 in ns2?

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Comment by ecordell** [comment]
Required operators are upgraded as needed based on configured `Subscriptions` in the cluster. Please see the dependency docs for more details: https://olm.operatorframework.io/docs/concepts/olm-architecture/dependency-resolution/
