### ISSUE TITLE
Operator-lifecycle-manager for Kotlin/java

### ISSUE THREAD

**Issue by ghost** [operator-framework/operator-lifecycle-manager#1400]
I work for **Software Defined Network(SDN)** Solutioning. Current architecture is completely driven by java based **OpenDaylight** controller with **Netconf** protocol and **YANG** models. We feel that many functionalaties such as  Resource Life Cycle Management, Audit, Closed Loop Control, Scheduling, High Performance Data Store, Lifecycle Managements of Network Functions etc are missing or not properly developed in cloud native way. I feel Kubernetes with **Operator Framework** fills the gap in more efficient way. 

I feel the major challenge is migrating the network functions from **Java/Kotlin** to Go or Ansible Python framework. It involves lot of risk, business knowledge and cost constrains. We have huge amount of code base in java and it requires lot of integration with existing systems. And it is very difficult to transform all resources to GO developer.

So I started similar Operator Framework using Kotlin, Ktor using Kubernetes Java client. We are good in all aspects except Life Cycle Management.

https://github.com/brvith/3k-operator-sdk

Sample App : https://github.com/brvith/3k-operator-sdk/tree/master/sample-app

So we looking for information or guidance in developing Operator Life Cycle Management functionality:
1. Cluster Service Version Generation.
2. Bundle Create and Validation
3. Operator Hub deployment.

using **Gradle** or **Maven** Plugins.

**Comment by dinhxuanvu** [comment]
This issue is stale. Closed. Please feel free to reopen if needed.
