### ISSUE TITLE
E0325 during olm-deployment phase in queueinformer_operator.go

### ISSUE THREAD

**Issue by rashmi43** [operator-framework/operator-lifecycle-manager#1412]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

About an error message
## Question

**What did you do?**
Running a scan for my operator on redhat site

**What did you expect to see?**
Expected the ole-deployment phase for my operator to pass.

**What did you see instead? Under which circumstances?**
I get this error:
E0325 09:56:45.273915       1 queueinformer_operator.go:282] sync "test-operator" failed: {ibm-iam-operator-test alpha  {test-operators openshift-marketplace}} not found: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.30.220.157:50051: i/o timeout"
E0325 09:56:45.282366       1 queueinformer_operator.go:282] sync "test-operator" failed: {ibm-iam-operator-test alpha  {test-operators openshift-marketplace}} not found: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.30.220.157:50051: i/o timeout"
E0325 09:56:45.697207       1 

**Environment**
* operator-lifecycle-manager version:

Not sure what version RH uses.

* Kubernetes version information:

  

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by ecordell** [comment]
These errors are generally transient and resolve themselves. If they don't, they will be surfaced on the status of the `CatalogSource`.
