### ISSUE TITLE
CatalogSource sourceType: configmap creating 1000s of pods

### ISSUE THREAD

**Issue by kramvan1** [operator-framework/operator-lifecycle-manager#1421]
## Bug Report

Not sure what caused this, could be a timing issue.  At the time Kube API server was experiencing peek demand, and some APIs calls would timeout.

The catalog-operator somehow got stuck in hard loop creating catalog pods.
1000s of pod create requests hit the API server.

**What did you do?**

olm and catalog operator 0.14.1.
The configmap for an existing CatalogSource was updated, added another CSV to it, but nothing special here.

**What did you expect to see?**

The old catalog pod deleted and a new one put in it's place.

**What did you see instead? Under which circumstances?**

1000s of catalog pods getting created and running, causing the API server to start bogging down.
I'm guessing there might be an error path in the catalog pod create path that only waits for a small period of time for the pod to be created, then tries it again, even tho the original request eventually worked.

**Environment**
* operator-lifecycle-manager version: 0.14.1

* Kubernetes version information:

1.16

* Kubernetes cluster kind:  IBM Cloud

**Possible Solution**

The catalog pod should simply use a Deployment spec, that would allow complete control over this pod.

**Additional context**

**Comment by kramvan1** [comment]
This fix is still needed, using a deployment would be best here.

**Comment by kramvan1** [comment]
Bump

**Comment by kramvan1** [comment]
This is still an issue with OLM.

**Comment by pamelachristie** [comment]
Bump

**Comment by pamelachristie** [comment]
Bump

**Comment by ecordell** [comment]
Is there a reason you're still using `configmap` type catalogs? Although they have not been completely removed, they are not receiving new features.

**Comment by pamelachristie** [comment]
We've been using configmaps since we started using OLM. Is there a different type that is recommended by the community?

**Comment by dinhxuanvu** [comment]
We typically use configmap-based catalogsources for testing. We only use the image-based catalog for production. I recommend you to move away from configmap-based catalog and build a catalog image to use for the catalog.
/close
