### ISSUE TITLE
[Best Practise] How to release a product with operator

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-lifecycle-manager#1427]
As a product, I may not able to publish the operator to operatorhub, as I need to customer buy the product first if they want to install.

So any best practice if I want to release a product via operator? Thanks!

**Comment by dmesser** [comment]
@gyliu513 you probably meant to post this against https://github.com/operator-framework/community-operators ?

**Comment by gyliu513** [comment]
Thanks @dmesser , opened an issue at https://github.com/operator-framework/community-operators/issues/1508
