### ISSUE TITLE
How to enable license agreement when install operator

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-lifecycle-manager#1430]
![image](https://user-images.githubusercontent.com/4461983/78645969-ecdfed00-78ea-11ea-9a75-03a8fead6891.png)

I have a requirement, when a customer install an operator, I want this customer accept the license first before install the operator, but from UI and CLI, I did not see we have a option to enable the customer accept a license before install an operator, any comments for this? Thanks!

**Comment by ecordell** [comment]
licenses can be linked to via the `links` in the
