### ISSUE TITLE
How to add "operatorhub.io" as a source for operators in OpenShift 4.3?

### ISSUE THREAD

**Issue by titou10titou10** [operator-framework/operator-lifecycle-manager#1437]
How to add`"operatorhub.io"` as a source for operators in OpenShift 4.3?
Creating the "official"`CatalogSource`object in project`openshift-marketplace` does not work
Help !

CatalogSource yaml:

    apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
      name: operatorhubio-catalog
      namespace: openshift-marketplace
    spec:
      sourceType: grpc
      image: quay.io/operator-framework/upstream-community-operators:latest
      displayName: Community Operators
      publisher: OperatorHub.io

`oc describe pod operatorhubio-catalog-glftd`:

    Events:
      Type     Reason     Age        From                                       Message
      ----     ------     ----       ----                                       -------
      Normal   Scheduled  <unknown>  default-scheduler                          Successfully assigned openshift-marketplace/operatorhubio-catalog-glftd to xxxx.xxxx.xxxx.xxxx.xxxx
      Normal   Pulling    28m        kubelet, xxxx.xxxx.xxxx.xxxx.xxxx Pulling image "quay.io/operator-framework/upstream-community-operators:latest"
      Normal   Pulled     28m        kubelet, xxxx.xxxx.xxxx.xxxx.xxxx Successfully pulled image "quay.io/operator-framework/upstream-community-operators:latest"
      Normal   Created    28m        kubelet, xxxx.xxxx.xxxx.xxxx.xxxxCreated container registry-server
      Normal   Started    28m        kubelet, xxxx.xxxx.xxxx.xxxx.xxxxxStarted container registry-server
      Warning  Unhealthy  27m        kubelet, xxxx.xxxx.xxxx.xxxx.xxxxReadiness probe failed: command timed out
      Warning  Unhealthy  25m        kubelet, xxxx.xxxx.xxxx.xxxx.xxxxLiveness probe failed: command timed out

Logs of the catalogoperator pod: 

    time="2020-04-09T18:42:15Z" level=warning msg="couldn't find service in cache" service=operatorhubio-catalog
    time="2020-04-09T18:42:17Z" level=info msg="state.Key.Namespace=openshift-marketplace state.Key.Name=operatorhubio-catalog state.State=CONNECTING"
    time="2020-04-09T18:42:37Z" level=info msg="state.Key.Namespace=openshift-marketplace state.Key.Name=operatorhubio-catalog state.State=TRANSIENT_FAILURE"
    time="2020-04-09T18:42:38Z" level=info msg="state.Key.Namespace=openshift-marketplace state.Key.Name=operatorhubio-catalog state.State=CONNECTING"
    time="2020-04-09T18:42:38Z" level=info msg="state.Key.Namespace=openshift-marketplace state.Key.Name=operatorhubio-catalog state.State=READY"
    time="2020-04-09T18:42:51Z" level=info msg="state.Key.Namespace=openshift-marketplace state.Key.Name=operatorhubio-catalog state.State=CONNECTING"
    time="2020-04-09T18:42:51Z" level=info msg="state.Key.Namespace=openshift-marketplace state.Key.Name=operatorhubio-catalog state.State=TRANSIENT_FAILURE"
    time="2020-04-09T18:42:52Z" level=info msg="state.Key.Namespace=openshift-marketplace state.Key.Name=operatorhubio-catalog state.State=CONNECTING"
    time="2020-04-09T18:43:07Z" level=info msg="state.Key.Namespace=openshift-marketplace state.Key.Name=operatorhubio-catalog state.State=READY"

`oc logs operatorhubio-catalog-glftd`

    time="2020-04-09T17:39:46Z" level=info msg="serving registry" database=/bundles.db port=50051

**Comment by ecordell** [comment]
The steps you tried should have worked, there may have been a temporary issue with quay or with the network at the time you tried.

Please re-open if this can be reproduced.

**Comment by netaskd** [comment]
set `image: quay.io/operatorhubio/catalog:latest` for OpenShift 4.12/4.13 and it works like a charm
