### ISSUE TITLE
Active Subscription does not recreate CSV if deleted

### ISSUE THREAD

**Issue by kramvan1** [operator-framework/operator-lifecycle-manager#1441]
## Bug Report
**What did you do?**

- Create CatalogSource backed by a configmap with several CSVs in it.
- Create a Subscription to one of the channels in the catalog
- See the CSV get created along with the operator
- After some time, delete the CSV
- The Subscription becomes an orphan, no CSV is ever recreated for it

**What did you expect to see?**

When the Subscription reconciles and there is no CSV in place for it, is should be re created.

**What did you see instead? Under which circumstances?**

CSV was never recreated.   ONLY if you delete and recreate the Subscription does it come back.

**Environment**
* operator-lifecycle-manager version:

0.14.1

* Kubernetes version information:

1.16

* Kubernetes cluster kind: 

IKS

**Possible Solution**

Any subscription change, channel update for example, should cause the CSV to be triggered just like delete and recreate the subscription.

**Additional context**

**Comment by kramvan1** [comment]
@ecordell Any thoughts on this one?   Right now we have to workaround with a delete/create of subscription each time the catalog is changed.

**Comment by kramvan1** [comment]
Bump

**Comment by pamelachristie** [comment]
Bump

**Comment by pamelachristie** [comment]
Bump

**Comment by ecordell** [comment]
This has been bumped, but is it reproducible today? I believe that the new resolver that landed last year would have fixed this.

**Comment by William-Newshutz** [comment]
We are using olm 0.16.1. When we delete the CSV neither the InstallPlan nor the Subscription causes the CSV to be regenerated. I deleted the CSV yesterday and today I checked if it was regenerated.
```
k get csv -A
No resources found.

k get installPlan -A
NAMESPACE       NAME            CSV                     APPROVAL    APPROVED
ibm-operators   install-9gwrn   istio-operator.v1.8.2   Automatic   true

k get pod -n ibm-system
NAME                                READY   STATUS    RESTARTS   AGE
addon-catalog-source-8cxqr          1/1     Running   0          18h
catalog-operator-5755496c77-8pxsj   1/1     Running   0          18h
olm-operator-796f57756c-p487h       1/1     Running   0          18h

k get deploy -n ibm-system -o wide
NAME               READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS         IMAGES                                                   SELECTOR
catalog-operator   1/1     1            1           18h   catalog-operator   registry.ng.bluemix.net/armada-master/olm:0.16.1-IKS-5   app=catalog-operator
olm-operator       1/1     1            1           18h   olm-operator       registry.ng.bluemix.net/armada-master/olm:0.16.1-IKS-5   app=olm-operator
```
