### ISSUE TITLE
Is that possible to access CatalogSource with grpc TLS

### ISSUE THREAD

**Issue by sunbinnnnn** [operator-framework/operator-lifecycle-manager#1475]
## Feature Request

Default port for catalogsource grpc is 50051 whitch not support TLS, and if we set catalogsource spec with `address` instead of `image`, it will use bare grpc to connect. Can we support using gprc with transport credenitals?

**Is your feature request related to a problem? Please describe.**
If we use ingress to expose catalogsource to other clusters to use, may need to get operator bundles from upstream catalog via tls port(like 443).

**Describe the solution you'd like**
Is that possible to support both `grpc.WithTransportCredentials` and `grpc.WithInsecure` when connecting to catalogsource

**Comment by dmesser** [comment]
I agree internal cluster communication should also be secure. However I am interested in your use case of exposing the catalog grpc endpoint to other clusters via ingress. What about having the other clusters use the same catalog image with their own local `CatalogSource` reference?

**Comment by sunbinnnnn** [comment]
> I agree internal cluster communication should also be secure. However I am interested in your use case of exposing the catalog grpc endpoint to other clusters via ingress. What about having the other clusters use the same catalog image with their own local `CatalogSource` reference?

em...In my case, the outside k8s cluster can not access local harbor(caused by network policy), and if we update catalog image in local harbor, the outside catalog may not be synced.
Besides, `CatalogSource` offers `address` field, is there any best practices for it?

**Comment by dmesser** [comment]
@sunbinnnnn yes,`address` exists and can be used when you don't supply `image` but run a grpc endpoint. This is from an older implementation when creating these images wasn't something OLM owned.

**Comment by dinhxuanvu** [comment]
This issue is stale. Closed. Please feel free to reopen if needed.
