### ISSUE TITLE
Use Kubeadm instead of Minikube to Support Local Power Build

### ISSUE THREAD

**Issue by aemperador** [operator-framework/operator-lifecycle-manager#1477]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
How to implement a specific feature

## Question

**What did you do?**
I am working to add IBM Power (PPC64LE) support for OLM. 

I have run into a few issues with the local setup including that Minikube support for Power is limited (almost nonexistent at this time).
I would like to either change the run-local Make target to use kubeadm for all local runs or conditionally choose kubeadm if the architecture is Power.
I would like advice on what would be more acceptable:
1. Updating to use kubeadm for all
2. Conditionally use kubeadm for PowerPC architectures and Minikube for X86

Currently, I have modified the scripts/build_local.sh file to use kubeadm. This allows me to build OLM locally on Power. 

```
if [[ "$(kubectl config current-context)" =~ ^kubernetes-admin@kubernetes$ ]]; then 
  kubeadm reset # shut down if currently running
  kubeadm init
  kubectl config use-context kubernetes-admin@kubernetes
fi

docker build -f local.Dockerfile -t quay.io/operator-framework/olm:local -t quay.io/operator-framework/olm-e2e:local ./bin
docker build -f test/e2e/hang.Dockerfile -t hang:10 ./bin

if [ -n "$KIND" ]; then
   kind load docker-image quay.io/operator-framework/olm:local
   kind load docker-image quay.io/operator-framework/olm-e2e:local
   kind load docker-image hang:10
fi

```

**Environment**
* operator-lifecycle-manager version:

2dea823abbacc286715254078d28b5058655362e

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/ppc64le"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/ppc64le"}
  

* Kubernetes cluster kind: 

Local: single node cluster

**Additional context**
We are wanting to use OLM on Power, so we need to be able to build it on the architecture.

**Comment by aemperador** [comment]
Tagging to get some feedback on this issue.
@exdx 
@ecordell 
@dmesser

**Comment by dmesser** [comment]
@aemperador `run-local` has been put in place for local development of OLM itself, not for deployment or testing. For the latter applying the generated manifests should be sufficient.

Regarding `kubeadm` - we already have variety with `kind` or `minikube`, I think adding even more options will make things difficult to maintain in the long-run.

**Comment by aemperador** [comment]
@dmesser Can you elaborate on the manifests? 

I am working to get a PPC64LE image of OLM built in quay and the easiest way for me to test my progress is to use run-local which requires it to built on Power. 

I was attempting to use MiniKube which does not have Power support. I will try to get a Kind build working locally in Power. 

Could you also point me to the location of the Prow CI configuration? I can't seem to find it in the project and it seems to be the way I have to build the image for Power is to cross compile the binaries.
