### ISSUE TITLE
Previous CSV Version doesn't get deployed

### ISSUE THREAD

**Issue by kahootali** [operator-framework/operator-lifecycle-manager#1492]
## Bug Report

**What did you do?**
I am using Openshift 4.3 and when I deploy an Operator from Operator Hub e.g. ElasticSearch Operator and lets say its CSV version was 4.3.10, and it gets deployed correctly but I need Manifest as Code so I get the manifests in yaml format of Operator Group, Subscription & CSV and save it in our Version Control, and then if I uninstall the Operator, and after some days when CSV version is updated, lets say as latest 4.3.13, if I apply the old manifests again, it doesn't work and Operator doesn't get installed saying **Pending Update, Catalog Source was Removed** and I have to deploy manually again which I don't want as I want Manifest as Code

**What did you expect to see?**
Previous CSV Version should also get deployed

**What did you see instead? Under which circumstances?**
Previous CSV doesn't get deployed, rather one has to again manually deploy the latest version

**Comment by dinhxuanvu** [comment]
This issue is stale. Closed. Please feel free to reopen if needed.
