### ISSUE TITLE
OLM fails to install CRDs on k8s 1.18.2

### ISSUE THREAD

**Issue by Mercwri** [operator-framework/operator-lifecycle-manager#1493]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

OLM Installation fails and leaves errors behind in api-server log

## Question

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).
applied the CRD and and ORM manifests.
**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).
OLM running and CRDs available for creating operators
**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

`E0429 19:03:05.498051       1 customresource_handler.go:652] error building openapi models for clusterserviceversions.operators.coreos.com: ERROR $root.definitions.com.coreos.operators.v1alpha1.ClusterServiceVersion.properties.spec.properties.install.properties.spec.properties.deployments.items.<array>.properties.spec.properties.strategy.properties.rollingUpdate.properties.maxSurge has invalid property: anyOf
ERROR $root.definitions.com.coreos.operators.v1alpha1.ClusterServiceVersion.properties.spec.properties.install.properties.spec.properties.deployments.items.<array>.properties.spec.properties.strategy.properties.rollingUpdate.properties.maxUnavailable has invalid property: anyOf
ERROR $root.definitions.com.coreos.operators.v1alpha1.ClusterServiceVersion.properties.spec.properties.install.properties.spec.properties.deployments.items.<array>.properties.spec.properties.template.properties.spec.properties.containers.items.<array>.properties.lifecycle.properties.postStart.properties.httpGet.properties.port has invalid property: anyOf`

**Environment**
* operator-lifecycle-manager version:
0.14.1

* Kubernetes version information:
1.18.0

  Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by dinhxuanvu** [comment]
Hi,

This seems to be related to a v1 CRD support bug that we encountered recently. It has been resolved. The new (coming) release should no longer have this issue.

Thanks,
Vu

**Comment by ecordell** [comment]
Closing as this has been fixed, as Vu mentioned.
