### ISSUE TITLE
OOM catalog

### ISSUE THREAD

**Issue by kfox1111** [operator-framework/operator-lifecycle-manager#1497]
I started a minikube with 8g of ram.

I installed the olm:

curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.14.1/install.sh | bash -s 0.14.1

Most things came up but the catalog was in a crash loop for a while:
NAME                                READY   STATUS    RESTARTS   AGE
catalog-operator-86f777cc59-4qrq7   1/1     Running   0          16m
olm-operator-5fd48d8cd4-gcm44       1/1     Running   0          16m
operatorhubio-catalog-ghkjm         0/1     Running   7          16m
packageserver-75946c9b59-2wrmj      1/1     Running   0          16m
packageserver-75946c9b59-vnfjw      1/1     Running   0          16m

doing a minikube ssh dmesg:
[  738.836068] Memory cgroup out of memory: Kill process 10034 (registry-server) score 2018 or sacrifice child
[  738.836350] Killed process 10034 (registry-server) total-vm:195796kB, anon-rss:92640kB, file-rss:14324kB, shmem-rss:0kB

There is plenty of ram left on the system, so it seems like the limit set on the pod is too low.

**Comment by AndrienkoAleksandr** [comment]
> operatorhubio-catalog-ghkjm 0/1 Running 7 16m

+1.  operatorhubio-catalog is very unstable and 
CrashLoopBackOff restarting...

**Comment by andresmgot** [comment]
I am also finding this issue. I see it was fixed here: https://github.com/operator-framework/operator-lifecycle-manager/pull/1389

But the latest release (0.14.2) doesn't include this change. When can we expect a new release? I am using `latest` for the moment for the image in the `catalog-operator`  deployment but that's far from ideal. 

I see in this comment: https://github.com/operator-framework/operator-lifecycle-manager/issues/1415#issuecomment-620258287 that @ecordell is planning a release, any update?

**Comment by kfox1111** [comment]
I think this is fixed, or at least worked around in 0.15+.
