### ISSUE TITLE
How to customize container image references when using Operators/OLM?

### ISSUE THREAD

**Issue by mmellin** [operator-framework/operator-lifecycle-manager#1517]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

This is a general context question relating to the use of Helm-based Operators and OLM.

## Question
I have a use case to deploy applications in various 3rd party airgapped environments. This is defined as one without Internet connectivity, but K8s clusters nodes do have access to a container registry and an internal private network. I have create a set of Helm based Operators from existing Helm charts and would like to use OLM to manage their lifecycle.  However, I've build these images referencing my own private container registry, so OLM catalog image, image references within the CRs/Helm charts all point to my repo.  Here is an example of such usage:

```yaml
image: my-private-registry.com/app1
tag: v1
```

If I want a user to download the catalog image and install my Operator(s) on their airgapped setup, I must first push all container images to their repo (catalog, operator, etc). 

**My question is** how then do I adjust the container image references programmatically (such as in the CatalogSource) to point to this new customer image registry so that the user can successfully install the catalog, operators and application?

The main focus is that whatever environment I install my Operators into, airgapped or not, they will never have access to `my-private-registry.com/` and I will always need to adjust where the images are being pulled from.  To date via searching I have not figured out a good programmatic approach.  Any help is appreciated!

** Additional Context**
These applications (containers, Helm charts or operators) will never be publicly accessible, meaning that we will not be publishing them on the Web for Internet based consumption. Thus the original container image references will be to wherever my build system is (`my-private-registry.com`) and we assume we will not know the destination image registry until installation time.

**Comment by dinhxuanvu** [comment]
There is a repo about disconnected mirror process that may be helpful: https://github.com/openshift/oc-mirror
