### ISSUE TITLE
How to troubleshoot failed operator upgrade

### ISSUE THREAD

**Issue by aharbis** [operator-framework/operator-lifecycle-manager#1518]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

Support / troubleshooting question about OLM operator upgrades.

## Question

**What did you do?**

We have a couple of CSVs:

- `0.9.0` and `0.10.0`
- `0.10.0` replaces `0.9.0`
- `0.10.0` defines `olm.skipRange: ">=0.9.0 <0.10.0"`

We've created a bundle for each CSV, and added both bundles to an index image using a command like this:

```
opm index add \
  --from-index private.registry.com/my-operator-index:0.9.0 \
  --bundles private.registry.com/my-operator-bundle:0.10.0 \
  --tag private.registry.com/my-operator-index:0.10.0 \
  --build-tool docker
```

OLM is unable to install `0.10.0` directly, or upgrade from `0.9.0`. In the OLM UI, it seems to install `0.9.0` first, then complain it cannot upgrade it due to `Catalog source was removed`. However, I can verify that the `0.9.0` and `0.10.0` bundles are both listed in the index.

**What did you expect to see?**

OLM should be able to:

- install `0.10.0` directly, as the `skipRange` should be able to skip the only other CSV version that exists, which it replaces as well.
- upgrade `0.9.0` to `0.10.0`

**What did you see instead? Under which circumstances?**

The `0.10.0` CSV is not installed, and stuck in `UpgradePending` status. The `0.9.0` is stuck in `Cannot update` status with message `Catalog source was removed`.

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

```
$ oc version
Client Version: openshift-clients-4.3.0-201910250623-88-g6a937dfe
Server Version: 4.4.3
Kubernetes Version: v1.17.1
```
 
* Kubernetes cluster kind: 

OCP 4.4.3

**Additional context**

I have looked through the logs of the `olm-operator` and `catalog-operator` pods in the `openshift-operator-lifecycle-manager` namespace, but I cannot find any logs that would indicate **why** the update / upgrade fails. It just shows the `0.9.0` install plan completely successfully, then nothing about an attempt to upgrade to `0.10.0`.

I used `opm` version `v1.12.2` to build the index. I am using `operator-sdk` version `v0.17.0` to build the bundles and generate the CSVs.

**Comment by aharbis** [comment]
It's worth noting that prior to our release of our `0.10.0` CSV, the `0.9.0` CSV was the only one which existed. `0.9.0` was able to install in OLM fine. Even now, `0.9.0` installs cleanly (the upgrade just fails).

So from that perspective, I'm rather confident our CSV, bundle, and index pipeline is good enough for a single CSV/CRD pair to get installed via OLM. The problem here is the upgrade path.

I've read through [How do operator upgrades work in Operator Lifecycle Manager (OLM)?](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/how-to-update-operators.md) but I can't find anything that's out of place for us.

**Comment by cdjohnson** [comment]
I've tried to recreate this problem with my own operator (same channels, same versions, similar CSV, but can't).  It seems like there is something unusual with how the operator is behaving.

I've enabled `debug: true` on both the `olm-operator` and `catalog-operator` to see if anything looks interesting, but there isn't anything obvious.  This WORKS on OpenShift 4.3, but fails on 4.4.3

**Comment by aharbis** [comment]
I would add that with `debug: true` on the `catalog-operator`, I was able to get this log out which seemed to provide a little insight into why this is failing on 4.4.3:

>time="2020-05-13T22:25:22Z" level=debug msg="error fetching csv listed in subscription status" channel=beta currentCSV=my-operator.v0.10.0 error="clusterserviceversions.operators.coreos.com \"my-operator.v0.10.0\" not found" id=6USzy namespace=my-operator-demo pkg=my-operator source=my-operator-catalog sub=my-operator

The `catalog-operator` seems to claim it cannot find the `0.10.0` CSV. However, I can query my index directly and validate that it has both the `0.9.0` and `0.10.0` bundles. Additionally, just to restate it, this works on 4.3.13.

**Comment by aharbis** [comment]
bump

**Comment by dinhxuanvu** [comment]
I recommend you to upgrade to newer version of OLM to take advantage of the new resolver. Then, you can check the catalog-operator log for the info. When the resolution fails, there is also an event generated in the default namespace for more information as well.
