### ISSUE TITLE
Set labels for the operator Deployment created via the ClusterServiceVersion

### ISSUE THREAD

**Issue by dacleyra** [operator-framework/operator-lifecycle-manager#1522]
## Feature Request

Would like the ability to set labels for the operator Deployment created via the ClusterServiceVersion.

As far as I understand, only owner labels are set by OLM, and the operator Deployment is limited to setting the DeploymentSpec, with no ability to set any metadata such as labels

https://github.com/operator-framework/operator-lifecycle-manager/blob/release-4.3/pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go#L62
https://github.com/operator-framework/operator-lifecycle-manager/blob/release-4.3/pkg/controller/install/deployment.go#L84

**Comment by ishankhare07** [comment]
What's the current status of this issue. I would be interested to take this up if no one is working on it.

**Comment by gee4vee** [comment]
Also looking for this functionality. I see a PR was merged with a fix? What version is it available in?
