### ISSUE TITLE
Error message appearing in operator log: Failed to watch *v1.PackageManifest

### ISSUE THREAD

**Issue by phantomjinx** [operator-framework/operator-lifecycle-manager#1531]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

- Incorporated OLM support into the [syndesis](https://github.com/phantomjinx/syndesis) [operator](https://github.com/phantomjinx/syndesis/blob/olm-jaeger/install/operator/pkg/syndesis/olm/subscription.go).
- Executing the syndesis operator on openshift, successfully queries for CSVs, subscriptions & if necessary installs the desired jaeger subscription. This all works.
- In the syndesis operator log, the following error message is generated repeatedly:

`
E0519 20:18:59.338786       1 reflector.go:382] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.PackageManifest: unknown (get packagemanifests.packages.operators.coreos.com)
`
- This does not impact the functionality in any way so is just noise in the logs but obviously something is not totally happy.

**What did you expect to see?**
No errors

**What did you see instead? Under which circumstances?**
The error being generated seems to bear little relation to the code actually being called. Is it perhaps due to the inclusion of the operator-lifecycle-manager packages?

**Environment**
* operator-lifecycle-manager version:
  - k8s.io/client-go v0.17.4
  - github.com/operator-framework/operator-lifecycle-manager v0.0.0-20200321030439-57b580e57e88
  - github.com/operator-framework/operator-marketplace v0.0.0-20200424213926-c53c1e365d90
  - github.com/operator-framework/operator-sdk v0.17.0

* Also, upgraded to following [here](https://github.com/phantomjinx/syndesis/blob/olm-jaeger-upgrade/install/operator/pkg/syndesis/olm/subscription.go) & still get the same error messages:
  - k8s.io/client-go v0.18.2
  - github.com/operator-framework/operator-lifecycle-manager v0.0.0-20200508205316-9ffa1fdb8dcf
  - github.com/operator-framework/operator-marketplace v0.0.0-20200515051804-e0148822df25
  - github.com/operator-framework/operator-sdk v0.0.0-20200428193249-b34ae44ff198

* Kubernetes version information:
  - Client Version: 4.3.13
  - Kubernetes Version: v1.16.2

* Kubernetes cluster kind: 
  - crc version: 1.9.0+a68b5e0
  - OpenShift version: 4.3.10

**Possible Solution**

**Additional context**

**Please feel free to ask for far more information, if required.**

**Comment by njhale** [comment]
Hi @phantomjinx,

`PackageManifests` are supplied by an aggregated API that doesn't support watch. The error you're encountering seems to be from an informer trying to list/watch this resource. The message also indicates that this is occurring in `controller-runtime` -- my guess is that it happens on Get with the dynamic client to maintain the cache (see the [go-docs](https://godoc.org/sigs.k8s.io/controller-runtime#hdr-Clients_and_Caches)).

We can revisit watch on `PackageManifest` resources to clear the message, but for now you can probably construct a client that doesn't use the cache.

Hope that helps some. Please let me know if you run into any roadblocks and I'll try to help further.

**Comment by dinhxuanvu** [comment]
The issue is stale. Closed. Please feel free to reopen if needed.
