### ISSUE TITLE
Add Data Protection category to OperatorHub in OpenShift/OLM

### ISSUE THREAD

**Issue by prashantokochavara** [operator-framework/operator-lifecycle-manager#1532]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We have a data protection solution for Kubernetes applications that are deployed via Operators, Helm or Label. No existing category aligns with the solution we provide.

**Describe the solution you'd like**
We would like to have a "Data Protection" category created within OperatorHub.
I already have an issue that I had created for this:  https://github.com/operator-framework/community-operators/pull/1362#issuecomment-602487288
But I am not sure if the same request would suffice, hence creating another one here.

**Comment by dinhxuanvu** [comment]
The issue is stale. Closed. Please feel free to reopen if needed.
