### ISSUE TITLE
How to generate InstallPlan manually from a CSV?

### ISSUE THREAD

**Issue by rvsingh011** [operator-framework/operator-lifecycle-manager#1545]
## How olm generates the roles and permissions from a given CSV file. 

**What did you do?**

My goal is to install an operator directly from CSV files. Like supporting a user who comes with a link like this: 
https://github.com/operator-framework/community-operators/tree/master/community-operators/api-operator/1.1.0 
These are the steps which I am following right now - 
1) Apply all CRD files. 
2) Run a script that reads the CSV file for role and permission requirements. 
3) Generate appropriate service account, Roles, and permissions through the script. 
4) Apply all the generated files. 
5) Apply the CSV file. 

**What did you expect to see?**
I am able to install operators. I want to manually generate the installPlan for the given CSV.

**Comment by dinhxuanvu** [comment]
The issue is stale. Closed. Please feel free to reopen if needed.
