### ISSUE TITLE
How to debug operators stuck in "UpgradePending"

### ISSUE THREAD

**Issue by IBMRob** [operator-framework/operator-lifecycle-manager#1548]
## Type of question

We are developing a new operator. More often than not after deleting the operator and then reinstalling it, it gets stuck in "UpgradePending"

## Question

**What did you do?**

Install instance of our operator
Deploy instance of operator
Delete instance Operator
Delete catalogSource
Create new catalogSource to use new build
Re-install instance of our operator

**What did you expect to see?**
Operator installs like normal. 

**What did you see instead? Under which circumstances?**

The operator gets stuck in "UpgradePending". 
The installPlan for the CSV is showing as "Complete". It's not clear what else I should be looking at to debug this issue. I have looked at the `catalog-operator` and `olm-operator` although can't see anything obvious there. 

If you delete the project and start again it seems to install fine again so its as if something isn't being cleaned up properly

**Environment**
* operator-lifecycle-manager version: Version in OCP 4.4.3
* Kubernetes version information: v1.17.1
* Kubernetes cluster kind: OCP 4.4.3

**Additional context**
Add any other context about the question here.

**Comment by IBMRob** [comment]
Interestingly it looks like bugs in reporting

InstallPlan showing complete
![image](https://user-images.githubusercontent.com/2182970/83016730-5bebdf00-a01a-11ea-843d-7bb750e08f29.png)
But clicking on the CSV shows 404
![image](https://user-images.githubusercontent.com/2182970/83016761-660ddd80-a01a-11ea-86ec-21199c6c454f.png)

**Comment by horis233** [comment]
@IBMRob Hi Rob, I open an issue at https://github.com/operator-framework/operator-lifecycle-manager/issues/1570.
I think they are caused by the same reason.

**Comment by dinhxuanvu** [comment]
The issue is stale. Closed. Please feel free to reopen if needed.
