### ISSUE TITLE
Multiple pods created for CatalogSource when updateStrategy of registryPoll enabled

### ISSUE THREAD

**Issue by jdockter** [operator-framework/operator-lifecycle-manager#1555]
## Bug Report
When installing a CatalogSource with updateStrategy of registryPoll seeing multiple pods created in the same namespace and the OperatorHub UI in cluster is not being refreshed with the latest catalogsource operator bundle contents.

**What did you do?**

1.  Created an catalog index image using opm 1.11.1 with several operator bundles.
2.  Applied catalogsource resource to cluster with updateStrategy under the openshift-marketplace project
```
  updateStrategy:
    registryPoll:
      interval: 45m
```
3.  Original catalog pod is created
```
 oc get pods
NAME                                    READY   STATUS    RESTARTS   AGE
certified-operators-7574d78974-t9gmn    1/1     Running   0          6h34m
community-operators-5f758d4679-zbsq7    1/1     Running   0          23h
ibm-apiconnect-catalog-gxqdv            1/1     Running   0          14h
**ibm-operator-catalog-x6w4l              1/1     Running   0          21m**
marketplace-operator-5fcf68c65c-xfp4m   1/1     Running   0          23h
opencloud-operators-6794575568-5c5fm    1/1     Running   0          23h
redhat-marketplace-5c54484748-2bznr     1/1     Running   0          17h
redhat-operators-6776b9b98b-fhbzc       1/1     Running   0          20h
```

4.  Build new catalog index image with new operator bundle.  Push catalog index image with same tag to registry.

5.  Wait for 45 mins plus and second catalog pod is created and OperatorHub UI for cluster does not show new operator from catalog index image
```
oc get pods
NAME                                    READY   STATUS    RESTARTS   AGE
certified-operators-7574d78974-t9gmn    1/1     Running   0          7h3m
community-operators-5f758d4679-zbsq7    1/1     Running   0          24h
ibm-apiconnect-catalog-gxqdv            1/1     Running   0          15h
**ibm-operator-catalog-pbwrf              1/1     Running   0          23s**
**ibm-operator-catalog-x6w4l              1/1     Running   0          49m**
marketplace-operator-5fcf68c65c-xfp4m   1/1     Running   0          24h
opencloud-operators-6794575568-5c5fm    1/1     Running   0          24h
redhat-marketplace-5c54484748-2bznr     1/1     Running   0          18h
redhat-operators-6776b9b98b-fhbzc       1/1     Running   0          21h
```

**What did you expect to see?**
Original catalog pod removed and new pod would replace, ultimately refreshing OperatorHub UI will new tile for operator bundle added in new catalog

**What did you see instead? Under which circumstances?**
Two catalog pod and no update to OperatorHub UI in cluster.

**Environment**
Not sure how to tell version of OLM on clusters but tested on OCP 4.4.3 and 4.5.0-0.nightly-2020-05-10-160515

* Kubernetes version information:

* Kubernetes cluster kind: 
CatalogSource

**Possible Solution**

**Additional context**

**Comment by dinhxuanvu** [comment]
There is a bug associated with this issue that has been merged recently: https://github.com/operator-framework/operator-lifecycle-manager/pull/1482
Hopefully that will resolve this issue.

**Comment by jdockter** [comment]
@dinhxuanvu how are OLM fixes rolled out, what OCP versions would it apply to, and how could I confirm that my cluster has the fix?

**Comment by dinhxuanvu** [comment]
It is just merged in master AKA 4.5 and it is in progress to be backport to 4.4.z so it should be available in the next z-stream for 4.4 which is 4.4.1 I believe.

**Comment by huizengaJoe** [comment]
Hi @dinhxuanvu just for my understanding of the process, if it is merged into master does that mean that I should see it in the next 4.5 nightly build and if I where to spin up a new cluster via the try.openshift.com https://cloud.redhat.com/openshift/install/pre-release installation process it should be there?  or is there some lag before it reaches this point?

**Comment by dinhxuanvu** [comment]
@huizengaJoe Correct. The fix should be in the latest nightly build of 4.5.

**Comment by jdockter** [comment]
@dinhxuanvu is it safe to assume the back port did not work from this comment on 4.4, https://github.com/operator-framework/operator-lifecycle-manager/pull/1482#issuecomment-635152577

**Comment by dinhxuanvu** [comment]
@jdockter Ah. No worries. It only meant the bot can't auto-cherry-pick the commits in PR due to code conflicts. The author will have manually cherry-pick the commits to create the backport PR. Bowen will take care of that.

**Comment by dinhxuanvu** [comment]
I believe this issue has been resolved.
