### ISSUE TITLE
Duplicate apply of 0.15.1 clusterserviceversions.crd.yaml hangs

### ISSUE THREAD

**Issue by pamelachristie** [operator-framework/operator-lifecycle-manager#1574]
## Bug Report

**What did you do?**
Ran the following command twice:
```
kubectl apply -f https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/manifests/0.15.1/0000_50_olm_00-clusterserviceversions.crd.yaml
```

**What did you expect to see?**
The first attempt should create the resource. The second apply should not hang, but instead return a message that the crd is unchanged.

**What did you see instead? Under which circumstances?**
First attempt created the resource. The second apply hung indefinitely.
```
Pamelas-MacBook-Pro-2:~ pamelachristie$ k apply -f https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/manifests/0.15.1/0000_50_olm_00-clusterserviceversions.crd.yaml
customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com created
Pamelas-MacBook-Pro-2:~ pamelachristie$ k apply -f https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/manifests/0.15.1/0000_50_olm_00-clusterserviceversions.crd.yaml

```

**Environment**
* operator-lifecycle-manager version:

0.15.1

* Kubernetes version information:
kubectl client versions tested
1.16.3 and 1.18.3

* Kubernetes cluster kind: 
IKS 1.16, 1.17, 1.18
ROKS 4.3

**Possible Solution**

**Additional context**
I think this may be a kubectl bug.

**Comment by benluddy** [comment]
Thanks for filing an issue.

This is a performance bug in a kubectl dependency (see https://github.com/operator-framework/operator-lifecycle-manager/issues/1534#issuecomment-632342257). Several of the OLM CRD manifests are quite large owing to their schemas, which runs into a pathological performance issue with JSON patch generation.

**Comment by kramvan1** [comment]
@benluddy Any known workarounds for this?    Is there some safe way to reduce the size of the CRD?  Take out descriptions or other info that is really not technically needed?

It appears this is still not fixed in kube 1.18, so many folks will start to run into this.

**Comment by benluddy** [comment]
I don't think that reducing the size of the serialized manifest without reducing the depth of nested maps within the manifest addresses the particular issue, but there seems to be good progress on a fix in https://github.com/kubernetes/kubernetes/pull/91622.

**Comment by benluddy** [comment]
Any suggestions would definitely be appreciated! To support new users, adding guardrails in the installation script could be an easy win. I'm just not sure that there is a nondisruptive change to the CRDs that would mitigate this bug.
