### ISSUE TITLE
Error while mounting a secret as volume in controller deployment causing CSV creation failure.

### ISSUE THREAD

**Issue by prafull01** [operator-framework/operator-lifecycle-manager#1582]
## Bug Report

**What did you do?**
I have created a CSV and in install spec, I was mounting a secret as a volume as follows:
`spec:
                volumes:
                - name: scorecard-kubeconfig
                  secret:
                    secretName: scorecard-kubeconfig
                    items:
                    - key: kubeconfig
                      path: config
                containers:
                  - command:
                      - etcd-operator
                      - '--create-crd=false'
                    volumeMounts:
                    - name: scorecard-kubeconfig
                      mountPath: /scorecard-secret
                    env:
                      - name: MY_POD_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: MY_POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                    image: >-
                      quay.io/coreos/etcd-operator@sha256:66a37fd61a06a43969854ee6d3e21087a98b93838e284a6086b13917f96b0d9b
                    name: etcd-operator
                    resources: {}
`
This is causing the following error:
`kubectl create -f /home/test/clusterserviceversion-etcdoperator.v0.9.4.yaml
The ClusterServiceVersion "etcdoperator.v0.9.4" is invalid: type: Required value`

**What did you expect to see?**
The CSV should be able to create successfully. I have used the same CSV on the openshift where OLM version is older, the same CSV works fine.

**What did you see instead? Under which circumstances?**
This is causing the following error:
`kubectl create -f /home/test/clusterserviceversion-etcdoperator.v0.9.4.yaml
The ClusterServiceVersion "etcdoperator.v0.9.4" is invalid: type: Required value`

**Environment**
* operator-lifecycle-manager version: 0.15.1 and 0.14.1 

* Kubernetes version information:

`test@prafull:~/go/src/github.com/trilioData/k8s-triliovault$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-gke.2", GitCommit:"4751ff766b3f6dbf6c6a63394a909e8108e89744", GitTreeState:"clean", BuildDate:"2020-05-08T16:44:50Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
`
* Kubernetes cluster kind: GKE 

**Possible Solution**

**Additional context**
I am attaching both the CSV one which is failing and other one which don't have any issue.
[csv.zip](https://github.com/operator-framework/operator-lifecycle-manager/files/4765053/csv.zip)

**Comment by prafull01** [comment]
The same CSV works fine with OLM version 0.13.0

**Comment by exdx** [comment]
Does it work without mounting the secret? I've seen a similar issue like this and resolved because the `Name` field was required in parts of the CRD -- could potentially be related

**Comment by prafull01** [comment]
Yes it works without mounting the secret. Also I have added the Name: field required in the CSV. The error of missing name field is different, I faced it but I have added name fields to resolve those errors.  The same CSV works with 0.13.0 with secret mounts in the deployment and from 0.14.0 it started throwing the error. 

I have attached the CSV's with secret mount and without secret mount (that is the only difference between those two CSV) in ticket description and one is successful and another one is failing

**Comment by samw08** [comment]
[This comment](https://github.com/kubernetes-sigs/kubefed/issues/469#issuecomment-443370555) states that it's a k8s bug, and one strategy to work around the problem is to add the `type: array` field like this:
```
secret:
  secretName: scorecard-kubeconfig                  
  items:
  - key: kubeconfig
    path: config
  type: array
```
It worked for me.

**Comment by dinhxuanvu** [comment]
The issue is stale. Closed. Please feel free to reopen if needed.
