### ISSUE TITLE
[RFE] - Enhance CSV to support Tags AND Digests

### ISSUE THREAD

**Issue by cdjohnson** [operator-framework/operator-lifecycle-manager#1588]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When attempting to mirror an OLM Operator Catalog via a tool such as `oc adm catalog mirror`, the inventory of all images are stored in the deployment pod as well as the `relatedImages` section of the CSV files.

All images, as seen by a Cluster require Digests to be defined, to take advantage of an ImageContentSourcePolicy registry mirroring policy in OpenShift

When the images are mirrored from the public registry to the air-gapped registry, the images do not have tags, and are therefore created with the "latest" tag which will result in tagless images that are subject to garbage collection.

**Describe the solution you'd like**
One of two options:
1. Explicitly support the `tag@digest` syntax:
   `quay.io/coreos/etcd:v1.2.3@sha256:12345`
or
1.  Enhance the image references as follows, which would require duplicating the deployment image in relatedImages as well:
```
spec:
  relatedImages:
  - name: default
    repo: quay.io/coreos/etcd
    digest: sha256:12345 
    tag: v1.2.3
    annotation: default
    required: true
```

The underlying mirror tool would PULL by digest, and PUSH by tag to the target registry, preserving the digest:
For example:
`skopeo -a copy docker://quay.io/coreos/etcd@sha256:12345 docker://myregistry.local/quay/coreos/etcd:v1.2.3`

@ecordell 
This is related to this enhancement:
https://github.com/operator-framework/enhancements/blob/master/enhancements/opm-mirroring.md

**Comment by ecordell** [comment]
Thanks @cdjohnson - I think that this is already covered by https://github.com/openshift/oc/pull/384 - do you agree?

(In summary - images with digests are given a generated tag during mirror so that they are not GC'd)

**Comment by Jamstah** [comment]
It definitely solves the registry GC problem, but it doesn't solve the discoverability problem for the target registry.

At some point, after mirroring a number of versions of an operator, a user is likely to want to remove old versions from their mirror registry either for security reasons (vulnerable images) or for space reasons. How are they identified?

I saw in the description for the PR:
> Images are given a tag when mirroring if they don't already have one

That implies its already possible to have a tag for an image, just to clarify, is that a tag *instead of* a digest?

**Comment by cdjohnson** [comment]
Bump:  Providing an additional tag his strongly desirable here because it allows the customer or future tooling to identify and clean up unused images.

**Comment by exdx** [comment]
Suggestion: use per-namespace conventions when mirroring. This would not duplicate images.

**Comment by dinhxuanvu** [comment]
The issue is stale. Closed. Please feel free to reopen if needed.
