### ISSUE TITLE
removed packageserver from "installed operators" mistakenly 

### ISSUE THREAD

**Issue by khodayard** [operator-framework/operator-lifecycle-manager#1593]
## Type of question

Fix a problem that I've caused.

## Question

**What did you do?**
Just went to Web Console > Installed Operators and removed a partly installed operator named "packageserver" or something like that and all of its related objects. 
**What did you expect to see?**
I don't know exactly! I though that it's a leftover and just wanted to clear it.

**What did you see instead? Under which circumstances?**

Whole operator hub is gone! It displays: "No OperatorHub Items Found" and this:
[root@okd4-services ~]# oc get co operator-lifecycle-manager-packageserver
NAME                                       VERSION                               AVAILABLE   PROGRESSING   DEGRADED   SINCE
operator-lifecycle-manager-packageserver   4.4.0-0.okd-2020-05-23-055148-beta5   False       False         False      24h

**Environment**
It's an okd 4.4.0-0.okd-2020-05-23-055148-beta5 with old 1.15.0 I guess.
* operator-lifecycle-manager version: 1.15.0

* Kubernetes version information:

[root@okd4-services ~]# oc version
Client Version: 4.4.0-0.okd-2020-05-23-055148-beta5
Server Version: 4.4.0-0.okd-2020-05-23-055148-beta5
Kubernetes Version: v1.17.1
[root@okd4-services ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0-4-g38212b5", GitCommit:"4a4cd75", GitTreeState:"clean", BuildDate:"2020-05-22T03:03:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1", GitCommit:"f63db30", GitTreeState:"clean", BuildDate:"2020-05-22T11:48:28Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
[root@okd4-services ~]#
  

* Kubernetes cluster kind: 

**Additional context**
Is there any way to undo it and get operator hub back?

Thanks

**Comment by timflannagan** [comment]
It looks like this is targeting an OCP installation given the `oc get co ...` output but the CVO should manage that resource for most of the newer OCP versions (until 4.9 where a new controller will manage that). The CVO should recreate any resources in manages, so the PackageServer CSV and ClusterOperator resources should both be recreated despite it's removal from the OCP console.
