### ISSUE TITLE
As the admin, I would like to have a possibility to install operator in the fixed namespace (with the fixed set of labels)

### ISSUE THREAD

**Issue by ibuziuk** [operator-framework/operator-lifecycle-manager#1597]
## Feature Request
Currently, OLM supports two installation modes - all namespaces & a specific namespace:

![image](https://user-images.githubusercontent.com/1461122/85588422-f6076d00-b642-11ea-8271-015244eed196.png)

As the admin, I would like to have a possibility to install operator in the fixed namespace (with the fixed set of labels)

![image](https://user-images.githubusercontent.com/1461122/85588511-0ae40080-b643-11ea-9bf3-b18366812b41.png)

At this point in time in order to achieve this behavior, one should use the 'All namespaces' strategy and handle the installation on the operator end (pre-create namespace and labels) which looks wrong by design. A particular example of the 'fixed namespace' requirement in the real project - https://github.com/eclipse/che/issues/17187

**Comment by dinhxuanvu** [comment]
You can use MultipleNamespace mode. Please take a look at this doc: https://olm.operatorframework.io/docs/concepts/crds/operatorgroup/#target-namespace-selection
