### ISSUE TITLE
InstallPlan cannot resolve a change to immutable field in operator Deployment spec

### ISSUE THREAD

**Issue by aharbis** [operator-framework/operator-lifecycle-manager#1608]
## Bug Report

**What did you do?**

Between two releases of our operator, we modified the `labels` on our operator's Deployment resource.

**What did you expect to see?**

OLM successfully resolve the new InstallPlan and Deployment spec, and perform the update.

**What did you see instead? Under which circumstances?**

OLM failed to perform the update, and the InstallPlan failed with an error such as:

>install strategy failed: Deployment.apps "datapower-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"datapower-operator", "app.kubernetes.io/managed-by":"datapower-operator", "app.kubernetes.io/name":"datapower-operator", "name":"datapower-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

**Environment**
* operator-lifecycle-manager version:

OCP 4.4.3, not sure on specific OLM version.

* Kubernetes version information:

```
$ oc version
Client Version: openshift-clients-4.3.0-201910250623-88-g6a937dfe
Server Version: 4.4.3
Kubernetes Version: v1.17.1
```

* Kubernetes cluster kind:  OCP

**Possible Solution**

If some change is found during the InstallPlan such as this, which causes a diff on an immutable field, the Deployment could be deleted by OLM and recreated to resolve the issue (this is what we had to do manually as a workaround).

**Additional context**

**Comment by aharbis** [comment]
bump

**Comment by prafull01** [comment]
@exdx If no one is working on this, I can pick it up..

**Comment by aharbis** [comment]
@cdjohnson Yes, that's the workaround that we documented in our upgrade docs. I still believe this is something that should be handled by OLM gracefully.
