### ISSUE TITLE
An old version of a dependent package is installed

### ISSUE THREAD

**Issue by nicolaferraro** [operator-framework/operator-lifecycle-manager#1620]
## Bug Report

**What did you do?**

I've tried to install the Knative Camel operator using a custom operatorsource, CSV is like in this PR: https://github.com/operator-framework/community-operators/pull/1933.

It depends on [another CRD](https://github.com/operator-framework/community-operators/pull/1933/files#diff-a3365771500fd67694ce22b8813d908fR61-R66), which is provided by [Camel K](https://github.com/operator-framework/community-operators/blob/master/community-operators/camel-k/1.0.0/integrations.camel.apache.org.crd.yaml).

I set the update to "manual", to see the install plan and I get:

![Screenshot from 2020-07-02 11-38-43](https://user-images.githubusercontent.com/4151857/86343015-ab947a80-bc58-11ea-9ebd-8ec0597aa8b3.png)

The plan wants to install Camel K 1.0.0-RC2. But why not installing latest version, which is 1.0.0?
Camel K 1.0.0 also **replaces** version 1.0.0-RC2, so I see no reasons why it should install 1.0.0-RC2.

I've tried to publish KnativeCamelSources also in a channel named "stable", which is the same channel where Camel K 1.0.0 is published (while Camel K 1.0.0-RC2 is in the "alpha" channel), but nothing changed.

**What did you expect to see?**
If a new version of a dependent package is present, OLM should not install it in place of an older version.

In the case of Camel K, the "Integration" CRD (same group and version) is also offered by two operators: "Apache Camel K" and "Red Hat Integration - Camel K". It would be nice if we had a way to specify which one we prefer.

**What did you see instead? Under which circumstances?**
Already explained above.

**Environment**
* operator-lifecycle-manager version: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:02bd2a1be514a4403a83536c20459d775036900e67dc2c4445d584ea4ca374a7

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1+3f6f40d", GitCommit:"3f6f40d", GitTreeState:"clean", BuildDate:"2020-06-08T07:13:25Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: OpenShift

**Comment by exdx** [comment]
We have recently done a major overhaul of dependency resolution in OLM. It would be helpful if you could replicate this on the latest release as see if the issue persists.

**Comment by nicolaferraro** [comment]
> We have recently done a major overhaul of dependency resolution in OLM. It would be helpful if you could replicate this on the latest release to see if the issue persists.

Tried now on OpenShift 4.5 and I see that latest (1.1.0 currently) is installed. Thanks, closing this.
