### ISSUE TITLE
What is the best way to install Operand CRDs with my Operator in OLM

### ISSUE THREAD

**Issue by Rulox** [operator-framework/operator-lifecycle-manager#1622]
## Support

I'm opening this as requested here https://github.com/operator-framework/operator-sdk/issues/3325 by the operator-sdk team.

## Question
I've tried to look for this but I haven't found any doc/example and no one has been able to answer me on the operator slack channel in k8s or other repositories.

We have a RH Certified operator (https://github.com/nginxinc/nginx-ingress-operator) to install this operand (https://github.com/nginxinc/kubernetes-ingress).

The operand (https://github.com/nginxinc/kubernetes-ingress) has some CRDs:
* VirtualServer https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/common/vs-definition.yaml
* VirtualServerRoute https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/common/vsr-definition.yaml
* GlobalConfiguration https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/common/gc-definition.yaml
* TransportServer https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/common/ts-definition.yaml

These CRDs must be installed in the cluster in order for the operand (Ingress Controller) to work. We did a workaround making the Operator install these from the Go code, but we want to do things right, as we want to deploy the whole manifests of the CRDs to support openapi validation too.

**What's the best way to make OLM install these CRDs too?** I can't make them part of the CSV because the `operator-sdk` tool will complain that the CRDs are not in the operator code. Also this step would be done manually and we're trying to make everything as automated as possible.

Please keep in mind this Operator must continue to be certified by RH, so we can't make any weird workaround in manifests.

**Environment**
operator-sdk version: "v0.15.1", commit: "e35ec7b722ba095e6438f63fafb9e7326870b486", go version: "go1.13.6 darwin/amd64"

crc version: 1.8.0+0a318dc
OpenShift version: 4.3.8 (embedded in binary)

**Comment by exdx** [comment]
So your operator needs to package additional CRDs for the operands to work? It seems like the operand is itself another operator with its own set of CRDs and controllers for ingress. 

This is an interesting case, where an operator is installing another operator. One approach is to bundle the operand into a separate bundle and make it a required API for the original operator. In this case OLM will resolve the operand bundle (installing its controllers and CRDs) before installing the original operator. 

Another approach would be to modify the SDK level validation

**Comment by dinhxuanvu** [comment]
Stale issue. Closed. Feel free to reopen if needed.
