### ISSUE TITLE
Install Quickstart did not work

### ISSUE THREAD

**Issue by mjschmidt** [operator-framework/operator-lifecycle-manager#1633]
## Bug Report

**What did you do?**
Attempted to install OLM via the installation guide on a native kubernetes cluster verison 1.15.12.

**What did you expect to see?**
Custom resources deploy when I ran
```kubectl create -f deploy/upstream/quickstart/crds.yaml```

**What did you see instead? Under which circumstances?**
```
unable to recognize "deploy/upstream/quickstart/crds.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "deploy/upstream/quickstart/crds.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "deploy/upstream/quickstart/crds.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "deploy/upstream/quickstart/crds.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "deploy/upstream/quickstart/crds.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
```

**Environment**
* operator-lifecycle-manager version:

release 4.7
* Kubernetes version information:
kubernetes version 1.15.12

* Kubernetes cluster kind: 
native kubernetes
**Possible Solution**
Not sure what kubernetes version openshift is testing against?

**Additional context**
could be an api version difference? That should probably be noted in the install guide if that is the case?

**Comment by Kampe** [comment]
same here, running k3s 1.18.4

**Comment by exdx** [comment]
Off the top of my head, I believe the v1 APIVersion of CRDs was introduced in kube 1.16? So installing v1 CRDs onto a 1.15 cluster would cause the issue you're seeing. 

We have upgraded the OLM CRDs to v1 since we are always rebasing off upstream kube, but this raises a fair point of how to install/support OLM on pre-1.16 clusters. Ideally we would have some sort of backwards-compatibility here.
