### ISSUE TITLE
Question: Uninstall of dependent operators

### ISSUE THREAD

**Issue by jeyaramashok** [operator-framework/operator-lifecycle-manager#1644]
The [olm-book](https://operator-framework.github.io/olm-book/docs/operator-dependencies-and-requirements.html) mentions about dependency resolution during install time, can you please also describe how uninstall/cleanup works. 

- Does the OLM keep reference counter of dependent operators when its a shared dependency ?
- How to cleanup the dependent operators and when to do this?

**Comment by manjuvee** [comment]
Am also looking for the same information. Please let us know how to uninstall the dependent operators when the operator is uninstalled.

**Comment by dinhxuanvu** [comment]
The main and dependent operators are all independent operators after installation. You can uninstall dependent operators independently by removing their subscriptions and CSVs. However, be careful that it may break the main operator.
