### ISSUE TITLE
Is it possible to run OLM on clusters without OpenShift

### ISSUE THREAD

**Issue by prajnak** [operator-framework/operator-lifecycle-manager#1658]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
General context and the presence of documentation around deploying OLM along with custom built operators (registries, bundles etc)to K8S (or private registries) without OpenShift.

**Comment by awgreene** [comment]
Yes - it is absolutely possible to run OLM on non-OpenShift Clusters by following the [installation steps](https://github.com/operator-framework/operator-lifecycle-manager#installation). The standard installation should include the operators featured in the [upstream-community-operators](https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators).

If you wish to build your own catalog of operators, you will need to review the [operator-registry](https://github.com/operator-framework/operator-registry) repository.

**Comment by awgreene** [comment]
Marking this issue as closed, please reopen if you have any questions or concerns.
