### ISSUE TITLE
Unable to use OLM to create operator in kubernetes native cluster

### ISSUE THREAD

**Issue by nataraj24** [operator-framework/operator-lifecycle-manager#1660]
## Type of question
1. How to use OLM to create operator in native kubernetes cluster? i am run OLM being corporate proxy.  
2. can i deploy operator using olm without publishing operator to operatorhubio?

getting below error when i try to deploy operator-group, subscription, csv
E0721 10:14:34.138232       1 queueinformer_operator.go:290] sync "test" failed: {test-operator alpha  {operatorhubio-catalog olm}} not found: rpc error: code = Unknown desc = no entry found for test-operator alpha

## Question

**What did you do?**
using operator-sdk generated csv for my operator.   

**What did you expect to see?**
should be able to deploy operator

**What did you see instead? Under which circumstances?**
E0721 10:14:34.138232       1 queueinformer_operator.go:290] sync "test" failed: {test-operator alpha  {operatorhubio-catalog olm}} not found: rpc error: code = Unknown desc = no entry found for test-operator alpha

**Environment**
* operator-lifecycle-manager version: 1.15.1

* Kubernetes version information:v1.16.8-eks-e16311

  

* Kubernetes cluster kind: Native Kubernetes cluster

**Additional context**
Add any other context about the question here.
i am able to run the operator without OLM.  trying use OLM to install operator and unable to use it.

**Comment by flickerfly** [comment]
This error is looking in the operatorhubio-catalog's records for an alpha channel of test-operator. It seems like it can't find it. Could you have another catalog? 

`kubectl get packagemanifest` will show you all the packages in your cluster and which catalog they are in. Check that out. Then you can get a specific package manifest to see if you have what you want. 

You can also use grpcurl to query the catalog as long as it is a grpc type catalog. A couple other types exist, but if you are using them you'll know.

**Comment by nataraj24** [comment]
thank you @flickerfly information.

Finally i was able to host private catalog registry with only my operator and i was able use OLM to install the operators
