### ISSUE TITLE
New release 0.16.1 request for kube 1.19 fixes

### ISSUE THREAD

**Issue by kramvan1** [operator-framework/operator-lifecycle-manager#1663]
## Type of question

Release request to help support and test with kube 1.19.  

## Question

Trying to run OLM on kube 1.19, need the https://github.com/operator-framework/operator-lifecycle-manager/pull/1562 and https://github.com/operator-framework/operator-lifecycle-manager/pull/1680 
for that to work well.

**What did you expect to see?**

0.16.1 release

**What did you see instead? Under which circumstances?**

No new release after that kube 1.19 PR was merged.

**Environment**
* Kubernetes version information:

1.19  

* Kubernetes cluster kind: 

**Additional context**

cc @ecordell

**Comment by kramvan1** [comment]
@ecordell Any ideas on new release to pick these up?

**Comment by kramvan1** [comment]
@ecordell @awgreene @njhale Bump on this?

**Comment by exdx** [comment]
We should be cutting a new release shortly. We had cut a 0.16.0 on 1.19 but ran into some issues.

**Comment by kramvan1** [comment]
@exdx Thx for the update.

**Comment by kramvan1** [comment]
Testing on 1.1.9 now...

**Comment by kramvan1** [comment]
Closing, appears to work on 1.19 now.
