### ISSUE TITLE
Issue Installing OLM in Openshift Namespace

### ISSUE THREAD

**Issue by atef23** [operator-framework/operator-lifecycle-manager#1683]
## Bug Report

**What did you do?**
I provisioned an Openshift cloud cluster through Red Hat's openTLC labs system so the cluster came preconfigured with some components I don't have full visibility into. I created a new namespace and attempted to install olm using the operator-sdk CLI.

**What did you expect to see?**
Expected to be able to install OLM if it wasn't there already.

**What did you see instead? Under which circumstances?**
It seems that some components of OLM are present but not enough to allow for an uninstall. Stuck in a catch-22 where I can't install due to these components but also can't run the uninstall command 

`[atefaziz@localhost projects]$ operator-sdk olm status

FATA[0002] Failed to get OLM status: no existing installation found 

[atefaziz@localhost projects]$ operator-sdk olm install

INFO[0002] Fetching CRDs for version "latest"          
 
INFO[0003] Fetching resources for version "latest"   
   
FATA[0005] Failed to install OLM version "latest": detected existing OLM resources: OLM must be completely uninstalled before installation 

[atefaziz@localhost projects]$ operator-sdk olm uninstall

FATA[0002] Failed to uninstall OLM: no existing installation found 
`

**Environment**
* operator-lifecycle-manager version: 

operator-sdk version: "v0.17.0"

* Kubernetes version information:

Openshift version:
4.4.8

**Comment by kevinrizza** [comment]
OpenShift comes with OLM already installed in a privileged namespace. You won't be able to install a second instance of olm (or be able to properly uninstall it) because OLM is considered a core component of openshift (at least, not without disabling other core cluster components that ensure OLM is always available).

That being said, the core OLM apis should already be there and will be handled. Is there a reason you need to run this operation at all? Can't you just use what's already available?

**Comment by atef23** [comment]
@kevinrizza sorry that was my CLI version. The cluster version is 4.4.8. I've updated it above. Hmm yeah I'm going through the source trying to see which existing resources exist which are preventing my installation from proceeding.

**Comment by kevinrizza** [comment]
@atef23 Ah, yeah, so in that case OLM is a core openshift component and the sdk won't be able to uninstall it without first putting the cluster in an unsupportable state. Is there a reason you are attempting to uninstall olm, or attempting to install a different version?

**Comment by atef23** [comment]
@kevinrizza ah ok so I guess the issue was that I was using a OC 3.x CLI with a 4.x cluster so it wasn't able to detect the olm installation? I think you're right the olm installation was already there but when I ran the:

operator-sdk olm status 

command, it said there was no installation

I manually applied the olm.yaml and crds.yaml from the latest release: https://github.com/operator-framework/operator-lifecycle-manager/releases and after doing that, my operator-sdk olm status command was successfully showing the installation:

`[atefaziz@localhost Downloads]$ operator-sdk olm status
INFO[0006] Fetching CRDs for version "0.15.1"           
INFO[0007] Fetching resources for version "0.15.1"      
INFO[0008] Successfully got OLM status for version "0.15.1" 

NAME                                            NAMESPACE    KIND                        STATUS
olm                                                          Namespace                   Installed
subscriptions.operators.coreos.com                           CustomResourceDefinition    Installed
operatorgroups.operators.coreos.com                          CustomResourceDefinition    Installed
installplans.operators.coreos.com                            CustomResourceDefinition    Installed
clusterserviceversions.operators.coreos.com                  CustomResourceDefinition    Installed
aggregate-olm-edit                                           ClusterRole                 Installed
catalog-operator                                olm          Deployment                  Installed
olm-operator                                    olm          Deployment                  Installed
operatorhubio-catalog                           olm          CatalogSource               Installed
olm-operators                                   olm          OperatorGroup               Installed
aggregate-olm-view                                           ClusterRole                 Installed
operators                                                    Namespace                   Installed
global-operators                                operators    OperatorGroup               Installed
olm-operator-serviceaccount                     olm          ServiceAccount              Installed
packageserver                                   olm          ClusterServiceVersion       Installed
system:controller:operator-lifecycle-manager                 ClusterRole                 Installed
catalogsources.operators.coreos.com                          CustomResourceDefinition    Installed
olm-operator-binding-olm                                     ClusterRoleBinding          Installed
`

**Comment by atef23** [comment]
@kevinrizza thanks for your input, I will close the issue

**Comment by atef23** [comment]
### Summary:

Issue:

No installation found error on Openshift 4 cluster which already has OLM installed by default:

```
[atefaziz@localhost Documents]$ operator-sdk olm status
FATA[0002] Failed to get OLM status: no existing installation found 
```

Run crds and resources manually:

`oc apply -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.15.1/crds.yaml
 oc apply -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.15.1/olm.yaml
`
Re-run status check:

```

[atefaziz@localhost Documents]$ operator-sdk olm status
INFO[0002] Fetching CRDs for version "0.15.1"           
INFO[0003] Fetching resources for version "0.15.1"      
INFO[0005] Successfully got OLM status for version "0.15.1" 

NAME                                            NAMESPACE    KIND                        STATUS
olm                                                          Namespace                   Installed
subscriptions.operators.coreos.com                           CustomResourceDefinition    Installed
operatorgroups.operators.coreos.com                          CustomResourceDefinition    Installed
installplans.operators.coreos.com                            CustomResourceDefinition    Installed
clusterserviceversions.operators.coreos.com                  CustomResourceDefinition    Installed
aggregate-olm-edit                                           ClusterRole                 Installed
catalog-operator                                olm          Deployment                  Installed
olm-operator                                    olm          Deployment                  Installed
operatorhubio-catalog                           olm          CatalogSource               Installed
olm-operators                                   olm          OperatorGroup               Installed
aggregate-olm-view                                           ClusterRole                 Installed
operators                                                    Namespace                   Installed
global-operators                                operators    OperatorGroup               Installed
olm-operator-serviceaccount                     olm          ServiceAccount              Installed
packageserver                                   olm          ClusterServiceVersion       Installed
system:controller:operator-lifecycle-manager                 ClusterRole                 Installed
catalogsources.operators.coreos.com                          CustomResourceDefinition    Installed
olm-operator-binding-olm                                     ClusterRoleBinding          Installed
```
