### ISSUE TITLE
Creating many subscriptions may result in `UpgradePending` for some operators

### ISSUE THREAD

**Issue by radtriste** [operator-framework/operator-lifecycle-manager#1704]
## Bug Report

**What did you do?**
In order to test current version of our Kogito [operator](https://github.com/kiegroup/kogito-cloud-operator), we install, via subscription yaml, the different dependent operators if needed for our tests. It can be for example, Infinispan, Stimzi and/or Keycloak operators.
For that, in our namespace,  we first create an OperatorGroup, if not already existing:
```
operatorGroup := &olmapiv1.OperatorGroup{
		ObjectMeta: metav1.ObjectMeta{
			Name:      operatorGroupName,
			Namespace: namespace,
		},
		Spec: olmapiv1.OperatorGroupSpec{
			TargetNamespaces: []string{namespace},
		},
	}
```
and then we create some namespaced subscriptions, for example both
```
subscription := &olmapiv1alpha1.Subscription{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "infinispan",
			Namespace: namespace,
		},
		Spec: &olmapiv1alpha1.SubscriptionSpec{
			Package:                "infinispan",
			CatalogSource:          "community-operators",
			CatalogSourceNamespace: "openshift-marketplace",
			Channel:                "stable",
		},
	}
```
and
```
subscription := &olmapiv1alpha1.Subscription{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "strimzi-kafka-operator",
			Namespace: namespace,
		},
		Spec: &olmapiv1alpha1.SubscriptionSpec{
			Package:                "strimzi-kafka-operator",
			CatalogSource:          "community-operators",
			CatalogSourceNamespace: "openshift-marketplace",
			Channel:                "stable",
		},
	}
```

and then we wait for all operators to be up and running.

**What did you expect to see?**
One installplan with both csv operators in it or 2 installplans, one for each csv operator.

**What did you see instead? Under which circumstances?**
When the cluster is busy, sometimes, only one installplan will be created and only one operator will be in it.
But both subscriptions are linked to that installplan. Which result, for example, in Strimzi (which is the second subscription to be created) blocked in status `UpgradePending` and no further progress ...

**Environment**
* Openshift version: `4.5.4`
* Kubernetes version: `v1.18.3+012b3ec`
* operator-lifecycle-manager version: `olm.deployment-spec-hash%3D77ff497567`

**Workaround**
For now, as a workaround, we install each operator, one after the other, waiting for the previous one to be up.

**Additional context**
Sometimes, also, it creates one installplan with both csv and sometimes 2 installplan, this seems to be totally random ...

**Comment by dinhxuanvu** [comment]
Please use newer version of OLM (OCP 4.6+) because the new resolver may resolve this issue.
Stale issue. Closed. Feel free to reopen if needed.
