### ISSUE TITLE
Support CRD v1beta1 APIs while major k8s distros continue to support them

### ISSUE THREAD

**Issue by ron1** [operator-framework/operator-lifecycle-manager#1726]
## Feature Request
Major k8s vendors continue to support pre-1.16 k8s versions which include the CRD v1beta APIs. Consider waiting to move exclusively to the CRD v1 APIs until pre-1.16 k8s versions are no longer supported by major vendors. Specifically, enhance OLM 0.15.0+ releases to make them work on pre-1.16 k8s versions.

**Comment by exdx** [comment]
This is a good point, and brought up recently in #1633. We will consider trying to add support for OLM in pre-1.16 clusters.

**Comment by dinhxuanvu** [comment]
Stale issue. Closed. Feel free to reopen if needed.
