### ISSUE TITLE
Outdated operators on OperatorHub

### ISSUE THREAD

**Issue by immanuelfodor** [operator-framework/operator-lifecycle-manager#1742]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

General context and help, community best bractices

## Question

**What did you do?**
I installed OLM and tried to install the [Minio](https://operatorhub.io/operator/minio-operator) and [Postgres](https://operatorhub.io/operator/postgres-operator) operators.

**What did you expect to see?**
I expected to see the latest available release installed of the above operators.

**What did you see instead? Under which circumstances?**
I got seriously outdated operators, so I ended up removing them - then finally removing OLM as well as I have no use case besides these operators 😢 

Postgres:
- All releases: https://github.com/zalando/postgres-operator/releases
- Source latest: **1.5.0** (May 5, 2020)
- OLM latest: **1.3.0** (Dec 17, 2019)

Minio:
- All releases: https://github.com/minio/operator/releases
- Source latest: **3.0.13** (Aug 14, 2020)
- OLM latest: **1.0.3** (Sep 17, 2019) ☠️

**Environment**
* operator-lifecycle-manager version: v0.15.1
* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```  
* Kubernetes cluster kind: RKE

**Additional context**
OLM is a great tool but packages should be maintained. I could open two tickets for these operators for an OLM package update but I suppose this is a more general issue that needs to be solved on the OLM-side. Maybe enforce at least monthly updates to keep the packages from being labeled as outdated in the OperatorHub?

**Comment by immanuelfodor** [comment]
Unstale

**Comment by immanuelfodor** [comment]
Unstale

**Comment by ecordell** [comment]
If this is a concern, please address in operator-framework/community-operators. The OLM maintainers do not maintain the community catalogs. Thanks!
