### ISSUE TITLE
OLM dashboard show operator version from all channels

### ISSUE THREAD

**Issue by NissesSenap** [operator-framework/operator-lifecycle-manager#1744]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I would like to see which versions is available on all the channels when I'm choosing to install a operator.

**Describe the solution you'd like**
Ether show the different operator versions available when first clicking the operator.
![image](https://user-images.githubusercontent.com/14774899/91697284-243c8800-eb71-11ea-99a0-e3ec8617e8bc.png)

Or show which version you get when picking which channel.
![image](https://user-images.githubusercontent.com/14774899/91697348-41715680-eb71-11ea-807d-f93d91f7d456.png)

**Comment by NissesSenap** [comment]
Thanks for the pointer @exdx , created one now.

**Comment by ecordell** [comment]
That information is currently available in the API, it's just not visible in the console. Closing this in favor of the console issue.
