### ISSUE TITLE
Latest version of OLM failed to install Keycloak-Operator.

### ISSUE THREAD

**Issue by JiyeYu** [operator-framework/operator-lifecycle-manager#1768]
## Bug Report

**What did you do?**

I was using OLM to install Keycloak-Operator and Etcd-Operator according to commands on OperatorHub pages.
However, I failed to install keycloak-operator while the etcd-operator successfully installed.

**What did you expect to see?**
Both Keycloak-operator and etcd-operator should get installed.

**What did you see instead? Under which circumstances?**
Keycloak-operator failed to get installed.

**Environment**
OLM v0.16.1

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

K8s built by Kubespray with 1 master and 2 nodes

**Possible Solution**

I tried to use OLM v0.15.1 to install keycloak-operator, and it succeeded.
I think there is something incompatible between keycloak-operator and olm v0.16.1

Cheers,
Jiye Yu

**Comment by benluddy** [comment]
Hi @JiyeYu, thank you for reporting this issue. The problem that you experienced is the result of a bug that is fixed (https://github.com/operator-framework/operator-lifecycle-manager/pull/1735) as of v0.17.0. The keycloak-operator was affected by the bug because it uses skips to define the upgrade graph of its "alpha" channel, and etcd doesn't.

**Comment by JiyeYu** [comment]
Hi, @benluddy 
Thank you for the update
