### ISSUE TITLE
[RFE] Provide procedure for hot-fixing an operator

### ISSUE THREAD

**Issue by cdjohnson** [operator-framework/operator-lifecycle-manager#1774]
## Feature Request
Give support a way to patch an operator for individual customers without requiring a new version of the operator.

**Is your feature request related to a problem? Please describe.**
Many times, customers will run into a problem with the operator or operand and support must enable diagnostic patches, or provide replacement images or pod specifications.  There is no clear path to support this today other than to publish a new Catalog Index Image with a new Bundle version, which is very expensive and time consuming to deploy.  It is also visible to all customers.

**Describe the solution you'd like**
A simple approach is to allow the customer to patch a deployed CSV file.

This means that OLM needs to know that it can't reconcile the CSV.

To patch:
1.  Modify the subscription to Manual install mode.
2.  Modify the CSV (pod spec, related images, etc) per the support team's instructions
3.  Add metadata to the CSV such that the customer remembers that the CSV has been patched.

To move to the official fix:
1.  Approve a new install plan, which rebuilds the CSV from the Catalog, overlaying the changes.

**Out of scope:**
1.  Provide a generalized template option to continually patch/merge changes into the CSV during upgrades.

**Comment by ecordell** [comment]
Have you run into issues modifying a CSV directly? Any changes made there should be synced to the deployment correctly. I believe the workflow you're looking for is already supported, but I'd like to hear if there's something you've tried that didn't work.

**Comment by cdjohnson** [comment]
We think that this works today.  We just want "official" support for this.  The concern is that we're using an undocumented side effect of OLM's lack of a reconciler.

**Comment by kevinrizza** [comment]
Result of this issue being resolved is documentation and a test describing current behavior. For the future, we should create a new issue (as an RFE) that removes this as the default behavior.

**Comment by jeyaramashok** [comment]
I have created a PR https://github.com/operator-framework/operator-lifecycle-manager/pull/1817  to add an e2e test case , which covers the hotfix scenario described in this issue

**Comment by cdjohnson** [comment]
@jeyaramashok Can we also update the OLM Documentation?

For example:  Add a new topic after this one:

https://olm.operatorframework.io/docs/tasks/install-operator-with-olm/

Called:  Patching an Operator
