### ISSUE TITLE
Add support for installing dependencies in separate namespaces

### ISSUE THREAD

**Issue by abkieling** [operator-framework/operator-lifecycle-manager#1777]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, dependencies are installed in the same namespace. When in Own Namespace mode, the dependencies' operands can only be installed in the same namespace, making it difficult to manage so many unrelated resources.

**Describe the solution you'd like**
I think the best solution for the problem would be installing each dependency in a separate namespace. The dependency definition could have an optional property for the namespace where it should be installed.

**Comment by exdx** [comment]
This seems like a good feature request- right now dependency resolution only considers the subscription namespace (and the global catalogs) and installs into that one namespace. To implement installing dependencies in separate namespaces would require resolution to understand operator groups and install modes, basically a much more sophisticated form of the resolver (which was itself recently overhauled and improved). 

This also leads into questions about the new multitenancy model that OLM is working on. For example, if tenants are on the same cluster and each is using the cluster-wide OLM, one users dependencies should potentially not know about the other. Still some design work being done there. 

@benluddy @ecordell

**Comment by astoycos** [comment]
Hrm any chance we could consider re-opening this?
