### ISSUE TITLE
[RFE] Installed Operators can expose a communication channel with OLM for update readiness

### ISSUE THREAD

**Issue by awgreene** [operator-framework/operator-lifecycle-manager#1783]
## Feature Request

**Is your feature request related to a problem? Please describe.**
OLM currently infers the state of an operator by inspecting the Kubernetes resources that define the operator. OLM does not provide operators with the means to communicate complex states.

Operators managed by OLM would benefit from the ability to communicate their state directly to OLM through a supported channel. Operators could communicate complex conditions and influence how OLM manages the operator, dramatically improving user experience.

A core requirement of this enhancement is to provide operators with the ability to communicate "Upgrade Readiness", providing operators with the ability to signal to OLM that they should not be upgraded at this time. Consider the following scenario based on OLM today:

An operator installed with automatic updates is executing a critical process that could place the cluster in a bad state if OLM upgrades the operator. While this critical process is running, a new version of the operator becomes available. Since the operator was installed with automatic updates, OLM upgrades the operator without allowing the critical process to finish and places the cluster in an unrecoverable state.

OLM could handle the scenario described above had the operator had the ability to communicate that it should not be upgraded as it ran the critical process.

**Describe the solution you'd like**
The desired solution can be seen [here](https://github.com/operator-framework/enhancements/blob/master/enhancements/operator-conditions.md)

**Comment by kevinrizza** [comment]
Completed.

**Comment by awgreene** [comment]
**Docs:** 
https://olm.operatorframework.io/docs/advanced-tasks/communicating-operator-conditions-to-olm/

**Enhancements:**
https://github.com/operator-framework/enhancements/blob/master/enhancements/operator-conditions.md
https://github.com/operator-framework/enhancements/blob/master/enhancements/operator-conditions-lib.md
