### ISSUE TITLE
[RFE] Separate OLM's Upstream and Downstream Repositories

### ISSUE THREAD

**Issue by awgreene** [operator-framework/operator-lifecycle-manager#1784]
## Feature Request

**Is your feature request related to a problem? Please describe.**
OLM was originally developed by Red Hat prior to being donated to CNCF. At this time, Red Hat still uses this GitHub Repository to build their release, which occasionally creates artificial wait time for bug fixes due to their release strategy.

**Describe the solution you'd like**
Separate the upstream and downstream repositories.

**Comment by timflannagan** [comment]
@awgreene Should we close this out? This has largely been addressed, but older (yet still supported) releases still house downstream builds.

**Comment by awgreene** [comment]
The OpenShift CI has been moved out of this repositories CI process, allowing upstream contributors much more control over the introduction of new features. I am going to mark this issue as closed(completed) and any additional work can be tracked as new issues.
