### ISSUE TITLE
[RFE] OLM deletes Operands upon Operator removal

### ISSUE THREAD

**Issue by awgreene** [operator-framework/operator-lifecycle-manager#1787]
## Feature Request

**Is your feature request related to a problem? Please describe.**
As a cluster-admin I can instruct OLM that I want to remove all Operands before removing the Operator, so that I don't end up with orphaned workloads.

**Why is this important:** 
Orphaned workloads are hard to clean up. After the Operator has been removed deleting the custom resource does not clean up secondary resources. It can be hard to find these resources as there is no obligation to put owner references or labels to them. It is probably impossible to find when those resources are outside of the cluster.

**Describe the solution you'd like**
- Operands are not automatically removed
- CRDs are not automatically removed
- Upon Operator uninstall a cluster-admin can opt-in to the clean up behavior
- Clean includes Operands (Custom Resource instances) and Custom Resource Definitions
- ~The Operand removal should have timeout~
- ~Hitting the Operand removal timeout should NOT fail Operator removal~
- ~Hitting the timeout should create an alert event~

**Comment by hasbro17** [comment]
Proposal:  https://github.com/operator-framework/enhancements/pull/46

**Comment by awgreene** [comment]
The team has come to the conclusion that this feature cannot be completed safely within OLM. The client should be able to understand that the CRs have been deleted before removing the CRDs.

We have [introduced](https://github.com/operator-framework/kubectl-operator/pull/45) the ability to control how an operator is uninstalled via the `kubectl operator` binary, which will become available in the upcoming v0.4.0 release.
