### ISSUE TITLE
[RFE] Make it easier to discover older versions of Operators in a CatalogSource

### ISSUE THREAD

**Issue by awgreene** [operator-framework/operator-lifecycle-manager#1788]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Today it's not possible to install an older version of an Operator unless the user exactly knows the CSV semantic version. Furthermore, no tooling exists that helps users  understand the contents of `CatalogSources` on cluster.

**Why is this important:**
There are many reasons why a user may not want to choose not to install the latest version of an operator - whether it's lack of testing or known problems. It should be easy for a user to discovers what versions of an Operator OLM has in its catalogs and update graphs and expose this information in a consumable way to the user.

**Why is this important to happen on the cluster:**
On-cluster catalog inspection can help an admin check:
- If a catalog with known content works correctly on the cluster.
- If certain versions of an Operator have been deprecated.
- If newer z-streams versions of a desired minor versions are available. 
- If a certain version got removed. 

**Describe the solution you'd like**

- A user can see list of available versions of an Operator in a channel on the cluster
- A user can see a list of available channels of an Operator on the cluster
- A user can see all available Operators in a particular catalog on the cluster

**Comment by codihuston** [comment]
Just wanted to bump this... for all of the reasons OP listed.
