### ISSUE TITLE
Add support for installing dependencies using different installModes

### ISSUE THREAD

**Issue by abkieling** [operator-framework/operator-lifecycle-manager#1790]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Main operator supports OwnNamespace, SingleNamespace, and AllNamespaces installMode.
It uses the spec.customresourcedefinitions.required section of the CSV file to define dependencies on other operators and not all of them support the AllNamespaces installMode.
When the operator is installed in AllNamespaces installMode, OLM tries to install the dependencies using the same installMode and the ones that don't support that installMode fail to install.

**Describe the solution you'd like**
I think OLM could provide additional features to cater for the described scenario. OLM could check the supported installModes of each dependency and pick a different one when the installMode selected for the main operator isn't supported by the dependency. Another option would be adding a new 'installMode' property in the dependencies definition. Note that OwnNamespace and SingleNamespace installModes would require the creation of a namespace. That's a feature already requested in issue https://github.com/operator-framework/operator-lifecycle-manager/issues/1777.

**Result of problem described above**
![console-openshift-console apps-crc testing_k8s_ns_openshift-operators_operators coreos com_v1alpha1_ClusterServiceVersion](https://user-images.githubusercontent.com/1910095/94822324-e4b7c480-03d8-11eb-8e6f-fcb943ac8820.png)

**Comment by awgreene** [comment]
OLM is planning to move towards cluster singleton operators, some notes on this topic can be found [here](https://hackmd.io/rfxVB8uXRcmH8qXBm4GoNw). If you are interested in engaging in this conversation please attend the upstream OLM Development Working Group meetings.
