### ISSUE TITLE
OLM doesn't revert modified deployment of operator

### ISSUE THREAD

**Issue by zkyle95** [operator-framework/operator-lifecycle-manager#1853]
## Bug Report

**What did you do?**

1. Subscribe an operator on operatorhub console

2. Scale down operator deployment

**What did you expect to see?**

Deployment be scaled up or rolled back soon.

**What did you see instead? Under which circumstances?**

The replicas of deployment keep 0 and CSV phase remains succeed

**Environment**
* operator-lifecycle-manager version:

  0e65642458a1e44e77bd5509dceee3a41da35b76

* Kubernetes version information:

  v1.19.1

* Kubernetes cluster kind: 

  Kubernetes created with kind

**Possible Solution**

**Additional context**

  Remove the deployment and it will be rebuild soon.

**Comment by zkyle95** [comment]
I found that OLM compares the hash set in label of existing deployment with calculated from `CSV.spec.install.spec.deployments`, but both of these hash values won't be updated when deployment is modified directly, which made them equled always.

https://github.com/operator-framework/operator-lifecycle-manager/blob/0e65642458a1e44e77bd5509dceee3a41da35b76/pkg/controller/install/deployment.go#L281

I'd like to solve this bug if my analysis is right 😃

**Comment by awgreene** [comment]
Thank you for submitting this bug @zkyle95 - after reading your most recent comment, I believe that OLM is working as intended.

OLM uses the deploymentHash to ensure that the resources created by OLM match those defined in the CSV. This approach allows a user to edit the resources once they are installed and prevents OLM from entering an endless loop when a webhook is changing the resource before it is saved to the object store.

I am planning to close this issue as things are working as intended.
