### ISSUE TITLE
do we support multi version of InstallPlan exists?

### ISSUE THREAD

**Issue by hchenxa** [operator-framework/operator-lifecycle-manager#1871]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

**What did you do?**

I have an operator installed and set the approve method as manually.

Then I have a new version of catalogsource image updated, it will trigged to create an installPlan with the new changes in.
But I found the the catalogsource image was not valid, and then I fix the problem and have an other version of catalogsource image updated, But it will not create a new InstallPlan with the new changes in since the old of installPlan was still exists.

So 1), Do I need to delete the old installPlan before apply the new catalogsource image? 2), why there can not have multi installPlan preexists and let approval to select which version should be approved?

**What did you expect to see?**

I just want to have a latest version of my operators bumped with the new change and have a installPlan to apply the changes to my operators. 

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

see above.

**Environment**
* operator-lifecycle-manager version:
ocp 4.6.1

* Kubernetes version information:

  

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by hchenxa** [comment]
@dinhxuanvu any comments here?

**Comment by dinhxuanvu** [comment]
Hey @hchenxa, at the moment, multiple versions of pending InstallPlans are not supported. Every time OLM resolves an operator installation/upgrade, it will have to take into account all of dependencies/requirements from other operators in the same namespace, the final resolution is one and only solution at that time which leads to a single InstallPlan that you see. You either accept that solution or decline it given if OLM to resolve happen again, the resolution may be different.
However, having said that, there is a recent change that allows OLM to re-resolve the operator again if you delete the pending InstallPlan (in Manual Approve mode). So if you don't like the current resolution, delete the pending InstallPlan and OLM will resolve again with the new information (if there is). Here is the original [PR](https://github.com/operator-framework/operator-lifecycle-manager/pull/1843).
Please keep in mind, OLM will follow the strict upgrade path that has been established in CatalogSource. So you may not be able to randomly skip to the version that you desire without it being allowable in the upgrade graph.
