### ISSUE TITLE
The installPlanApproval attribute of Subscription does not work

### ISSUE THREAD

**Issue by lanzhiwang** [operator-framework/operator-lifecycle-manager#1895]
## Bug Report

**What did you do?**
I installed OLM 0.16.0 in minikube, and then deployed OperatorGroup and Subscription. The yaml is as follows:

```yaml
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: kafka-group
  namespace: kafka
spec:
  targetNamespaces:
  - kafka

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-strimzi-kafka-operator
  namespace: kafka
spec:
  channel: stable
  name: strimzi-kafka-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  startingCSV: strimzi-cluster-operator.v0.18.0
  installPlanApproval: Manual

```

In Subscription, I set to manually update `installPlanApproval: Manual` and the installed version `startingCSV: strimzi-cluster-operator.v0.18.0`, but OLM will still install the newer version.

```bash
$ kubectl -n kafka get csv strimzi-cluster-operator.v0.19.0
NAME                               DISPLAY   VERSION   REPLACES                           PHASE
strimzi-cluster-operator.v0.19.0   Strimzi   0.19.0    strimzi-cluster-operator.v0.18.0   Succeeded
```

**What did you expect to see?**
I want to see OLM install strimzi-cluster-operator.v0.18.0

**What did you see instead? Under which circumstances?**
OLM install strimzi-cluster-operator.v0.19.0

**Environment**
* operator-lifecycle-manager version: 0.16.0
```bash
$ curl -L https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.16.1/install.sh -o install.sh

$ chmod +x install.sh

$ ./install.sh 0.16.1
```

* Kubernetes version information: v1.19.2

* Kubernetes cluster kind: minikube

```bash
$ minikube version
minikube version: v1.14.2
commit: 2c82918e2347188e21c4e44c8056fc80408bce10
$
```

**Possible Solution**

**Additional context**

**Comment by benluddy** [comment]
Thanks for taking the time to report your issue. I tried and failed to reproduce this myself.

If you can reproduce this again and share the complete manifests of all Subscriptions, InstallPlans, and ClusterServiceVersions in the kafka namespace, that may be sufficient to understand what has happened on your cluster.

**Comment by lanzhiwang** [comment]
I I carefully looked at the document and observed the entire deployment process. I found that it was a problem with my operation. I approved the installation of the new version. This is not a bug. Sorry, you can close this issue.

**Comment by lanzhiwang** [comment]
```bash
$ kubectl -n kafka get ip
NAME            CSV                                APPROVAL   APPROVED
install-7224r   strimzi-cluster-operator.v0.18.0   Manual     true
install-9jxjm   strimzi-cluster-operator.v0.19.0   Manual     false

```
