### ISSUE TITLE
README shows outdated

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lifecycle-manager#1914]
## Docs

**What did you do?**
I am looking for the info in the readme

**What did you expect to see?**
Link for documents that can help me getting started and know more about OLM closer as it was done for [SDK](https://github.com/operator-framework/operator-sdk). 

- Should not the README uses the link https://olm.operatorframework.io/ in the README such as it is done for SDK. See: https://github.com/operator-framework/operator-sdk
- Could we not move the docs from the README to https://olm.operatorframework.io/ and keep it simple as it was done for [SDK](https://github.com/operator-framework/operator-sdk)? 

**What did you see instead? Under which circumstances?**
Link for a very outdated and deprecated/archive repo: https://github.com/operator-framework/getting-started and the doc info in the README and then, I could not find a link for  https://olm.operatorframework.io/.

**Comment by timflannagan** [comment]
Looks like this has already been fixed in the linked PR but automation didn't close it out? Going to close this out in the meantime but feel free to reopen if there's something else this issue was supposed to be tracking.
