### ISSUE TITLE
Oudated info in Packaging an operator for OLM

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lifecycle-manager#1920]
## Bug Report

**What did you do?**
I was checking the doc https://olm.operatorframework.io/docs/tasks/packaging-an-operator/

**What did you expect to see?**
- It links as an example of the Memcached sample with the layout 1.0+ of SDK in : https://github.com/operator-framework/operator-sdk/tree/master/testdata/go/v3/memcached-operator/config
- The description point out the files in the config/ dir instead of the legacy deploy/ one. 

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Comment by timflannagan** [comment]
@camilamacedo86 Thanks for the report - It looks like the doc link you provided no longer exists, so I'm going to close this out. If we're still referencing out-of-date memcached samples, let's re-visit this by opening an issue in the olm-docs repository so we have a centralized place that tracks all the upstream OLM documentation.
