### ISSUE TITLE
The ` advanced operator configuration` in Packaging an operator for OLM is broken

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lifecycle-manager#1922]
## Bug Report

**What did you do?**
Click on in the link  `advanced operator configuration` in https://olm.operatorframework.io/docs/tasks/packaging-an-operator/:

<img width="709" alt="Screen Shot 2020-12-23 at 11 46 56" src="https://user-images.githubusercontent.com/7708031/102993176-9700b300-4514-11eb-9294-80dd9ecaa1fa.png">

**What did you expect to see?**
Check the advanced options

**What did you see instead? Under which circumstances?**
Came back for the same page(on top)

**Comment by timflannagan** [comment]
Closing this out as the o-f/olm-docs repository now houses OLM documentation. This link no longer resolves to the task directory -- it looks like an advanced documentation now lives in the advanced-tasks directory.
