### ISSUE TITLE
The link ` document on install modes ` is broken 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lifecycle-manager#1923]
## Bug Report

**What did you do?**
Click on `Please see the document on install modes and OperatorGroups for more information.` in https://olm.operatorframework.io/docs/tasks/packaging-an-operator/: 

<img width="651" alt="Screen Shot 2020-12-23 at 11 49 28" src="https://user-images.githubusercontent.com/7708031/102993355-f1017880-4514-11eb-9ec3-3d92a6a92d4c.png">

**What did you expect to see?**
The link works and redirects me to the doc

**What did you see instead? Under which circumstances?**
Go to the same page on the top

**Comment by timflannagan** [comment]
Closing this out as (almost all) documentation is now housed on the o-f/olm-docs repository. It looks like this has since been removed/reworded/etc. and the link to a similar sentence now resolves to the correct link.
