### ISSUE TITLE
Error:: no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1" with suit_test.go

### ISSUE THREAD

**Issue by sagar-lonkar** [operator-framework/operator-lifecycle-manager#1954]
**What did you do?**
I have written test case by referring
https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html

**What did you expect to see?**
I run command from controller folder
ginkgo -r -v ./...
It should run basic test 
Ran 1 of 1 Specs in 5.582 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 11.747769669s
Test Suite Passed

**What did you see instead? Under which circumstances?**
But I am getting error ,

Running Suite: Controller Suite
===============================
Random Seed: 1610544295
Will run 1 of 1 specs

STEP: bootstrapping test environment
2021-01-13T18:55:01.596+0530    DEBUG   controller-runtime.test-env     starting control plane  {"api server flags": []}
2021-01-13T18:55:10.656+0530    DEBUG   controller-runtime.test-env     installing CRDs
2021-01-13T18:55:10.667+0530    DEBUG   controller-runtime.test-env     reading CRDs from path  {"path": "../config/crd/bases"}
2021-01-13T18:55:10.697+0530    DEBUG   controller-runtime.test-env     read CRDs from file     {"file": "xyz.yaml"}
2021-01-13T18:55:10.732+0530    DEBUG   controller-runtime.test-env     installing CRD  {"crd": "xyz"}
Failure [9.145 seconds]
[BeforeSuite] BeforeSuite
 /mnt/d/operator-go/controllers/suite_test.go:54

  Unexpected error:
      <*meta.NoKindMatchError | 0xc00035bc80>: {
          GroupKind: {
              Group: "apiextensions.k8s.io",
              Kind: "CustomResourceDefinition",
          },
          SearchedVersions: ["v1"],
      }
      no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
  occurred

  /mnt/d/operator-go/controllers/suite_test.go:64
------------------------------
STEP: tearing down the test environment

Ran 1 of 0 Specs in 9.276 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestAPIs (9.28s)
FAIL

Ginkgo ran 1 suite in 15.3886648s
Test Suite Failed

**Environment**
* operator-lifecycle-manager version:

 operator-sdk version
operator-sdk version: "v1.2.0-33-g71c40198", commit: "71c401987278f0ce209e2adf5d4152d3c045af1e", kubernetes version: "v1.19.4", go version: "go1.15.6", GOOS: "linux", GOARCH: "amd64"

* Kubernetes version information:
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

**Comment by ankitathomas** [comment]
Hi @sagar-lonkar ,

It looks like kubebuilder isn't adding the required scheme from k8s.io/apiextensions-apiserver.
You'd need to add to the scheme used in the test from k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/install.

**Comment by sagar-lonkar** [comment]
How to do that ?

**Comment by subodh-dharma** [comment]
@ankitathomas -- any inputs on this? I am also facing a similar issue

**Comment by timflannagan** [comment]
I'm also under the impression that this is more of a controller runtime issue. Trying upgrading the controller runtime version, or explicitly adding those APIs to a scheme:

```go
import (
         k8s.io/apiextensions-apiserver/pkg/apis/apiextensions
         ...
)
...
func main() {
        ...
	scheme := runtime.NewScheme()
	if err := apiextensions.AddToScheme(scheme); err != nil {
		return nil, err
	}
```

In either case, feel free to re-open if that solution doesn't work but it's not immediately clear to me that's this is an OLM issue.
