### ISSUE TITLE
"Form View" UI in OLM supports multiple Tab

### ISSUE THREAD

**Issue by wondersong** [operator-framework/operator-lifecycle-manager#1959]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: "I have an issue when (...)"
```
When we deploy our operator in OLM, but we have so many required input values result that all was chaos and confusion.
Although all values could be classified by different sections, but all on one page, it is not very friendly from the perspective of UX.
```
**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.
```
If OLM "Form View" UI supports Tab like tab in Web browser, we could allocate those similar kinds of CR values order by same components or feature in one Tab. It will make it more clear.
```

**Comment by ecordell** [comment]
OLM supports UI via the opaque spec descriptors - please open an issue in openshift/console about what values are allowed and how they may configure display in the console UI.

**Comment by wondersong** [comment]
> descriptors

Thank you.
