### ISSUE TITLE
Offline Installation of OLM

### ISSUE THREAD

**Issue by lengrongfu** [operator-framework/operator-lifecycle-manager#1964]
OLM how to Offline Installation?

**Comment by exdx** [comment]
Hi @lengrongfu, could you be more specific? Are you referring to a disconnected cluster? 

There are some [pretty extensive docs ](https://docs.openshift.com/container-platform/4.6/operators/admin/olm-restricted-networks.html) around using OLM in a disconnected environment, but this is openshift specific so it assumes that OLM is already present on cluster (it is packaged with the default openshift payload). 

Installing OLM on a standard kubernetes cluster, assuming the [latest v0.17 release](https://github.com/operator-framework/operator-lifecycle-manager/releases/tag/v0.17.0) would be fairly straightforward via the `install.sh` script. Just make sure that all the image references in the `olm.yaml` file are in the mirrored registry and then run the install script and I believe it should work. The images are as follows:
```
quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607
quay.io/operatorhubio/catalog:latest
```
