### ISSUE TITLE
Failed to install OLM and get Kubernetes config on Microk8s single node cluster

### ISSUE THREAD

**Issue by RyzeNGrind** [operator-framework/operator-lifecycle-manager#1997]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
Operator-SDK | OLM

## Question
Why am I getting this error when I try to follow documentation instructions to install olm via operator-sdk?
**What did you do?**
`ubuntu@pc00:~/kubernetes/operator/memcached-operator$ operator-sdk olm install`
**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).
```
ubuntu@pc00:~/kubernetes/operator/memcached-operator$ operator-sdk olm install
Succesfully installed olm via operator-sdk
```
**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).
```
ubuntu@pc00:~/kubernetes/operator/memcached-operator$ operator-sdk olm install
FATA[0000] Failed to install OLM version "latest": failed to get Kubernetes config: <nil> 
```

**Environment**
* operator-lifecycle-manager version:

```
ubuntu@pc00:~/kubernetes/operator/memcached-operator$ operator-sdk version
operator-sdk version: "v1.4.0", commit: "67f9c8b888887d18cd38bb6fd85cf3cf5b94fd99", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "arm64"
```
* Kubernetes version information:

```
  ubuntu@pc00:~/kubernetes/operator/memcached-operator$ microk8s.kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.1-34+97978f80232b01", GitCommit:"97978f80232b0141732accadfd29444095bcd54f", GitTreeState:"clean", BuildDate:"2021-01-11T12:20:27Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.1-34+97978f80232b01", GitCommit:"97978f80232b0141732accadfd29444095bcd54f", GitTreeState:"clean", BuildDate:"2021-01-11T12:29:09Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/arm64"}
```

* Kubernetes cluster kind: 
Single node microk8s cluster on Raspberry Pi 4 4GB Ubuntu 20.04LTS ARM64

**Additional context**
Add any other context about the question here.

**Comment by RyzeNGrind** [comment]
Issue no longer seems to exist. Closing.

**Comment by RyzeNGrind** [comment]
Issue no longer seems to exist. Closing.

**Comment by timflannagan** [comment]
>FATA[0000] Failed to install OLM version "latest": failed to get Kubernetes config: <nil> 

@RyzeNGrind Looking at that error message, I would guess that you don't kubeconfig properly configured locally (e.g. `KUBECONFIG` isn't exported in your shell), or there's an issue with how the operator-sdk sets up the restconfig needed to interact with any k8s-related clients. Outside of that failure message, there isn't enough information to debug what happened further, so I'm going to close this out in the meantime. Feel free to re-open if you're able to reproduce this using a newer OLM minor version release.
