### ISSUE TITLE
Fails to display installed OLM on OpenShift4.6

### ISSUE THREAD

**Issue by Hatland87** [operator-framework/operator-lifecycle-manager#2002]
## Bug Report

**What did you do?**
Trying to detect installed OLM
```
$ operator-sdk olm status
FATA[0003] Failed to get OLM status: error getting installed OLM version (set --version to override the default version): no existing installation found
```

When trying to install OLM
```
$ operator-sdk olm install
INFO[0003] Fetching CRDs for version "latest"
INFO[0003] Fetching resources for resolved version "latest"
FATA[0004] Failed to install OLM version "latest": detected existing OLM resources: OLM must be completely uninstalled before installation
```

I can see in the documentation that OLM is installed by default in OpenShift 4.0 and above

**Environment**
* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"6082e941e6d62f3a0c6ca8ba52927100948b1d0d", GitTreeState:"clean", BuildDate:"2020-11-14T01:08:04Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+e49167a", GitCommit:"e49167aad6a08046be6ab21ff13029110c76951d", GitTreeState:"clean", BuildDate:"2021-01-28T07:35:27Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
OpenShift 4.6.16

**Comment by kevinrizza** [comment]
The sdk command that checks if OLM is installed is looking for a vanilla kube installation. On OCP there are some key differences to what and how OLM is installed and I don't believe that the sdk is attempting to check for it. It's also worth mentioning that on OCP there is not a direct relationship between that installed version and a specific upstream release.
