### ISSUE TITLE
olm uninstall failing when passed latest as version however install works with same input

### ISSUE THREAD

**Issue by saurav-k** [operator-framework/operator-lifecycle-manager#2003]
##Uninstall failing 
++++++++++++++++

❯ operator-sdk olm uninstall --version=latest  --verbose
DEBU[0000] Debug logging is set
FATA[0003] Failed to uninstall OLM: mismatched installed version "0.17.0" vs. supplied version "latest"'

install working 
++++++++++++

## Install working 
++++++++++++++++

❯ operator-sdk olm install --version=latest  --verbose
DEBU[0000] Debug logging is set
INFO[0003] Fetching CRDs for version "latest"
INFO[0003] Fetching resources for resolved version "latest"
I0211 20:30:48.738982   96831 request.go:655] Throttling request took 1.047317093s, request: GET:https://10.234.240.134:6443/apis/node.k8s.io/v1beta1?timeout=32s
INFO[0022] Creating CRDs and resources
INFO[0022]   Creating CustomResourceDefinition "catalogsources.operators.coreos.com"
INFO[0023]   Creating CustomResourceDefinition "clusterserviceversions.operators.coreos.com"
INFO[0024]   Creating CustomResourceDefinition "installplans.operators.coreos.com"
INFO[0025]   Creating CustomResourceDefinition "operatorgroups.operators.coreos.com"
INFO[0025]   Creating CustomResourceDefinition "operators.operators.coreos.com"
INFO[0026]   Creating CustomResourceDefinition "subscriptions.operators.coreos.com"
INFO[0026]   Creating Namespace "olm"
INFO[0027]   Creating Namespace "operators"
INFO[0027]   Creating ServiceAccount "olm/olm-operator-serviceaccount"
INFO[0027]   Creating ClusterRole "system:controller:operator-lifecycle-manager"
INFO[0028]   Creating ClusterRoleBinding "olm-operator-binding-olm"
INFO[0028]   Creating Deployment "olm/olm-operator"
INFO[0029]   Creating Deployment "olm/catalog-operator"
INFO[0029]   Creating ClusterRole "aggregate-olm-edit"
INFO[0029]   Creating ClusterRole "aggregate-olm-view"
INFO[0030]   Creating OperatorGroup "operators/global-operators"
INFO[0032]   Creating OperatorGroup "olm/olm-operators"
INFO[0032]   Creating ClusterServiceVersion "olm/packageserver"
INFO[0033]   Creating CatalogSource "olm/operatorhubio-catalog"
INFO[0033] Waiting for deployment/olm-operator rollout to complete
INFO[0033]   Waiting for Deployment "olm/olm-operator" to rollout: 0 of 1 updated replicas are available
INFO[0045]   Deployment "olm/olm-operator" successfully rolled out
INFO[0045] Waiting for deployment/catalog-operator rollout to complete
INFO[0045]   Waiting for Deployment "olm/catalog-operator" to rollout: 0 of 1 updated replicas are available
INFO[0052]   Deployment "olm/catalog-operator" successfully rolled out
INFO[0052] Waiting for deployment/packageserver rollout to complete
INFO[0052]   Waiting for Deployment "olm/packageserver" to rollout: 0 of 2 updated replicas are available
INFO[0058]   Deployment "olm/packageserver" successfully rolled out
INFO[0067] Successfully installed OLM version "latest"

NAME                                            NAMESPACE    KIND                        STATUS
catalogsources.operators.coreos.com                          CustomResourceDefinition    Installed
clusterserviceversions.operators.coreos.com                  CustomResourceDefinition    Installed
installplans.operators.coreos.com                            CustomResourceDefinition    Installed
operatorgroups.operators.coreos.com                          CustomResourceDefinition    Installed
operators.operators.coreos.com                               CustomResourceDefinition    Installed
subscriptions.operators.coreos.com                           CustomResourceDefinition    Installed
olm                                                          Namespace                   Installed
operators                                                    Namespace                   Installed
olm-operator-serviceaccount                     olm          ServiceAccount              Installed
system:controller:operator-lifecycle-manager                 ClusterRole                 Installed
olm-operator-binding-olm                                     ClusterRoleBinding          Installed
olm-operator                                    olm          Deployment                  Installed
catalog-operator                                olm          Deployment                  Installed
aggregate-olm-edit                                           ClusterRole                 Installed
aggregate-olm-view                                           ClusterRole                 Installed
global-operators                                operators    OperatorGroup               Installed
olm-operators                                   olm          OperatorGroup               Installed
packageserver                                   olm          ClusterServiceVersion       Installed
operatorhubio-catalog                           olm          CatalogSource               Installed

**Comment by timflannagan** [comment]
@saurav-k It looks like this is an issue with how operator-sdk handles input to their various CLI commands, and there's nothing that the OLM component can do to fix this issue, so I'm going to close this out. I'd recommend cloning this issue on the https://github.com/operator-framework/operator-sdk/issues and seeing whether they're interested in changing this behavior.
