### ISSUE TITLE
Operator Update failing in new operator-sdk 1.x format

### ISSUE THREAD

**Issue by Kaitou786** [operator-framework/operator-lifecycle-manager#2019]
## Bug Report

**What did you do?**
Hi, we recently updated our operator to follow operator-sdk 1.x, and seems to be working nicely, we already released a version of our operator built with this new format and the upgrade was working seamlessly. Now when we are trying to update our operator with the second release with this 1.x format, we see errors in the installPlans.
```
1 queueinformer_operator.go:290] sync {"update" "openshift-operators/install-qtcfj"} failed: error updating service: kogito-operator-controller-manager-metrics-service: Service "kogito-operator-controller-manager-metrics-service" is invalid: [metadata.resourceVersion: Invalid value: "": must be specified for an update, spec.clusterIP: Invalid value: "": field is immutable]
```
The manager-metrics-service is introduced with 1.x updates and now causing the problem while upgrading the operator.

**What did you expect to see?**
The operator should successfully be updated without any problem

**What did you see instead? Under which circumstances?**
The installPlan failed while updating the metricsService

**Environment**
* operator-lifecycle-manager version: Not sure, version bundled with OCP I guess

* Kubernetes version information: OCP 4.6.15

* Kubernetes cluster kind:  Openshift

**Possible Solution**

**Additional context**

**Comment by benluddy** [comment]
This bug has been fixed. For OpenShift, you'll need to be on at least 4.6.16 (https://bugzilla.redhat.com/show_bug.cgi?id=1920873).

**Comment by benluddy** [comment]
https://github.com/operator-framework/operator-lifecycle-manager/pull/1884

**Comment by zach-source** [comment]
@benluddy I'm seeing this same failure on 4.5. Is there a patch fix planned for this on that release?
