### ISSUE TITLE
Service account is not owned by this ClusterServiceVersion

### ISSUE THREAD

**Issue by davidkarlsen** [operator-framework/operator-lifecycle-manager#2028]
## Bug Report

**What did you do?**

Upgrade namespace-configuration operator by using the operator ui: https://github.com/redhat-cop/namespace-configuration-operator/issues/92
The install is actually OK, but halts with a bad status. Then you see:

```
Kind:     ServiceAccount
Message:  Service account is not owned by this ClusterServiceVersion
Name:     default
Status:   PresentNotSatisfied
```

**What did you expect to see?**
Smooth upgrade.

**What did you see instead? Under which circumstances?**
The upgrade "hangs"

**Environment**
* operator-lifecycle-manager version:

openshift 4.6.18

* Kubernetes version information:
1.19

* Kubernetes cluster kind: 
OpenShift

**Possible Solution**
IDK but I see similar issues reported in OCP BZ.

**Additional context**

**Comment by benluddy** [comment]
There should be an InstallPlan in the same namespace that references the stuck ClusterServiceVersion. Can you share its status? It sounds like something may have failed after partially executing that plan.

**Comment by benluddy** [comment]
I didn't take note that this ServiceAccount was named "default". I think this is a bug. Patch here: https://github.com/operator-framework/operator-lifecycle-manager/pull/2029.
