### ISSUE TITLE
Transient apiserver errors can cause CSV to show RequirementsNotMet

### ISSUE THREAD

**Issue by benluddy** [operator-framework/operator-lifecycle-manager#2038]
Errors reaching the discovery API (in `isGVKRegistered`) can cause required/native API requirements to be marked as NotPresent, and the CSV to be marked Pending/RequirementsNotMet. This kind of error should either cause the CSV to be queued for resync or there needs to be support for partial updates to the requirement status list.

**Comment by exdx** [comment]
Related to installplan retries

**Comment by benluddy** [comment]
The specific case of discovery check failures should have been resolved by https://github.com/operator-framework/operator-lifecycle-manager/pull/2024.
