### ISSUE TITLE
Aggregated ClusterRole support in CSV

### ISSUE THREAD

**Issue by muvaf** [operator-framework/operator-lifecycle-manager#2039]
## Feature Request

**Is your feature request related to a problem? Please describe.**

We make use of [aggregated ClusterRoles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles) in our operator's permissions, which means that one `ClusterRole` has `.aggregationRule` field at the top level and don't have any rules in `spec.rules`. Then others specify which `ClusterRole` to be aggregated via `metadata.labels[specific-label]`. This causes two problems when I try to write a CSV:
* The main `ClusterRole` doesn't have any `rules` but that's the one used to bind to operator's `ServiceAccount`. In [`StrategyDeploymentPermissions`](https://github.com/operator-framework/api/blob/1ce77c8/pkg/operators/v1alpha1/clusterserviceversion_types.go#L60) struct, there is no way to specify `aggregationRule`.
* Other `ClusterRole`s do have `spec.rules` but they are not bound to anything; they choose which `ClusterRole` to be aggregated on using `metadata.labels` but [`StrategyDeploymentPermissions`](https://github.com/operator-framework/api/blob/1ce77c8/pkg/operators/v1alpha1/clusterserviceversion_types.go#L60) does not have a way of describing `labels` of the `ClusterRole`

**Describe the solution you'd like**

`StrategyDeploymentPermissions` could have `labels` and `aggregationRules` fields and there could be way to specify `ClusterRole`s that are not bound to any `ServiceAccount`, i.e. used only for aggregation.

**Comment by exdx** [comment]
This seems like a valid feature request and we want to support this functionality with our overhaul of operator permissions and supporting arbitrary objects in the bundle. OLM users will get a more expressive set of permissions for arbitrary objects when some of the newer OLM v2 APIs land. 

As we flesh more of these RBAC issues out we will keep you updated -- we don't have any public facing docs at the moment to share, but once we have something we can share the doc with you for feedback.

**Comment by exdx** [comment]
Closing this issue to track the effort in #2757 .
