### ISSUE TITLE
CI does not work besides the PR has any change that could cause that

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lifecycle-manager#2049]
## Bug Report

the e2e tests fail without any change that could cause that. 
See: https://github.com/operator-framework/operator-lifecycle-manager/pull/2045 or https://github.com/operator-framework/operator-lifecycle-manager/pull/2046

Note that I just change docs which means that the CI could not fail at all with the changes made. 
If my change was in the code then, how would I be able to identify if my changes cause or not an issue?

**What did you do?**
Only change docs 

**What did you expect to see?**

- the tests passing successfully
- the e2e tests not called when it is only doc changes 

**What did you see instead? Under which circumstances?**

Issues faced in the e2e tests which have no relation with the changes made in the PR

**Comment by exdx** [comment]
For tests that tests code, we shouldn't run those if the only change in the PR is against docs. 
We have the `!doc/**` directive in some of the tests suites like https://github.com/operator-framework/operator-lifecycle-manager/blob/cc47b639eea947c27a347b53b0bdc00b4f545aec/.github/workflows/test-scripts.yml#L6 but we should potentially add those to all CI tests in the repo.

Basically, any diff to only `/doc` should come up green in CI 100% of the time until we potentially add linters and other checks for markdown related docs in this repository specifically.

**Comment by timflannagan** [comment]
Closing as this appears to have been fixed in #2299.
