### ISSUE TITLE
localhost:9000 console - "Failed to get user data to handle user setting request"

### ISSUE THREAD

**Issue by holmesb** [operator-framework/operator-lifecycle-manager#2087]
**What did you do?**
We try to launch the console using `make run-console-local`.  After a pause of around 5 mins, we get the 
```
The OLM is accessible via web console at:
http://localhost:9000/
```
prompt and attempt to browse.  We see only a blank screen:
![image](https://user-images.githubusercontent.com/5072156/114061957-e2a25700-988e-11eb-80ec-a03d305b5caa.png)

**What did you expect to see?**
OLM webui.

**What did you see instead? Under which circumstances?**
Error in bash window is per the above screenshot: "Failed to get user data to handle user setting request: the server could not find the requested resource"
````
The OLM is accessible via web console at:
http://localhost:9000/
Press Ctrl-C to quit
2021/04/08 16:16:20 CheckOrigin: Proxy has no configured Origin. Allowing origin [http://localhost:9000] to wss://10.0.0.1:6443/api/v1/namespaces/openshift-console-user-settings/configmaps?watch=true&fieldSelector=metadata.name%3Duser-settings-kubeadmin
E0408 16:16:21.157873       1 handlers.go:82] Failed to get user data to handle user setting request: the server could not find the requested resource
2021/04/08 16:16:21 CheckOrigin: Proxy has no configured Origin. Allowing origin [http://localhost:9000] to wss://10.0.0.1:6443/apis/apiregistration.k8s.io/v1/apiservices?watch=true&resourceVersion=301348
E0408 16:16:21.286030       1 handlers.go:82] Failed to get user data to handle user setting request: the server could not find the requested resource
E0408 16:16:21.314848       1 handlers.go:82] Failed to get user data to handle user setting request: the server could not find the requested resource
````

**Environment**
docker image "quay.io/openshift/origin-console:latest" is sha256:bba74d5412ad78411553fda72bd716f37158a09575d430172f9c997eaae69322
OLM is v0.17.0.  We installed using commands:
````
curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.17.0/install.sh | bash -s v0.17.0
kubectl apply -f deploy/crds/
make run-console-local
````
* Kubernetes version information:
v1.19.7

* Kubernetes cluster kind: 
native

**Comment by web-apply** [comment]
[http://localhost:9000/](https://localhosts.mobi/9000)
