### ISSUE TITLE
Operators installed on different namespaces in the same cluster with the manual approval strategy are upgrading automatically by approving the upgrade in one namespace.

### ISSUE THREAD

**Issue by AnilKumarBandi27** [operator-framework/operator-lifecycle-manager#2113]
Hi,

Operators installed on different namespaces in the same cluster with the manual approval strategy are upgrading automatically by approving the upgrade in one namespace.

I have installed three operators on two different namespaces with a manual approval strategy.
I have released updates for all three operators.
I have seen the option upgrade available for all three operators, in both the namespaces.
When I clicked on upgrade available for one operator and approved the update. I have seen all the three operators got updated. Also, the same operators which are installed on different namespaces got updated.
Is there a way to avoid operator upgrade until we approve it for each operator?
Why operators in different namespace B are getting upgraded when we approve in namespace A?
Why all the three operators in the same namespace are getting upgraded when we approve one operator?

Environment
Ansible Operator:
Operator-SDK v1.4.2
OCP Clusters 4.5.x, 4.6.x, and 4.7,x

**Comment by exdx** [comment]
Hi @AnilKumarBandi27 , this seems like a serious issue, it could be an aggregation issue in the console, we haven't seen this behavior before on the OLM side directly.

Have you ever seen this behavior outside of using the console? We are going to double-check this behavior to be sure.

**Comment by dinhxuanvu** [comment]
Hi,
This is an issue with the OpenShift Console so we recommend you to open an issue on https://github.com/openshift/console instead. If you approve the IP via CLI, it should work as expected.
