### ISSUE TITLE
Please keep support for multiple namespaces

### ISSUE THREAD

**Issue by sathieu** [operator-framework/operator-lifecycle-manager#2124]
## Feature Request

Current doc [says](https://docs.openshift.com/container-platform/4.7/operators/understanding/olm/olm-understanding-operatorgroups.html#olm-operatorgroups-target-namespace_olm-understanding-operatorgroups):

> Listing multiple namespaces via `spec.targetNamespaces` or use of a label selector via `spec.selector` is not recommended, as the support for more than one target namespace in an Operator group will likely be removed in a future release.

Please keep this feature in future releases and remove this warning.

This is especially needed for the crunchy postgres operator (we want each namespace to be able to provision PostgreSQL).

**Comment by exdx** [comment]
Hi @sathieu, I think there's a lot of confusion around the OLM descoping plans -- OLM still plans to support the operator's ability to watch and interact with specific namespaces. Not every operator will be cluster scoped. 

We are still iterating on the design, but should have some docs on this topic soon. The crunchy postgres operator will still be able to run in and watch individual namespaces. We will update the docs for clarity as part of providing more support to users on the future of OLM.

**Comment by kevinrizza** [comment]
A few things:

That documentation mention is specifically in the openshift documentation, which this project does not explicitly have ownership over.

That being said, we have been iterating on the future of tenancy with OLM. The project is now in a state where our intention is to migrate to a descoped operator installation concept. In this world, operators can define their own namespace watches via rbac explicitly, and as a result of that OLM will only ever install one version of the operator on a cluster.

So, the short answer is that OperatorGroups as a concept will be deprecated in a future release.
