### ISSUE TITLE
quay.io/operator-framework/olm for v0.18.0 cannot start container "util" due to missing /bin/cp

### ISSUE THREAD

**Issue by zhaminglei** [operator-framework/operator-lifecycle-manager#2129]
**What did you do?**
Installed OLM v0.18.0 
created a catalogsource with an index built by me
created a subscription to the catalogsource

**What did you expect to see?**
The flow is able to parse my index and moving forward, generate Installplan etc..

**What did you see instead? Under which circumstances?**
Job failed due to following issue:

```
Successfully assigned blah/6d587b34c86ea704dce32c7abc361c7cf3a078db7d3e86673e7406d3f88nwzv to minikube
  Normal   Pulling    22s                kubelet            Pulling image "quay.io/operator-framework/olm@sha256:e9de77ac5c08643202ad42a0311d15c98ffbfd8a1dc2eab4e9f2dcaeed7110ac"
  Normal   Pulled     22s                kubelet            Successfully pulled image "quay.io/operator-framework/olm@sha256:e9de77ac5c08643202ad42a0311d15c98ffbfd8a1dc2eab4e9f2dcaeed7110ac" in 747.878744ms
  Warning  BackOff    17s (x2 over 18s)  kubelet            Back-off restarting failed container
  Normal   Created    3s (x3 over 21s)   kubelet            Created container util
  Normal   Pulled     3s (x2 over 19s)   kubelet            Container image "quay.io/operator-framework/olm@sha256:e9de77ac5c08643202ad42a0311d15c98ffbfd8a1dc2eab4e9f2dcaeed7110ac" already present on machine
  Warning  Failed     2s (x3 over 21s)   kubelet            Error: failed to start container "util": Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/bin/cp": stat /bin/cp: no such file or directory: unknown

```

**Environment**
* operator-lifecycle-manager version:
v0.18.0

* Kubernetes version information:

kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

minikube with virtualbox as driver.

**Possible Solution**
Please verify the file in the images and executable

**Additional context**

v0.17.0 is working fine for me
Another issue opened in operator-sdk: https://github.com/operator-framework/operator-sdk/issues/4833

**Comment by benluddy** [comment]
Thanks for reporting this. I marked v0.18.0 as "pre-release", which appears to make v0.17.0 be considered the latest release again. I hope that will prevent other operator-sdk users from hitting this.

The base image `gcr.io/distroless/static:debug` introduced in https://github.com/operator-framework/operator-lifecycle-manager/commit/14df1168dda8a214b6e429bc9983e03d1def8e07 does have `cp` via busybox, but it's not at the path that the bundle unpacker expects. A symlink should fix it, or maybe `cpb` could be extended to copy itself?

This also highlights a testing gap: the E2E test jobs build an image locally using `e2e.Dockerfile`. That could probably be unified with `upstream.Dockerfile`, and there should also be an end-to-end run for tagged releases that installs OLM using the release payload.

I'll leave this issue here to track a v0.19.0 roll-forward release.

**Comment by njhale** [comment]
The patch merged: https://github.com/operator-framework/operator-lifecycle-manager/pull/2133

**Comment by zhaminglei** [comment]
> Thanks for reporting this. I marked v0.18.0 as "pre-release", which appears to make v0.17.0 be considered the latest release again. I hope that will prevent other operator-sdk users from hitting this.
> 
> The base image `gcr.io/distroless/static:debug` introduced in [14df116](https://github.com/operator-framework/operator-lifecycle-manager/commit/14df1168dda8a214b6e429bc9983e03d1def8e07) does have `cp` via busybox, but it's not at the path that the bundle unpacker expects. A symlink should fix it, or maybe `cpb` could be extended to copy itself?
> 
> This also highlights a testing gap: the E2E test jobs build an image locally using `e2e.Dockerfile`. That could probably be unified with `upstream.Dockerfile`, and there should also be an end-to-end run for tagged releases that installs OLM using the release payload.
> 
> I'll leave this issue here to track a v0.19.0 roll-forward release.

Thanks a lot, is there an ETA to push the new version out with the fix? or any workaround to allow me use the version?

**Comment by pedjak** [comment]
operatorhub.io instructions are still advertising the usage of OLM 0.18 version

**Comment by kevinrizza** [comment]
Looks like this should be resolved with the release of https://github.com/operator-framework/operator-lifecycle-manager/releases/tag/v0.18.1
