### ISSUE TITLE
Remove the root manifests directory and OCP/downstream helm charts

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/operator-lifecycle-manager#2130]
The root manifests are no longer needed now that a new repository was created to house the downstream OCP builds, and this repository was decoupled from the OCP release cycle.

We can similarly investigate removing the OCP-related helm charts entirely from upstream.

**Comment by timflannagan** [comment]
I'm going to throw this in the backlog for now as it's technically a nice-to-have, rather than something we need to actively address.

**Comment by benluddy** [comment]
Reopening, historical ocp charts are still around.

**Comment by timflannagan** [comment]
Another somewhat related question now that we're decoupled from the OCP release cadence -- do we want to continue committing the root vendor directory to the repository?
