### ISSUE TITLE
Is it possible to deploy a custom operator catalog  that runs with the `restricted` scc?

### ISSUE THREAD

**Issue by huizengaJoe** [operator-framework/operator-lifecycle-manager#2166]
I am deploying a custom catalogSource image that is build using opm tooling,  I noticed that the pod that is actually created when I deploy my catalogSource is NOT using the `restricted` scc.  I also did a quick check of some of the other pods running in the openshift-marketplace namespace here is what I see:
```
$ oc get po certified-operators-xrgcd -oyaml | grep scc
    openshift.io/scc: anyuid
          f:openshift.io/scc: {}
$ oc get po redhat-marketplace-65vw8 -oyaml | grep scc
    openshift.io/scc: anyuid
          f:openshift.io/scc: {}
$ oc get po ibm-operator-catalog-rhkzh -oyaml | grep scc
    openshift.io/scc: anyuid
    ```

**Comment by exdx** [comment]
Let's track this in the related BZ instead of the GH issue.
