### ISSUE TITLE
How to run the catalog pod with a non-root user

### ISSUE THREAD

**Issue by efussi** [operator-framework/operator-lifecycle-manager#2203]
## Type of question

[x] how to implement a specific feature:

Our operator is running on OpenShift, and the security policy is that images must be based on UBI minimal and pods must run with a non-root user (this will be flagged in a Twistlock scan). However, the catalog pods created by OLM run with the root user.

## Question

**What did you do?**
I added a `USER` directive to our **Dockerfile** as follows (the `ls` statements are just for debugging purposes):
```dockerfile
FROM registry.redhat.io/openshift4/ose-operator-registry:v4.6 AS builder
FROM registry.access.redhat.com/ubi8/ubi-minimal
LABEL operators.operatorframework.io.index.database.v1=/database/index.db
RUN echo "opm:x:3000:0::/home/opm:/sbin/nologin" >> /etc/passwd && id && ls -ld /dev && chmod g+w /dev && ls -ld /dev
RUN ls -ld /dev
USER opm
COPY bundles.db /database/index.db
COPY --from=builder /bin/opm /bin/opm
COPY --from=builder /bin/grpc_health_probe /bin/grpc_health_probe
EXPOSE 50051
ENTRYPOINT ["/bin/opm"]
CMD ["registry", "serve", "--database", "/database/index.db"]
```

As an alternative, I tried
```
CMD ["registry", "serve", "--database", "/database/index.db","-t","/tmp/termination-log"]
```

**What did you expect to see?**
Catalog pod comes up successfully.

**What did you see instead? Under which circumstances?**
It fails with
```
time="2021-05-10T10:38:37Z" level=warning msg="unable to set termination log path" error="open /dev/termination-log: permission denied"
```
The docker build logs show that **/dev** is special and any attempt to change permissions is discarded right in the next layer:
```
 ---> Running in 48f177f8d26a
uid=0(root) gid=0(root) groups=0(root)
drwxr-xr-x 5 root root 340 May 10 10:42 /dev
drwxrwxr-x 5 root root 340 May 10 10:42 /dev
Removing intermediate container 48f177f8d26a
 ---> 09c82b7a86e9
Step 10/14 : RUN ls -ld /dev
 ---> Running in 29b7d1ac9565
drwxr-xr-x 5 root root 340 May 10 10:42 /dev
```

Using the extra parameter `"-t","/tmp/termination-log"`, the catalog pod comes up fine, but its definition is unaware of the changed **termination-log** path:
```
$ oc get pod/my-operator-catalog-h96pt -n openshift-marketplace -o yaml | grep " termination"
    terminationMessagePath: /dev/termination-log
```
I cannot proof it, but I doubt this will work correctly. I also checked the OLM code to see if there was an annotation to tell OLM which `terminationMessagePath` to use (similar to `operators.operatorframework.io.index.database.v1=/database/index.db`) but didn't find anything.

**Environment**
* operator-lifecycle-manager version:

    Not sure how to get this, but if I run `oc describe pod -n openshift-operator-lifecycle-manager olm-operator-67c6b9d448-n87l7`, the output contains this:
    ```
    Image:         quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5017c2872fcf1820a0e5db74a16da7353759c187d4d28bab5b3bc2a3fd3e475c
     RELEASE_VERSION:     4.6.21
    ```

* Kubernetes version information:

    ```
    Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+2f3101c", GitCommit:"2f3101cb663d0cb102ccb9730b63753604f6d29b", GitTreeState:"clean", BuildDate:"2021-02-26T13:55:24Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
    ```

* Kubernetes cluster kind: 

    OpenShift Container Platform 4.6.

**Additional context**
None.

**Comment by exdx** [comment]
There is a way to do this right now -- use address type `catalog source` to point to an IP address on the cluster (the service fronting the catalog source) which allows you to use a custom catalog pod (which custom permissions). 

There are catalogs that run as user 1001 so this is definitely something that is supported, it's set in the Dockerfile itself. So if you set a custom user in the image build process it should be used on-cluster. We do not specify a user by default though.

**Comment by exdx** [comment]
Relates to #2023

**Comment by joelanford** [comment]
I am able to build a custom index image by including the following two lines directly before the `EXPOSE 50051` line.

```Dockerfile
WORKDIR /tmp
USER 1001:0
```

The resulting Dockerfile looks like this:
```Dockerfile
FROM registry.redhat.io/openshift4/ose-operator-registry:v4.6 as builder

FROM registry.access.redhat.com/ubi8/ubi-minimal
LABEL operators.operatorframework.io.index.database.v1=/database/index.db
ADD database/index.db /database/index.db

COPY --from=builder /bin/opm /bin/opm
COPY --from=builder /bin/grpc_health_probe /bin/grpc_health_probe

USER 1001:0
WORKDIR /tmp

EXPOSE 50051
ENTRYPOINT ["/bin/opm"]
CMD ["registry", "serve", "--database", "/database/index.db"]
```

After building and pushing this image and creating a CatalogSource referencing it, I can see the registry pod successfully running in a cluster.

@efussi Can you try to reproduce with these steps?

**Comment by efussi** [comment]
Thanks for your suggestion, @joelanford. I will get to this next week, and report back here.

**Comment by efussi** [comment]
Using
```dockerfile
USER 1001:0
WORKDIR /tmp
````
appears to work. The only real difference to my original attempt is the `WORKDR` directive. Based on my testing, it solves the
```
Error: open db-592845606: permission denied                                                                        
Usage:                                                                                                             
  opm registry serve [flags]
```
error when a non-root user tries to write to the `/` directory.
Now the weird thing is that I am unable to recreate my initial error
```
"open /dev/termination-log: permission denied"
```
no matter what I tried. Looking at the code https://github.com/operator-framework/operator-registry/blob/5f55ec29ef79ac386f32e531ea5585fe4d97f170/cmd/opm/registry/serve.go#L53-L58 I think the termination log file is accessed right during startup, not only when it's being written to. That is, once the pod started successfully we should not have a permission issue with the termination log during pod shutdown.
Can you please confirm, @joelanford? If so, I am good to close this issue (although I'd really love to understand what happened to the original `permission denied` error :-) )

**Comment by joelanford** [comment]
> That is, once the pod started successfully we should not have a permission issue with the termination log during pod shutdown.
Can you please confirm, @joelanford?

Yes, I believe this is correct.

> although I'd really love to understand what happened to the original permission denied error

Based on https://github.com/kubernetes/kubernetes/issues/31839, it seems like `/dev/termination-log` is created with `0666` perms in the pod prior to the entrypoint running, which means it would be writable by the root user/group (or any other uid). So I'm not sure how you got that error.

**Comment by efussi** [comment]
Thanks @joelanford! Closing this issue now.
