### ISSUE TITLE
Pause Operator Lifecycle Manager

### ISSUE THREAD

**Issue by clyang82** [operator-framework/operator-lifecycle-manager#2212]
## Type of question

community best practices

## Question

**What did you do?**
Can I pause Operator Lifecycle Manager so that I can enable debug mode to debug my operator? my operator is installed by olm. When I modify the operator deployment, it will be reconciled back at once.

**What did you expect to see?**
I can modify my operator deployment for debugging.

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

  

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by ecordell** [comment]
You can pause OLM by spinning down it's pods, but in this case you should be able to to modify the CSV for your operator directly. The changes you make to the CSV (i.e. enabling debug mode) will be propagated to the deployment.

**Comment by clyang82** [comment]
Yes. that works to directly modify the CSV. I considered that the CSV will be controlled by InstancePlan and it may pull back my changes. It seem the OLM just monitor if there has version changed in operatorHub and apply once.  Thanks @ecordell
