### ISSUE TITLE
Syntax error in csv incorrectly reported as missing csv in bundle.

### ISSUE THREAD

**Issue by renan-campos** [operator-framework/operator-lifecycle-manager#2227]
## Bug Report

**What did you do?**
I'm tried to deploy the operator I'm developing with `operator-sdk run bundle ...`, but the command reported that it was unable to find the csv in the manifests directory of bundle image. However, I exported the filesystem of the bundle image and verified that there was a csv in the manifests directory. After some experimenting I found that the same reporting behavior occurs in `operator-sdk validate bundle`, and that the true error was invalid syntax in my csv.yaml.

**What did you expect to see?**
```
[rcampos@rh-laptop src]$ operator-sdk bundle validate ./bundle                                                                                    
FATA[0000] Syntax error in csv. :'(
```

**What did you see instead? Under which circumstances?**
```
[rcampos@rh-laptop src]$ # Validating a valid csv
[rcampos@rh-laptop src]$ operator-sdk bundle validate ./bundle
INFO[0000] Found annotations file                        bundle-dir=bundle container-tool=docker
INFO[0000] Found dependencies file                       bundle-dir=bundle container-tool=docker
INFO[0000] All validation tests have completed successfully 
[rcampos@rh-laptop src]$ # Adding a syntax error to the valid csv
[rcampos@rh-laptop src]$ echo "foobar" >> ./bundle/manifests/csv.yaml
[rcampos@rh-laptop src]$ # Running validation again...
[rcampos@rh-laptop src]$ operator-sdk bundle validate ./bundle
FATA[0000] unable to find a csv in bundle directory bundle/manifests
```

**Environment**
* operator-lifecycle-manager version:
```
[rcampos@rh-laptop src]$ operator-sdk version
operator-sdk version: "v1.8.0", commit: "d3bd87c6900f70b7df618340e1d63329c7cd651e", kubernetes version: "v1.20.2", go version: "go1.15.9", GOOS: "linux", GOARCH: "amd64"
```

* Kubernetes version information:
```
[rcampos@rh-laptop src]$ oc version
Client Version: 4.5.7
Kubernetes Version: v1.19.2
```

* Kubernetes cluster kind: 
```
[rcampos@rh-laptop src]$ oc get node
NAME       STATUS   ROLES    AGE   VERSION
minikube   Ready    master   22d   v1.19.2
```

**Comment by kevinrizza** [comment]
This seems like an issue with the operator-sdk parsing and error handling logic, especially if it is happening with their `validate bundle` command. Can you please file an issue on the operator-sdk project instead? https://github.com/operator-framework/operator-sdk/issues
