### ISSUE TITLE
Remove broken git tag v3.11.0

### ISSUE THREAD

**Issue by sathieu** [operator-framework/operator-lifecycle-manager#2253]
## Bug Report

See https://github.com/operator-framework/operator-lifecycle-manager/tree/v3.11.0.

v3.11 is an OpenShift version, dated Sept 2018, and it's > v0.18.3 which is the current OLM version. This breaks semver.

**Comment by exdx** [comment]
This probably can't be removed right now because the older versions of OLM (downstream) are still being managed from this repo. 

We may have to configure the 3.11 build to look outside of this repository. Cleaning up our git tags is a good upstream initiative to take on.

**Comment by sathieu** [comment]
@exdx Alternatively, bump olm version to v4?

**Comment by awgreene** [comment]
@joelanford pointed out that it is possible to exclude a release via the go.mod file. Might be worth checking out.

**Comment by exdx** [comment]
Proposed solution: create a branch from the v3.11.0 tag, and then delete the tag.

**Comment by kevinrizza** [comment]
I just deleted the tag. This should be resolved

**Comment by janisz** [comment]
> I just deleted the tag. This should be resolved

This breaks dependabot as the tag is still there in proxies. Could you retract it https://go.dev/ref/mod#go-mod-file-retract
