### ISSUE TITLE
Dynamic UI for operator - conditional form view fields

### ISSUE THREAD

**Issue by rasapala** [operator-framework/operator-lifecycle-manager#2255]
I was following the Declarative UI blog - https://www.openshift.com/blog/openshift-4-2-declarative-dynamic-ui-for-your-operator - and I have a question how can I additionally organize the UI fields defined in CRD scheme in the  "form view" UI of my operator.

One form of manipulation I am interested in is how to organize certain fields in sections with headers - is there a way to do that ?

Another form is to introduce conditions if certain fields are set (input or x-descriptor selection) can I hide other fields or mark them as required/unrequired in a dynamic manner described in the blog.

apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion plus kind: CustomResourceDefinition

**Comment by exdx** [comment]
HI @rasapala , the console repository [1] would be a good place to ask this question. OLM doesn't really own or interact with the console side as much. The x-descriptors would let you do this but you would have to implement the extra bits in the console. 

[1] https://github.com/openshift/console
