### ISSUE TITLE
Is there a way to develop and debug at local environment (minikube or kind)

### ISSUE THREAD

**Issue by aiyijing** [operator-framework/operator-lifecycle-manager#2295]
## Feature Request

> In fact，packageserver 、catalog and olm should run as OutCluster. 

> I don't seem to find a way to debug minike here. If we can develop 
and debug by minikube.it will be very convenient to fix some bug.

**Comment by timflannagan** [comment]
@aiyijing I'm trying to wrap my head around this feature request - it looks like you're interested in running the various OLM components locally through local binaries (e.g. ./bin/olm ...) and providing the requisite CLI flags. Just want to double-check whether that's the correct assumption as I saw `should run as OutCluster` in the original comment. Any other details that you can provide for what you're looking for?

**Comment by timflannagan** [comment]
I played around with running both the OLM and Cluster Operator(s) using a local executable and providing the requisite CLI flags, and everything appeared to be working for me.

I ran into a real small error where the Catalog Operator requires the kubeconfig flag to be explicitly specified when running out-of-cluster, so I opened https://github.com/operator-framework/operator-lifecycle-manager/pull/2303 which defaults to reading from the $KUBECONFIG environment variable.

**Comment by aiyijing** [comment]
>  It looks great
Thank you very much for trying to understand what I said。

**Comment by timflannagan** [comment]
Was there anything else you needed help with on the debug/developing locally side-of-things or should we close this out?

**Comment by aiyijing** [comment]
thank you, so close this out
