### ISSUE TITLE
Investigate overhauling the change log process

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/operator-lifecycle-manager#2308]
This is a follow-up tracker to the v0.18.3 release being cut without the root CHANGELOG.md not being updated to reflect changes since the v0.18.0 release.

This issue tracks updating the root CHANGELOG.md with the v0.18.1, v0.18.2, and v0.18.3 release notes.

## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

**Comment by awgreene** [comment]
Discussed this in the upstream Triage meeting, @joelanford pointed out that GoReleaser has the ability to generate a change log and is under consideration for use in the operator-framwork/operator-registry project. @joelanford will review how the existing change log is generated and make a case for moving to GoReleaser.

**Comment by awgreene** [comment]
@timflannagan will update the changelogs in the v0.18.1, v0.18.2, and v0.18.3 releases.

**Comment by timflannagan** [comment]
Closing as we now rely on goreleaser to handle generating CHANGELOGs at release time vs. maintaining a static list that's housed in this repository.
