### ISSUE TITLE
install.sh detects the existence of OLM in a wrong namespace

### ISSUE THREAD

**Issue by morningspace** [operator-framework/operator-lifecycle-manager#2327]
## Bug Report

**What did you do?**
Using `install.sh` to install OLM, I see the script always tries to deploy OLM even if that has been deployed on the target cluster already.

**What did you expect to see?**

The `install.sh` script should not always deploy OLM even it has already been deployed.

**What did you see instead? Under which circumstances?**

The current `install.sh` has [a way](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/scripts/install.sh#L17) to check and exit if OLM has already been installed. However, the namespace it uses, `openshift-operator-lifecycle-manager`, is not the one it is defined in a variable called `namespace`, where the value is `olm`.

The `install.sh` script should use the right namespace to check the existence of OLM deployment.

**Environment**
* operator-lifecycle-manager version:

0.18.3

* Kubernetes version information:

v1.19.1, but should impact all versions.

* Kubernetes cluster kind: 

v0.9.0, but should impact all versions.

**Possible Solution**

See above.

**Comment by morningspace** [comment]
If needed I can submit a PR since it seems to be a simple fix.

**Comment by joelanford** [comment]
@morningspace That particular line is actually a fail-safe to make sure that users are not trying to install OLM on an OpenShift cluster, which comes with OLM already installed in the openshift-operator-lifecycle-manager namespace.

However, I think what you're actually asking for is a check that prevents `install.sh` from continuing if it detects an existing OLM install _anywhere_ in the target cluster?

**Comment by morningspace** [comment]
@joelanford Aha I see, thanks for the clarification, and yes, that is what I am asking for, more accurately: prevents `install.sh` from continuing if it detects an existing OLM installed in the namespace where `install.sh` is going to install OLM. So, if I run `install.sh` for the second time against the same cluster, it exit immediately since OLM has already been installed in the target namespace. Does it make sense?

**Comment by morningspace** [comment]
This is exactly what I mean. And, I assume both `olm` and `openshift-operator-lifecycle-manager` (per https://github.com/operator-framework/operator-lifecycle-manager/issues/2327#issuecomment-899476144) need to be covered.

**Comment by joelanford** [comment]
Seems mostly reasonable to me. FWIW, I think `operator-sdk olm install` checks to make sure that none of the objects in the install manifests exist.

But checking for `olm` namespace is better than nothing and probably catches 90+% of what folks want.

**Comment by timflannagan** [comment]
Yeah, that sounds reasonable to me - @morningspace would you be willing to submit a PR that checks for the `olm` namespace in the install.sh bash script?

**Comment by morningspace** [comment]
sure @timflannagan, the PR is ready for review :-)

**Comment by timflannagan** [comment]
#2334 just merged :tada:
