### ISSUE TITLE
Subscription's `installPlanApproval` is not reconciled after change to Automatic

### ISSUE THREAD

**Issue by porridge** [operator-framework/operator-lifecycle-manager#2341]
## Bug Report

**What did you do?**

1. applied a Subscription with the following fields in the `spec` (following the [official documentation to install a specific version](https://olm.operatorframework.io/docs/tasks/install-operator-with-olm/#example-install-a-specific-version-of-an-operator))
```yaml
channel: latest
installPlanApproval: Manual
startingCSV: my-operator.v3.1.0
```
2. approved the `v3.1.0` installation plan created by OLM, and it was processed as expected
3. patched the Subscription to:
   - remove the `startingCSV` field, and
   - change the `installPlanApproval` to `Automatic`

**What did you expect to see?**

A new *Automatic* install plan to be created for the most recent version in `latest` channel (v3.1.2).

**What did you see instead? Under which circumstances?**

A new plan was created for `v3.1.2` but it was *manual* as well.

```
NAME            CSV                      APPROVAL   APPROVED
install-jvvnx   my-operator.v3.1.0       Manual     true
install-zk6jr   my-operator.v3.1.2       Manual     false
```

Note: as soon as I delete `install-zk6jr` OLM does create an *automatic* and *approved* `install-rsdf7` plan and *then* processes it as expected.

Also, I'm reasonably sure `install-zk6jr` was created *before* step 3 above. Probably between 2 and 3.

**Environment**
* operator-lifecycle-manager version:

whatever comes with OpenShift 4.7.28. How do I find out? 🤷🏻  the image is `quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:c154e432b4364675b833458a1779d38e6b775e8aeee51c8cbe86f6652b2515b1` FWIW

* Kubernetes version information:

```
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+4593a24", GitCommit:"4593a24e8fd58d0921e09d2c35f9d67245a9070b", GitTreeState:"clean", BuildDate:"2021-08-13T05:18:21Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

OpenShift 4.7.28

**Possible Solution**

**Additional context**

I simplified the operator name and versions since they are mostly irrelevant.

**Comment by dinhxuanvu** [comment]
This behavior is expected. When you set the `CatalogSource` in `Manual` mode, it will create `InstallPlan` if there is an upgrade and that InstallPlan is waiting for your approval in the background. When you change the approval mode to `Automatic`, it will apply to the next `InstallPlan`, not the existing ones. OLM simply don't automatically approve existing `InstallPlan` when it is already in Manual approval mode.
/close

**Comment by porridge** [comment]
> When you change the approval mode to Automatic, it will apply to the next InstallPlan, not the existing ones. 

What is the rationale for this approach? I do not think it is consistent with other controllers. For example I think most `Deployment` changes propagate to its subordinate `ReplicaSets` right away, not "next time it creates one".
