### ISSUE TITLE
Remove controller-runtime replace pin

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/operator-lifecycle-manager#2353]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: "I have an issue when (...)"

Remove the [replace pin](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/go.mod#L66) for controller runtime once the race condition issue around metadata-only watchers has been resolved.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

Bump the controller runtime dependency and remove the replace pin once https://github.com/kubernetes-sigs/controller-runtime/pull/1650 gets tagged in a release.

**Comment by timflannagan** [comment]
It looks like c-r v0.10.1 contains that linked PR - @benluddy any idea on whether we can remove the replace pin in the root go.mod now that Joe's PR has been tagged?

**Comment by benluddy** [comment]
> It looks like c-r v0.10.1 contains that linked PR - @benluddy any idea on whether we can remove the replace pin in the root go.mod now that Joe's PR has been tagged?

I don't see why not. The partial metadata race bug was the only reason for the temporary fork.

**Comment by exdx** [comment]
@timflannagan this seems to be resolved in the latest OLM version? There is no longer a pinned version in the go.mod. Could we close this issue out?
