### ISSUE TITLE
Multiple ways to resolve a dependency?

### ISSUE THREAD

**Issue by illeatmyhat** [operator-framework/operator-lifecycle-manager#2443]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
How to implement, documentation clarification

## Question

Background: There are often multiple competing implementations of the same APIs, e.g. OpenShift Pipelines vs Tekton Pipelines
I would like my Operator to depend on _one or the other_.
Is the correct approach to use the `olm.gvk` dependency type in the bundle's `dependencies.yaml`?
How does this get resolved when both operators are installable? Is there a way to "prefer" one or the other?

**Comment by dinhxuanvu** [comment]
Hey here. You can use gvk dependency and that should work on the situation you described (one operator depends on another operator's API/CRD). You can also use `olm.package` dependency which allows you to depend on a specific operator on a specific version (or a range of versions). There is a doc on this: https://olm.operatorframework.io/docs/concepts/olm-architecture/dependency-resolution/

**Comment by illeatmyhat** [comment]
But wouldn't `olm.package` cause dependency resolution to fail if the option wasn't available, without attempting to use a fallback?

**Comment by dinhxuanvu** [comment]
> But wouldn't `olm.package` cause dependency resolution to fail if the option wasn't available, without attempting to use the other operator?

Resolution failure will happen to either gvk or package dependency if that gvk or package isn't available. It is possible for multiple operators owning the same API/CRD, then there will be more than one options to choose from. However, assuming multiple operators own the same API/CRD is not always true. Most of time, each operator owns its own set of APIs.

**Comment by illeatmyhat** [comment]
So then the solution in general is to claim that your operator only supports a specific implementation of an API and ignore the other one?

**Comment by dinhxuanvu** [comment]
Hi,

So there are a list of preferences to select resolution candidates if they are multiple of them (in term of multiple operators providing the same API that your operator depends on):

1. higher catsrc priority
2. higher catsrc name (lexical)
3. is from default channel
4. lexically higher package name
5. lexically higher channel name
6. closest to head of channel by replaces distance
