### ISSUE TITLE
Add ability to directly configure operator command line via `subscription.spec.config`

### ISSUE THREAD

**Issue by dudinea** [operator-framework/operator-lifecycle-manager#2496]
## Feature Request

**Is your feature request related to a problem? Please describe.**

When installing operators using the `Subscription` CR we customize
their runtime configuration using the configuration override settings
in `subscription.spec.config` sub-fields such as `resources`, `env`,
etc.

The `config` section has no field to modify command line arguments of
the operator.  According to the design document
https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/subscription-config.md
in order to change the command line arguments one should override the
`ARGS` environment variable.

Unfortunately there are some operators that do not provide the
ability to change their command line via environment vatiables.

It looks that we do not really have a way to deploy such operators via
Subscription because we cannot change those parameters in Deployments
(which are updated automatcally from CSV) and cannot change configure
them in CSV (that are is updated automatically from `Subscription`).

**Describe the solution you'd like**

So it would be great if there were an additional field in `Subscription` CR
for modifying command line of the operator. 

 On the other hand, It seems to me that  the entire mechanism of the
`subscription.spec.config.*` fields seems to be rather limited: 
one cannot really predict what settings customers would ever need to change.

Probably if `Subscription` could have a field for Patches against CSV
it would be a better solution? Any thoughts?

**Comment by dmesser** [comment]
Can you provide an example of such an operator? I am wondering what kind of style we should promote. IMHO configuration of operators should be externalized.

**Comment by dudinea** [comment]
In out case that was the [Jaeger Operator](https://github.com/jaegertracing/jaeger-operator)  in it's Red Hat's distribution  (Red Hat Openshift Jaeger 1.24.1). 

Actually this operator uses Cobra+Viper with AutomaticEnv() enabled, so it does have support for settings configuration via env. variables. Unfortunately for us it has lots of parameters  set in the command line flags and they have priority over env. vars and over the config file as well.

**Comment by dmesser** [comment]
Would it be bad if you just remove those command line flags and replace them with environment variable defaults for the flags that need user input? It sounds like you have the necessary control over the Jaeger operator's deployment to do that.

**Comment by dmesser** [comment]
I was under the impression that as the author of the Red Hat Jaeger operator you have full access to the Jaeger deployment that is part of the CSV. That is where you would make these changes. Are you referring to Red Hat Jaeger as a dependency of your own operator, that you have less control over?

**Comment by dudinea** [comment]
What made you think I'm the maintainer of the Red Hat's Jaeger operator?  :-) 

 I'm just trying to use that operator to deploy Jaeger on an OpenShift  cluster and need to find a way  (preferably a good one) to customize the way it runs.

**Comment by dmesser** [comment]
Sorry if I mistook your [response](https://github.com/operator-framework/operator-lifecycle-manager/issues/2496#issuecomment-976455424) earlier. As a consumer you cannot change the deployment of an operator in this aspect. This definition is generally seen as owned by the operator publisher. If they haven't made these feature flags configurable there is either an intent behind it (changes could cause breakage on the cluster) or it is an potential RFE for the operator.

**Comment by dudinea** [comment]
I very much agree with you that operator developers cannot support operators if
any aspect of deployment can be changed, one need to draw the line somewhere.

What you say is that with OLM currently the line here  is the fields that can be
configured by customer in the `subscription.spec.config` and that is by design. 

If this is the case, I think it should be stated more clearly in the
documentation, Currently, it seems to me, this distinction is not
clearly understood both by customers and operator developers (which
put into the command line args things that obviously may be changed by
customer, even very minor ones like logging level).

IMHO the specific distinction is too coarse grained 
and does not really make much sense. For example, why one cannot change 
command line but can inject and overwrite arbitrary files using Volume Mounts?

If OLM is thought to be kind of a package manager for operators,
probably it should behave more like one?  Traditional package managers
like dpkg allow package authors to specify what resources are to be
customized on file level and behave accordingly when performing
upgrades, checking package integrity, etc.

**Comment by dmesser** [comment]
Fair feedback. The intention behind the user-provided config in {{Subscription}} was initially meant to provide information specific to the runtime environment, for example proxy information and TLS certificates. The idea that you modify deeper configuration of the operator itself via this route naturally emerged. Your comparison to `dpkg` highlights exactly what OLM is doing: it's providing specific interfaces to insert customizations which thus persist during updates. It's just not allowing everything to be customizable in a generic way, which is a conscious decision because at some point the offerings provided via OLM needs to be supportable.

I agree with you that, if operator authors "hard code" things like logging verbosity into a command line switch, that might be a sign that we are not highlighting user-provided configuration options enough in the documentation.

**Comment by kevinrizza** [comment]
To expand on this: arbitrary configuration of everything that happens to be created by OLM is a very difficult problem in kubernetes -- see Pod Presets for some prior art in the space which was eventually abandoned by Kubernetes, https://v1-18.docs.kubernetes.io/docs/concepts/workloads/pods/podpreset/.

Subscription config exists to add additional specific knobs that we know can be generalized and are common use cases for most users. I think it's reasonable to talk about whether those knobs are the right ones or if additional knobs can be added, but I do not think that OLM can or should provide a passthrough to modify anything about a deployment spec -- it's a very large scoped project and out of the purview of what OLM is attempting to provide. Instead, if a deployment needs to be modified, OLM already allows you to do that: just modify the deployment spec of the operator after the CSV creates it.

In general, that release valve is really the only other option that OLM has today for users. If specific configuration knobs want to be explicitly supported by operator developers, they can also provide a CRD to configure the operator and have it persist across upgrades.
