### ISSUE TITLE
How can we change deployment image in clusterserviceversion?

### ISSUE THREAD

**Issue by 0xff-dev** [operator-framework/operator-lifecycle-manager#2497]
## Feature Request
When we create the bundles of the operator, we will write the image address of the operator deployment, but if the image does not exist, is there any way to update it? Or do we have to provide a new version of CSV? I searched issues related to `clusterserviceversion` in issues and found no similar issues.

**Describe the solution you'd like**
Maybe we can support redefining deployment mirroring in the resource of `Subscription`. By adding the field `containerIndexOfOperator` to `ClusterServiceVersion`, it indicates which container of the deployment is the real operator image. After injecting the configuration, you can modify the deployment image.

**Comment by cdjohnson** [comment]
Please see the following issue where we discussed _hot fixing_ Operators by updating the CSV post-install:
https://github.com/operator-framework/operator-lifecycle-manager/issues/1774

**Comment by 0xff-dev** [comment]
Thank you very much. That's what I'm looking for.
