### ISSUE TITLE
OLM is depending on an old version of github.com/openshift/api

### ISSUE THREAD

**Issue by fgiloux** [operator-framework/operator-lifecycle-manager#2505]
## Bug Report

**What did you do?**

`$ make test`

**What did you expect to see?**

From a fresh clone all tests run and pass.

**What did you see instead? Under which circumstances?**

~~~
/home/fgiloux/tmp/operator-lifecycle-manager/pkg/controller/operators/openshift/suite_test.go:51

  Unexpected error:
      <*fmt.wrapError | 0xc000a79920>: {
          msg: "unable to install CRDs onto control plane: unable to create CRD instances: unable to get CRD \"clusteroperators.config.openshift.io\" to check if it exists: no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\"",
          err: <*fmt.wrapError | 0xc000a79900>{
              msg: "unable to create CRD instances: unable to get CRD \"clusteroperators.config.openshift.io\" to check if it exists: no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\"",
              err: <*fmt.wrapError | 0xc000a798e0>{
                  msg: "unable to get CRD \"clusteroperators.config.openshift.io\" to check if it exists: no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\"",
                  err: <*meta.NoKindMatchError | 0xc0010f0b00>{
                      GroupKind: {
                          Group: "apiextensions.k8s.io",
                          Kind: "CustomResourceDefinition",
                      },
                      SearchedVersions: ["v1beta1"],
                  },
              },
          },
      }
      unable to install CRDs onto control plane: unable to create CRD instances: unable to get CRD "clusteroperators.config.openshift.io" to check if it exists: no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
  occurred
~~~

**Environment**
* operator-lifecycle-manager version: master branch

`commit e6cc305d49e865020b0d3481b621bf7412fb871a (HEAD -> master, origin/master, origin/HEAD)`

* Kubernetes version information:

v1.22.1

* Kubernetes cluster kind: 

Envtest

**Possible Solution**

CRD v1beta1 has been deprecated since Kubernetes 1.16 and removed in 1.22. OLM relies on:

- github.com/openshift/api v0.0.0-20200331152225-585af27e34fd
- github.com/openshift/client-go v0.0.0-20200326155132-2a6cd50aedd0

They are very old and  contain the old definitions whereas release-4.8 already contains the v1 version:
https://github.com/openshift/api/blob/master/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml

**Additional context**

This is successful:

~~~
$ source <(setup-envtest use -i -p env 1.19.2)
$ make test
~~~

**Comment by timflannagan** [comment]
We'll likely get this for free when #2368 (https://github.com/operator-framework/operator-lifecycle-manager/pull/2368/commits/2d236f8bac9e33a6db7923844280d24110f9bafd) lands.

**Comment by timflannagan** [comment]
closing as #2368 just landed in master
