### ISSUE TITLE
e2e Subscription - creation with pod config [It] fails intermittently

### ISSUE THREAD

**Issue by akihikokuroda** [operator-framework/operator-lifecycle-manager#2507]
## Bug Report

I saw this error in the e2e test in the CI.  This error can be seen more often by adding "time.Sleep(10 * time.Second)" in the "case v1alpha1.CSVPhaseInstalling:" part in transitionCSVState function in the olm/operator.go.

Subscription 
/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:52
  creation with pod config [It]
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/subscription_e2e_test.go:1203

          Error Trace:        subscription_e2e_test.go:2874
                              subscription_e2e_test.go:1350
                              runner.go:113
                              runner.go:64
                              it_node.go:26
                              spec.go:215
                              spec.go:138
                              spec_runner.go:200
                              spec_runner.go:170
                              spec_runner.go:66
                              suite.go:79
                              ginkgo_dsl.go:238
                              ginkgo_dsl.go:221
                              e2e_test.go:59
          Error:              Should be true
          Test:               Subscription creation with pod config
          Messages:           Volume name=test-volume-7gxcg not injected

  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/vendor/github.com/stretchr/testify/assert/assertion_format.go:714
**What did you do?**
Error in CI e2e test

**What did you expect to see?**
Should not fail

**What did you see instead? Under which circumstances?**
Failure in CI e2e test

**Environment**
* operator-lifecycle-manager version: Pull request branches 

* Kubernetes version information: 

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

**Comment by timflannagan** [comment]
Re-opening as it looks like a [recent action](https://github.com/operator-framework/operator-lifecycle-manager/runs/4693753848?check_suite_focus=true) had this test failure still present.

**Comment by akihikokuroda** [comment]
@timflannagan Please assign this to me.

**Comment by akihikokuroda** [comment]
The runtime code is working fine now.  The e2e test code has an issue.  It captures the CSV before the configs are injected into it.  The configs are injected into the CSV and the deployment later correctly.  I think that the e2e test has to wait to capture the CSV until the owner of the CSV is set.  I'll verify if this is correct.

**Comment by akihikokuroda** [comment]
I couldn't find a good condition that shows the timing to fetch the CSV to check the config injections.  I'll add the Eventually around fetching the CSV and checking the config.
