### ISSUE TITLE
Unit test registry/grpc fails intermittently

### ISSUE THREAD

**Issue by akihikokuroda** [operator-framework/operator-lifecycle-manager#2522]
## Bug Report

**What did you do?**
In the CI build, the registry/grpc unit test fails intermittently.
https://github.com/operator-framework/operator-lifecycle-manager/runs/4490427895?check_suite_focus=true

This failure can be reproduced by a making change in controller/registry/grpc/source.go
```
diff --git a/pkg/controller/registry/grpc/source.go b/pkg/controller/registry/grpc/source.go
index 59856c7f3..d022c0c07 100644
--- a/pkg/controller/registry/grpc/source.go
+++ b/pkg/controller/registry/grpc/source.go
@@ -188,7 +188,7 @@ func (s *SourceStore) Add(key registry.CatalogKey, address string) (*SourceConn,
        s.sourcesLock.Lock()
        s.sources[key] = source
        s.sourcesLock.Unlock()
-
+time.Sleep(5*time.Second)
        go s.watch(ctx, key, source)
 
        return &source, nil
```
and change the timeout form 10 to 20 seconds in the controller/registry/grpc/source_test.go
```
			// start source manager
                        syncer := NewFakeSourceSyncer(len(tt.expectedHistory))
			sources := NewSourceStore(logrus.New(), 1*time.Second, 5*time.Second, syncer.sync)
                        ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
                        defer cancel()
                        sources.Start(ctx)
```
**What did you expect to see?**
No failure.

**What did you see instead? Under which circumstances?**
Unit test failure above.

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

**Comment by timflannagan** [comment]
another failure: https://github.com/operator-framework/operator-lifecycle-manager/runs/4610831885?check_suite_focus=true

**Comment by timflannagan** [comment]
Closed in https://github.com/operator-framework/operator-lifecycle-manager/pull/2521. Let's re-open this issue if we find any subsequent unit tests that are failing for the same reason as documented here.
