### ISSUE TITLE
support Descriptors for metadata

### ISSUE THREAD

**Issue by XiaoBoya** [operator-framework/operator-lifecycle-manager#2526]
## Feature Request

I have an issue when create cr about tekton-operator tektonpipeline.
The CRD‘s controller designs that limit the name of cr which name must be 'pipleine'.

**Describe the solution you'd like**
Is it possible to add rules to restrict the fields in the metadata, like SpecDescriptors

**Comment by dinhxuanvu** [comment]
We do not control the tekton-operator manifest. So if you have an issue with tekton-operator CRD, please reach out to their development team directly: https://tekton.dev/docs/operator/.
