### ISSUE TITLE
Don't generate kubeclient at runtime in testing framework

### ISSUE THREAD

**Issue by awgreene** [operator-framework/operator-lifecycle-manager#2570]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Functions used to facilitate testing should request a kubeclient as a parameter as opposed to creating a new Kubeclient as part of the function. Born from [this disscussion](https://github.com/operator-framework/operator-lifecycle-manager/pull/2444/files#r777701898)

**Describe the solution you'd like**
Do not generate kubeclients at runtime in functions used for e2e testing.

**Comment by exdx** [comment]
This would require taking a look at the existing e2e tests and wherever a client is being generated as part of the test, replace it with a client that created at test start-up time.

**Comment by nsapse** [comment]
As I hack away on this I just want to confirm I'm understanding the scope correctly. The original issue is limited to replacing created instances of kubeclient in functions where the second says `wherever a client is being generated as part of the test` which seems slightly broader. I am currently working on refactoring out all test based instances of creating clients and replacing them with tests created at startup time in the global before each. Before I go any further - is that consistent with what's desired from this ticket?
