### ISSUE TITLE
[FLAKE] can satisfy an associated ClusterServiceVersion's ownership requirement

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/operator-lifecycle-manager#2646]
### Description

Unfortunately, I marked this as a flake without capturing the stack trace ._.
Once I get it I'll update the issue. Or if this test fails for you, please paste in the stack trace and log link if possible.

**Comment by akihikokuroda** [comment]
[Failure log](https://github.com/operator-framework/operator-lifecycle-manager/runs/5243365133?check_suite_focus=true)

ClusterServiceVersion when a CustomResourceDefinition was installed alongside a ClusterServiceVersion 
  [FLAKE] can satisfy an associated ClusterServiceVersion's ownership requirement
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:148
[BeforeEach] ClusterServiceVersion
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:56
[BeforeEach] when a CustomResourceDefinition was installed alongside a ClusterServiceVersion
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:74
[It] [FLAKE] can satisfy an associated ClusterServiceVersion's ownership requirement
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:148
[AfterEach] when a CustomResourceDefinition was installed alongside a ClusterServiceVersion
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:133
[AfterEach] ClusterServiceVersion
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:61
cleaning up ephemeral test resources...
deleting test subscriptions...
deleting test installplans...
deleting test catalogsources...
deleting test crds...
deleting test csvs...
test resources deleted

• Failure in Spec Teardown (AfterEach) [63.094 seconds]
ClusterServiceVersion
/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:44
  when a CustomResourceDefinition was installed alongside a ClusterServiceVersion
  /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:65
    [FLAKE] can satisfy an associated ClusterServiceVersion's ownership requirement [AfterEach]
    /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:148

    Timed out after 60.000s.
    Expected
        <bool>: false
    to be true


    /home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:144

    Full Stack Trace
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.glob..func6.4.2()
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:144 +0x207
    github.com/operator-framework/operator-lifecycle-manager/test/e2e.TestEndToEnd(0xf908f9)
    	/home/runner/work/operator-lifecycle-manager/operator-lifecycle-manager/test/e2e/e2e_test.go:59 +0x268
    testing.tRunner(0xc00073e680, 0x30058d0)
    	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1259 +0x102
    created by testing.(*T).Run
    	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1306 +0x35a

**Comment by akihikokuroda** [comment]
This is the namespace deletion issue.

**Comment by perdasilva** [comment]
Thank you @akihikokuroda!!!
