### ISSUE TITLE
lower/remove "object has been modified" type log messages from the OLM operators

### ISSUE THREAD

**Issue by exdx** [operator-framework/operator-lifecycle-manager#2672]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

Currently OLM emits a lot of unnecessary cache miss logs at the error level in the style of 
```
error="Operation cannot be fulfilled on catalogsources.operators.coreos.com \"operatorhubio-catalog\": the object has been modified; please apply your changes to the latest version and try again" id=OTXzH source=operatorhubio-catalog
```
which confuses admins and others looking at the OLM logs. It also greatly increases the volume of OLM logs which then affects  clients of OLM logs such as log aggregation/exporter tools. It's worth investigating whether there is a way to remove or tone down these logs in a way that does not change the sync behavior of OLM. 

**Environment**
* operator-lifecycle-manager version:

* Kubernetes version information:

* Kubernetes cluster kind: 

**Possible Solution**

**Additional context**

**Comment by exdx** [comment]
One possible solution lowering logs from the informer could be passing a different instance of the logger than the one that OLM generates on startup and fine-tuning it

**Comment by exdx** [comment]
Initial solution is to lower the log-level of this particular error in the queueinformer underlying this particular operator's queue. 

May be a symptom of underlying controller problems. 

Possible solution is generate a metric based on when this modified error occurs and then diagnose based on the number of occurrences.

**Comment by timflannagan** [comment]
@exdx Should this be closed now that https://github.com/operator-framework/operator-lifecycle-manager/pull/2631 has been merged for a while now?

**Comment by awgreene** [comment]
[This code](https://github.com/kubernetes/apimachinery/blob/080c0c77fab5f76acfa0c31e9e59411ecc861973/pkg/api/errors/errors.go#L544-L555) may allow us to identify whenever an update fails due to a conflict.
