### ISSUE TITLE
file in chart without extension does not pass helm v3 lint

### ISSUE THREAD

**Issue by Morriz** [operator-framework/operator-lifecycle-manager#2692]
## Bug Report

see `templates/image-references`

**What did you do?**
- download the `4.9` release
- helm lint the chart with default values

**What did you expect to see?**
Successful lint

**What did you see instead? Under which circumstances?**
A lint error:
```
[ERROR] templates/image-references: file extension '' not valid. Valid extensions are .yaml, .yml, .tpl, or .txt
```

**Environment**
* operator-lifecycle-manager version: `quay.io/operator-framework/olm:master`

The final images pulled are:
- `quay.io/operator-framework/olm@sha256:494ea7d8585e21d243f5956b408a34109c76d7425baa4160ed51c8a1521039f9`
- `quay.io/operatorhubio/catalog@sha256:c72e3082c811042587f357839745eef76c571eeb03bdacc25aa8dc41d9608f92`

* Kubernetes version information:

1.21

* Kubernetes cluster kind: 

**Possible Solution**
add `.yaml` extension

**Additional context**

**Comment by exdx** [comment]
Please follow-up if you have any additional questions or concerns.

**Comment by Morriz** [comment]
I can't believe this. My observation is still valid: the chart has a linting error.
