### ISSUE TITLE
golangci-lint check fails

### ISSUE THREAD

**Issue by georgettica** [operator-framework/operator-lifecycle-manager#2723]
## Bug Report

**What did you do?**

Use the latest version of olm in a fork

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

that the github actions (GHA) will pass

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

[the GHA fork action failed](https://github.com/georgettica/operator-lifecycle-manager/runs/5812109753?check_suite_focus=true) on linting

**Environment**
* operator-lifecycle-manager version:

N/A

* Kubernetes version information:

N/A

* Kubernetes cluster kind: 

N/A

**Possible Solution**
to set the golangci-lint version to go1.17
as of now there is a list linters that work with 1.18 but not all of them.

**Additional context**
[see this page for the status of the golangci-lint state](https://github.com/golangci/golangci-lint/issues/2649)

**Comment by timflannagan** [comment]
Thanks for the report - it looks like I forgot to link up this issue with the #2724 PR that bumps the golangci-lint action to a version that plays well with Go 1.17, so automation didn't automatically close this. The https://github.com/operator-framework/operator-lifecycle-manager/runs/5820704445?check_suite_focus=true action just passed (which ran against the master branch) so I'm going to close this out.
