### ISSUE TITLE
[flake] TestCARotation/ValidCert/SecretMissing/NewCertCreated unit test

### ISSUE THREAD

**Issue by exdx** [operator-framework/operator-lifecycle-manager#2773]
## Flaky Test Report
This test started flaking recently, pretty consistently. Relates to changes from #2752 

**Failure Log Link**
[Failure Log](put link here)
You can get the link by clicking on the line number in the job logs and copying the url from your browser.
https://github.com/operator-framework/operator-lifecycle-manager/runs/6375947720?check_suite_focus=true
**Relevant Failure Log**

--- FAIL: TestCARotation (0.45s)
    --- FAIL: TestCARotation/ValidCert/SecretMissing/NewCertCreated (0.15s)
        operator_test.go:5372: 
            	Error Trace:	operator_test.go:5372
            	Error:      	Not equal: 
            	            	expected: 1652208591
            	            	actual  : 1652208590
            	Test:       	TestCARotation/ValidCert/SecretMissing/NewCertCreated

**Comment by perdasilva** [comment]
OK, the root cause is due to us calculating the certificate and status times separately. Essentially, when a secret disappears, a new certificate is created, but this cannot be detected at the point where we calculate the status timestamps. So, the old ones are kept.
