### ISSUE TITLE
Installation fails on microk8s

### ISSUE THREAD

**Issue by joaomlneto** [operator-framework/operator-lifecycle-manager#2777]
## Bug Report

Operator Lifecycle Manager `install.sh` script fails to install on a new `microk8s` cluster on a clean Ubuntu 20.04 installation.

#### Some observations 
- The install script fails with `CSV "packageserver" failed to reach phase succeeded`.
- `kubectl get csv -n "olm" packageserver -o jsonpath='{.status.phase}'` returns `Installing`.
- ~~Additionally, CPU usage hangs at 100% (1 full CPU core).~~ (seems to be overall cluster CPU utilization; not tied to any container in particular)
- Persists even if we enable cluster add-ons `dns`, `storage`, `metallb`, `helm3`.
- Persists even after `microk8s`/machine reboots.

---

### Steps to reproduce: 
1. Get an instance in Hetzner Cloud (I got a 16-core, 32GB RAM, just in case…)
2. `apt update && apt upgrade -y && apt install snapd -y && snap install microk8s --classic && snap install kubectl --classic`
3. `mkdir ~/.kube && microk8s config > .kube/config`
4. Pick a version of OLM to install:
  - [v0.20.0](https://github.com/operator-framework/operator-lifecycle-manager/releases/tag/v0.20.0): `curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.20.0/install.sh | bash -s v0.20.0`
  - ~~[v0.21.1](https://github.com/operator-framework/operator-lifecycle-manager/releases/tag/v0.21.1): `curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.21.1/install.sh | bash -s v0.21.1`~~ This fails because of https://github.com/operator-framework/operator-lifecycle-manager/issues/2767
  - https://github.com/operator-framework/operator-lifecycle-manager/pull/2771: `curl -sL https://raw.githubusercontent.com/exdx/operator-lifecycle-manager/33e86c2850975a793e121b200476a95511179dc6/scripts/install.sh | bash -s v0.21.1`

#### Expected
```
# kubectl get csv -A
NAMESPACE   NAME            DISPLAY          VERSION   REPLACES   PHASE
olm         packageserver   Package Server   0.20.0               Succeeded
```
#### Actual Result
```
# curl -sL https://raw.githubusercontent.com/exdx/operator-lifecycle-manager/33e86c2850975a793e121b200476a95511179dc6/scripts/install.sh | bash -s v0.21.1
customresourcedefinition.apiextensions.k8s.io/catalogsources.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/installplans.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/olmconfigs.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/operatorconditions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/operatorgroups.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/operators.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/subscriptions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/catalogsources.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/installplans.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/olmconfigs.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/operatorconditions.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/operatorgroups.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/operators.operators.coreos.com condition met
customresourcedefinition.apiextensions.k8s.io/subscriptions.operators.coreos.com condition met
namespace/olm created
namespace/operators created
serviceaccount/olm-operator-serviceaccount created
clusterrole.rbac.authorization.k8s.io/system:controller:operator-lifecycle-manager created
clusterrolebinding.rbac.authorization.k8s.io/olm-operator-binding-olm created
olmconfig.operators.coreos.com/cluster created
deployment.apps/olm-operator created
deployment.apps/catalog-operator created
clusterrole.rbac.authorization.k8s.io/aggregate-olm-edit created
clusterrole.rbac.authorization.k8s.io/aggregate-olm-view created
operatorgroup.operators.coreos.com/global-operators created
operatorgroup.operators.coreos.com/olm-operators created
clusterserviceversion.operators.coreos.com/packageserver created
catalogsource.operators.coreos.com/operatorhubio-catalog created
Waiting for deployment "olm-operator" rollout to finish: 0 of 1 updated replicas are available...
deployment "olm-operator" successfully rolled out
Waiting for deployment "catalog-operator" rollout to finish: 0 of 1 updated replicas are available...
deployment "catalog-operator" successfully rolled out
Package server phase: Installing
CSV "packageserver" failed to reach phase succeeded
```
```
# kubectl get csv -A
NAMESPACE   NAME            DISPLAY          VERSION   REPLACES   PHASE
olm         packageserver   Package Server   0.20.0               Installing
```

**Environment**
* Kubernetes version information:
```
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.23.6-2+2a84a218e3cd52
```
(Checked `microk8s` version `v1.23` and `v1.24`)

* Kubernetes cluster kind: single-node `microk8s`

**Additional context**
Installing operators works fine, even if `packageserver` stays `Installing` (e.g. running `kubectl create -f https://operatorhub.io/install/strimzi-kafka-operator.yaml`)

**Comment by timflannagan** [comment]
@joaomlneto Awesome - should we close this out, or do you think this is worth documenting? We mainly dev/test on kind and OCP clusters, although we have a daily action that runs OLM's quickstart instructions on minikube clusters. It might be possible to also extend those tests to microk8s clusters, but it's unclear whether this is worth the extra maintenance over time.

**Comment by exdx** [comment]
@joaomlneto good to see that you got it working. This issue can serve as documentation for any other users that look to install OLM onto `microk8s`. They would have to enable RBAC on the cluster via `microk8s enable rbac` for packageserver to install successfully.
