### ISSUE TITLE
Tag v0.22.0

### ISSUE THREAD

**Issue by sathieu** [operator-framework/operator-lifecycle-manager#2812]
## Feature Request

**Is your feature request related to a problem? Please describe.**

v0.22.0 image was released (see [here](https://quay.io/repository/operator-framework/olm?tab=tags)), but there is no associated git tag.

**Describe the solution you'd like**

A git tag pointing to the relevant commit

**Comment by aemperador** [comment]
@sathieu there is a git tag here - https://github.com/operator-framework/operator-lifecycle-manager/tree/v0.22.0

**Comment by sathieu** [comment]
Thanks. CLosing.
