### ISSUE TITLE
Where is the subsititute for "operatorsource"

### ISSUE THREAD

**Issue by LronDC** [operator-framework/operator-lifecycle-manager#2854]
## Question

**What did you do?**
I searched old PRs and also the latest master, and noticed that `operatorsource` had been removed https://github.com/operator-framework/operator-lifecycle-manager/pull/651

**What did you expect to see?**
I want to know since `operatorsource` had been removed, how does OLM or Operator Framework connect to the outside or say online resources? Did `operatorsource` be somewhere else in Operator Framework?

**What did you see instead? Under which circumstances?**
I've also noticed that operator-marketplace added and removed `operatorsource` too.  I want to know the intention of doing so.

**Comment by dmesser** [comment]
`OperatorSource` served as an indirection of making operator's available to installs from a source like `CatalogSource`. `CatalogSource` is now the canonical API to bring collections of operators and their version history into the cluster.

The operator-marketplace concept was providing an additional layer of filtering what's available to install from a catalog.  User feedback was that this did not serve a particular use case and it was easier to just use `CatalogSource` directly. Hence the removal.

Did you have a use case for `OperatorSource` outside of that?

**Comment by LronDC** [comment]
`Did you have a use case for OperatorSource outside of that?`
Well, actually no. But I do like the possibility to have `an additional layer of filtering what's available to install from a catalog`.
So I was wondering.
Thanks for the explanations.
