### ISSUE TITLE
Why "packagemanifest.packages.operators.coreos.com" is allocated in all the namespaces?

### ISSUE THREAD

**Issue by marandalucas** [operator-framework/operator-lifecycle-manager#2932]
## Bug Report

**What did you do?**

_If we run the next command, We only see packagemanifest into the olm namespace._

```
kubectl get packagemanifest.packages.operators.coreos.com -A
olm         nfs-provisioner-operator                   Community Operators   3d
olm         ack-eks-controller                         Community Operators   3d
olm         sosivio                                    Community Operators   3d
.....
```

Now, if we run all the resources that we have in our customer namespace, also we can see that we have packagemanifests.
```
kubectl get-all -n pv-envtest100-a
packagemanifest.packages.operators.coreos.com/minio-operator                            pv-envtest100-a  3d     
packagemanifest.packages.operators.coreos.com/multicluster-operators-subscription       pv-envtest100-a  3d     
packagemanifest.packages.operators.coreos.com/dell-csm-operator                         pv-envtest100-a  3d     
....
...
```

- We already have implemented OLM in our GKE cluster.
- We are trying to implement Backups for GKE, but unfortunately, we got the error below recovering a customer namespace:

`[302/302] resources failed due to the same reason [KubeError]; e.g. resource [/pv-envtest100-a/packages.operators.coreos.com/PackageManifest/pcc-operator] restore failed: the server does not allow this method on the requested resource.`

NOTES:
- packagemanifest.packages.operators.coreos.com does not allow create actions (Backup for GKE wants to create packagemanifest when we are recovering a customer namespace, because of that we got the error).
- Backups for GKE is a new service in GCP, so there's no feature for excluding specific resources. We've got a meeting with them and they are considering adding a new feature for that purpose.

**Environment**
* operator-lifecycle-manager version:
olm.version: v0.22.0

* Kubernetes version information:
v1.24.9-gke.3200

* Kubernetes cluster kind: 
GKE

**Possible Solution**

**We'd like to don't see these resources in other namespaces because it causes issues in Backups for GKE.**

**Comment by awgreene** [comment]
Hello @marandalucas,

Requests against the PackageManifest resource are fulfilled by an api server, the response is generated and cached based on content available within CatalogSources on cluster. These resources are never stored in the object store and can't be created in the traditional sense. The only way to "create" a PackageManifest is to create a catalogSource with the new content that would result in a PackageManifest.

You should exclude these resources from being backed up.

**Comment by marandalucas** [comment]
Thank @awgreene, for your fast response. 

Unfortunately, the backup for GKE doesn't have exclusions. Hopefully, they'll release a new feature for it. :)
