### ISSUE TITLE
configure operator resources from the OperatorGroup

### ISSUE THREAD

**Issue by zfrhv** [operator-framework/operator-lifecycle-manager#2939]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Often many operators don't configure resources (limits/requests) on the operator deployment.
And modifying the CSV each time manually is a workaround.
Using LimitRange is not always possible because many operators dont support cluster wide installation and the application has to run in the same namespace.

**Describe the solution you'd like**
Same as the OperatorGroup can configure the default service account for the operator to run with and limit permission, I suggest to also add option to specify the resources for the operator.
The OperatorGroup may have option for the default resources values if the operator didnt configured any, or enforce the cpu+memory limits even if the operator already configured it. (basically same as LimitRange but only on the operator)

**Comment by tlwu2013** [comment]
OLM currently supports setting up how an Operator gets deployed via the config field in the [Subscription](https://github.com/operator-framework/olm-book/blob/master/docs/subscriptions.md) object.

Specially, the `resources` field defines [Resource Constraints](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container) for all the containers in the Pod created by OLM. See details in [Resources](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/subscription-config.md#resources) section.

**Comment by zfrhv** [comment]
I see,
I tried to use it, checked the csv and nothing changed, so i thought maybe its something else that i dont understand.

now I tried to use it again, and i see that the pod actually gets the configured resources from the sub.
Its actually better.
thank you!
