### ISSUE TITLE
Missing ARM version for quay.io/operator-framework/upstream-opm-builder

### ISSUE THREAD

**Issue by OGKevin** [operator-framework/operator-lifecycle-manager#2967]
## Bug Report

**What did you do?**

ARM image for `quay.io/operator-framework/upstream-opm-builder`.

The operator creates jobs with this image, however it has not been build in a while as reported here:
https://github.com/operator-framework/operator-lifecycle-manager/issues/1138#issuecomment-1468826014

Where is the source of this build? As the link to the repo on https://quay.io/repository/operator-framework/upstream-opm-builder?tab=info seems to not work either. 

I would be happy to help build an ARM version of this image.

**Comment by grokspawn** [comment]
upstream-opm-builder has been deprecated for about a year, when `opm` from the `operator-registry` repo started releasing via goreleaser in order to support multiple architectures.  ARM versions are available at quay.io/operator-framework/opm.

**Comment by OGKevin** [comment]
hmm well there is hard-coded image name somewhere that is outdated. 
As

> Looks like the job pod creates a container using quay.io/operator-framework/upstream-opm-builder:latest and that was built in February 2022 (over a year old at this point)

Is still happening today when following the installation instructions 😕 

e.g. 
``` bash
curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.24.0/install.sh | bash -s v0.24.0
```
