### ISSUE TITLE
Why olm checks all CatalogSource objects health when apply operators by Subscription

### ISSUE THREAD

**Issue by sqwaseda** [operator-framework/operator-lifecycle-manager#3009]
## Bug Report

**What did you do?**
1. two CatalogSource objects in the same namespace
2. one CatalogSource is healthy, another one is unhealthy
3. apply an operator in the healthy CatalogSource by create Subscription object

**What did you expect to see?**
apply the operator in the healthy CatalogSource successfully. Because in the Subscription object, we specify the healthy Catalogsource object by name and namespace
![image](https://github.com/operator-framework/operator-lifecycle-manager/assets/45985127/c3e163e1-da94-4a02-8697-3e833f9bbc1c)

![image](https://github.com/operator-framework/operator-lifecycle-manager/assets/45985127/581dca19-bc65-4240-a1e1-1dfaa22dae33)

**What did you see instead? Under which circumstances?**
1. operator apply failed
2. Subscription's condition unhealthy, message is: 
` [failed to populate resolver cache from source community-operators/openshift-marketplace: failed to list bundles: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.30.96.177:50051: connect: connection refused", failed to populate resolver cache from source certified-operators/openshift-marketplace: failed to list bundles: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.30.130.63:50051: connect: connection refused", failed to populate resolver cache from source redhat-marketplace/openshift-marketplace: failed to list bundles: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.30.76.30:50051: connect: connection refused", failed to populate resolver cache from source redhat-operators/openshift-marketplace: failed to list bundles: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.30.217.141:50051: connect: connection refused"]`
3. It seems the unhealthy CatalogSource effects the deployment of the healthy CatalogSource
4. We view the codes. When reconcile the Subscription objects, it will check all the CatalogSource Objects in the same namespace of the CatalogSoure  which the Subscription is subscribed

**Comment by kevinrizza** [comment]
This isn't a bug, it's an intentional design decision. OLM considers the context of all the catalogs that are available in the context of the namespace (so, all the catalog sources in the namespace + the global catalog sources) in order to get a deterministic result when resolving all the operators in a namespace and their potential dependencies. When OLM installs an operator, it considers the potential context of everything installed in a namespace, and fails to resolve if it can't.

**Comment by sqwaseda** [comment]
@kevinrizza thanks for taking the time and providing this valuable feedback.

> This isn't a bug, it's an intentional design decision. OLM considers the context of all the catalogs that are available in the context of the namespace (so, all the catalog sources in the namespace + the global catalog sources) in order to get a deterministic result when resolving all the operators in a namespace and their potential dependencies. When OLM installs an operator, it considers the potential context of everything installed in a namespace, and fails to resolve if it can't.

**Comment by awgreene** [comment]
I'm going to close this issue as Kevin has addressed the question and the [official documentation](https://olm.operatorframework.io/docs/troubleshooting/subscription/#why-does-a-single-failing-subscription-cause-all-subscriptions-in-a-namespace-to-fail) discusses this concept as well. Thanks for using OLM @sqwaseda.
