### ISSUE TITLE
InstallMode `OwnNamespace` should be allowed in case Conversion Webhook is also used

### ISSUE THREAD

**Issue by 0sewa0** [operator-framework/operator-lifecycle-manager#3053]
## Feature Request

**Is your feature request related to a problem? Please describe.**
If I want to publish an operator that has a Conversion Webhook BUT I do not want to have it in `AllNamespaces` as that will cause the operator's `roles` to be converted into `clusterRoles`, which causes concerns from users that "the operator requests too many permissions". 
It's a valid concern as the operator wouldn't even need those permissions.

**Describe the solution you'd like**
Either:
- Allow `OwnNamespace` install-mode in case a Conversion Webhook is also provided
- Provide a way to opt-out of the `roles` to `clusterRoles` conversion in case `AllNamespaces` install-mode is used

**Comment by joelanford** [comment]
Hi @0sewa0!

The reason that OLM requires operators that use conversion webhooks to be installed in `AllNamespaces` mode is that conversion webhooks are global and called for all instances of a CRD, so there can be only one installation of the operator that provides a conversion webhook. 

When installed in `AllNamespaces` mode, OLM needs to give the operator permission to operate in all namespaces, hence the promotion of roles to cluster roles.

However, we do understand that there are limitations with this approach, but they are not easily fixable from an architecture perspective they want OLM (v0) is designed. We are actively working on a new architecture (we're calling it OLMv1), where fine-grained RBAC will be supported for both:
- [users of APIs provided by operators](https://github.com/operator-framework/operator-controller/issues/383)
- [operators that need to permission to read/write other objects.](https://github.com/operator-framework/operator-controller/issues/384)

You can track our progress for OLMv1 in the operator-controller repository, here: https://github.com/operator-framework/operator-controller

We have an OLMv1 [GitHub project view](https://github.com/orgs/operator-framework/projects/8/views/26) as well, if you want to follow along on the progress and see what work is planned.

**Comment by joelanford** [comment]
I'm going to close this issue, since I think we've covered this feature request in our OLMv1 plans and we are not planning to implement this in OLMv0.
