### ISSUE TITLE
Add 'deprecated' condition to Subscription status

### ISSUE THREAD

**Issue by dtfranz** [operator-framework/operator-lifecycle-manager#3099]
As an OLM user, I would like to know when a Subscription has a deprecated Operator installed.

Acceptance Criteria:

- When the catalog entry used by a Subscription is marked as "deprecated", the "Deprecated" condition will be added to the Subscription status.
- Tests are written

**Comment by awgreene** [comment]
This is closely related to the tests defined in https://github.com/operator-framework/operator-lifecycle-manager/issues/3103
