### ISSUE TITLE
Augment OLM e2e to ensure Subscription API contains deprecation info

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-lifecycle-manager#3103]
### Background

We're working on a feature that would enable operator authors to deprecate and provide deprecation messages for packages, channels, and bundles via a new FBC type.

We are working in the operator-registry repository to define the FBC schema, update the GRPC schema, and implement the necessary functionality to parse, validate, and propagate that information into the GRPC responses sent to catalog clients.

OLM has two catalogs clients: the package server, which provides the `PackageManifest` API and provides visibility into the catalog contents, and the catalog-operator, which reconciles `Subscription` which ultimately results in the installation and lifecycling of operators on a cluster. We need to propagate the deprecation information to both APIs

## Request

Let's implement (or update an existing) e2e test to ensure that we correctly propagate all deprecation information into the `Subscription` object. The main test criteria are:
- If `spec.name` references a deprecated package, the subscription status includes information about the package deprecation
- If `spec.channel` references a deprecated channel, the subscription status includes information about the channel deprecation
- If `status.installedCSV` references a deprecated bundle, the subscription status includes information about the bundle deprecation.

**Comment by dtfranz** [comment]
Closed in #3106
