### ISSUE TITLE
CSV not removed after deletion when not in Success/Terminal state.

### ISSUE THREAD

**Issue by tmshort** [operator-framework/operator-lifecycle-manager#3130]
## Bug Report

It appears that CSVs may not be deleted when they are "deleted". The CSV remains after a deletion attempt, which means that all resources associated with (owned by) the CSV remain. 

See #3108

**What did you do?**
Happens during e2e (Install Plan creation with permission), it's a flake.

When a CSV is not in a (e.g.) success state, and it's deleted, it's not actually deleted.

**What did you expect to see?**
When a CSV is deleted, the CSV is deleted regardless of the state it's in.

**What did you see instead? Under which circumstances?**
When the CSV is deleted, it remains.

**Environment**
* operator-lifecycle-manager version: master
* e2e tests

* Kubernetes version information: e2e test (most recent)

* Kubernetes cluster kind:  openshift and kind

**Comment by stevekuznetsov** [comment]
This does not really have to do with the state that the CSV is in. The controller, as written today, is edge-driven. If it ever misses a deletion event, since there is no finalizer, you are not guaranteed that the clean-up code runs.

**Comment by tmshort** [comment]
What appears to be happening is that the CSV is being re-created by the Subscription, as the UIDs are different. With some of the performance enhancements, this is occurring a lot quicker now.
