### ISSUE TITLE
make run-local is broken

### ISSUE THREAD

**Issue by sslavic** [operator-framework/operator-lifecycle-manager#366]
I tried to follow https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/install/install.md#run-locally-with-minikube and got:
```
$ make run-local
./scripts/package-release.sh  deploy/tectonic-alm-operator/manifests/ deploy/tectonic-alm-operator/values.yaml
Usage: ./scripts/package-release.sh semver chart values
* semver: semver-formatted version for this package
* chart: the directory to output the chart
* values: the values file
make: *** [tectonic-release] Error 1
```

**Comment by ecordell** [comment]
Hi @sslavic - you need to pass a version string to `run-local` like this: `make ver=0.5.0 run-local`

Let me know if that doesn't fix the problem!

**Comment by fiftoine** [comment]
I just resolved it before seeing your comment ;-) Thanks @ecordell 

Maybe adding this info to the readme file would be nice.

**Comment by sslavic** [comment]
Before and after this change, running `make run-local` pollutes local git repo state - modifies `deploy/aos-olm/playbook/private/roles/olm` file, and also generates some files which are not in version control and are also not ignored. Wish it would leave the repo unmodified.
