### ISSUE TITLE
Typos in architecture doc

### ISSUE THREAD

**Issue by mhrivnak** [operator-framework/operator-lifecycle-manager#376]
The `architecture.md` doc includes some typos. In the last paragraph "Catalog (Registry) Design":

"Within a package, channels which point to a particular CSV." _This is not a valid sentence. Perhaps the word "which" should be removed? Or maybe the rest of the sentence is missing?_

"Because CSVs explicitly reference the CSV that they replace, a package manifest provides the catalog Operator needs to update a CSV to the latest version in a channel (stepping through each intermediate version)." _This sentence appears to merge into some other sentence around the words "provides the catalog Operator needs to update". I don't have enough domain knowledge to suggest a fix._

**Comment by ecordell** [comment]
Thanks for catching this! Made a PR to fix the issues you found.
