### ISSUE TITLE
`The ConfigMap "rh-operators" is invalid` while installing on upstream k8s

### ISSUE THREAD

**Issue by darkowlzz** [operator-framework/operator-lifecycle-manager#467]
Following the instructions at [Install the latest released version of OLM for upstream Kubernetes](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/install/install.md#install-the-latest-released-version-of-olm-for-upstream-kubernetes) on k8s 1.11, I get the following message:
```
$ kubectl apply -f deploy/upstream/manifests/latest/
clusterrole.rbac.authorization.k8s.io/system:controller:operator-lifecycle-manager configured
serviceaccount/olm-operator-serviceaccount unchanged
clusterrolebinding.rbac.authorization.k8s.io/olm-operator-binding-kube-system configured
customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/catalogsources.operators.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/installplans.operators.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/subscriptions.operators.coreos.com configured
catalogsource.operators.coreos.com/rh-operators unchanged
deployment.apps/olm-operator unchanged
deployment.apps/catalog-operator unchanged
clusterrole.rbac.authorization.k8s.io/aggregate-olm-edit configured
clusterrole.rbac.authorization.k8s.io/aggregate-olm-view configured
apiservice.apiregistration.k8s.io/v1alpha1.packages.apps.redhat.com configured
clusterrolebinding.rbac.authorization.k8s.io/packagemanifest:system:auth-delegator configured
rolebinding.rbac.authorization.k8s.io/packagemanifest-auth-reader unchanged
clusterrolebinding.rbac.authorization.k8s.io/packagemanifest-view configured
clusterrolebinding.rbac.authorization.k8s.io/package-apiserver-clusterrolebinding configured
secret/package-server-certs unchanged
deployment.apps/package-server unchanged
service/package-server unchanged
The ConfigMap "rh-operators" is invalid: metadata.annotations: Too long: must have at most 262144 characters
```

Is there a workaround for annotations length limit?

**Comment by darkowlzz** [comment]
@ecordell thanks! that worked.

Also, I was following the Getting Started Guide's [Deploy the Operator](https://github.com/operator-framework/getting-started#manage-the-operator-using-the-operator-lifecycle-manager) section and tried to install memcachedoperator csv after deploying OLM, but I get this error.
```
$ kubectl apply -f memcachedoperator.0.0.1.csv.yaml
error: unable to recognize "memcachedoperator.0.0.1.csv.yaml": no matches for kind "ClusterServiceVersion-v1" in version "app.coreos.com/v1alpha1"
```
I'm not aware of much of the internals of OLM at the moment. Some hint would be great.

**Comment by ecordell** [comment]
@darkowlzz Great!

That example is unfortunately a little out of date - but I'm betting that if you just remove the `-v1` prefix from the example types, it will still work. (i.e. `ClusterServiceVersion-v1` -> `ClusterServiceVersion`)

Closing since your original issue is fixed - please open an issue on the `Getting Started` repo if you have more problems with that.
