### ISSUE TITLE
The `--service-catalog` clusterup option is invalid for OS 3.10+

### ISSUE THREAD

**Issue by jcrossley3** [operator-framework/operator-lifecycle-manager#468]
This causes the `scripts/build-local-shift.sh` to fail. I'm not sure of the best way to determine which flag value to pass, but for 3.10 the syntax should be: 

  `--extra-clusterup-flags "--enable=*,service-catalog"`

**Comment by ecordell** [comment]
That was only needed for testing the olm-broker, which now lives in a separate repo: https://github.com/operator-framework/olm-broker

We can just remove it; the service-catalog integration should be tested by that other repo, not this one.

**Comment by jcrossley3** [comment]
I guess I misinterpreted the `install` doc as it being The Right Way to install OLM on minishift. What is the proper way?

**Comment by njhale** [comment]
Also, OLM versions 0.6.0 and 0.7.0 require Kubernetes v1.11 and I believe `minishift` v3.10 is at Kubernetes v1.10. If you can, I would try running the latest `minikube`. `scripts/build_local.sh` should start `minikube` with the appropriate flags and build the OLM images.
