### ISSUE TITLE
Tag "master" of quay.io/coreos/package-server does not exist

### ISSUE THREAD

**Issue by LiliC** [operator-framework/operator-lifecycle-manager#471]
quay.io/coreos/package-server in the `0.7.0.` manifest file uses `master` tag which does not exist, which makes the deploy fail.
https://github.com/operator-framework/operator-lifecycle-manager/blob/170be9c08533b32f14d49e9829055b40af15389e/deploy/upstream/manifests/0.7.0/22-packageserver.yaml#L108

**Comment by ecordell** [comment]
I opened #472 to fix the 0.7.0 release manifests.

Just fyi, that packages server is somewhat of a "preview" feature for now (it doesn't yet support `watch` apis, and console hasn't been updated to use it). If it causes problems for you, you can safely delete the deployment for now.

**Comment by LiliC** [comment]
@ecordell Thanks for the quick fix!
