### ISSUE TITLE
Installation requirements missing

### ISSUE THREAD

**Issue by alexxa** [operator-framework/operator-lifecycle-manager#481]
I don't see any Installation requirements in [1] or [2]. Or "Tested on" info. For example, will it work with any Kubernetes and OpenShift cluster? 

[1] https://github.com/operator-framework/operator-lifecycle-manager/blob/master/README.md
[2] https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/install/install.md

**Comment by alexxa** [comment]
For example, 
```
curl https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/scripts/run_console_local.sh | bash -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   969  100   969    0     0   2634      0 --:--:-- --:--:-- --:--:--  2640
bash: line 4: jq: command not found
bash: line 4: jq: command not found
bash: line 4: jq: command not found
bash: line 4: jq: command not found
```

**Comment by chancez** [comment]
Needs kube 1.11 at least on latest as well. Uses the status subresource for updates.

**Comment by camilamacedo86** [comment]
Do you mean the minikube? Could you be more specific? If the user is trying to install it with OCP then is the kube already installed? Why the issue was closed if this info still missing from the README?

**Comment by chancez** [comment]
I mean, whatever kubernetes cluster you're using, and it's API version.

**Comment by ecordell** [comment]
Prereqs are now in the readme and the install instructions
