### ISSUE TITLE
olm-operator local run expects `master` image tag which is unavailable

### ISSUE THREAD

**Issue by aditya-konarde** [operator-framework/operator-lifecycle-manager#529]
## Environment:
Using `run make-local-shift`, 

## Issue: 
Saw that the `olm-operator` pod went into ImagePullBackOff, failing to pull the image `quay.io/coreos/olm` with the `master` tag. 

## Workaround
I was able to fix this by editing the pod definition to use one of the existing tags, for example `0.7.3`. 

Looks like this needs to be fixed somewhere in the makefile or bringup scripts. Please feel free to let me know if any further details are needed. :)

**Comment by rhuss** [comment]
See #537 which should fix that issue.
