### ISSUE TITLE
There seems to be no proper way to uninstall

### ISSUE THREAD

**Issue by ctron** [operator-framework/operator-lifecycle-manager#557]
Installing OLM is easy. But it seems there is no out-of-the-box way to completely uninstall it again.

**Comment by ecordell** [comment]
We haven't documented this, so I'll leave this issue open until we do (or have a better solution):

1. OLM installs running components into a namespace. For openshift, it's `openshift-operator-lifecycle-manager`. Deleting this namespace will remove all OLM components.
2. OLM manages the types defined by its CRDs. Currently these are `Subscription`, `InstallPlan`, ClusterServiceVersion`, and `OperatorGroup`. If you delete those CRDs, all instances across the cluster will be deleted. All other resources OLM manages will then be cleaned up (they are ownerref'd to some OLM CR)

**Comment by njhale** [comment]
Closing since we now have [docs for uninstalling](https://github.com/operator-framework/olm-book/blob/master/docs/uninstall-an-operator.md#how-to-uninstall-an-operator).

**Comment by hangyan** [comment]
> [](https://github.com/operator-framework/olm-book/blob/master/docs/uninstall-an-operator.md#how-to-uninstall-an-operator).

The link is wrong, it should be https://github.com/operator-framework/olm-book/blob/master/docs/uninstall-olm.md

**Comment by hangyan** [comment]
> Closing since we now have [docs for uninstalling](https://github.com/operator-framework/olm-book/blob/master/docs/uninstall-an-operator.md#how-to-uninstall-an-operator).

The link is wrong, it should be https://github.com/operator-framework/olm-book/blob/master/docs/uninstall-olm.md
