### ISSUE TITLE
OLM compatibility with cluster monitoring Operator 

### ISSUE THREAD

**Issue by nabbdl** [operator-framework/operator-lifecycle-manager#581]
I am currently running an OKD 3.11  with cluster monitoring operator installed which leverage both Prometheus and Alertmanager Operator. On the OKD documentation it is said that the « cluster monitoring operator » is dedicated to monitor the cluster itself and if we need to monitor applications we have to use OLM
« Users interested in leveraging Prometheus for application monitoring on OpenShift should consider using OLM to easily deploy a Prometheus Operator and setup new Prometheus instances to monitor and alert on their applications ».
As cluster-monitoring-operator already provide « Prometheus operator » I was wondering if it will lead to issues by installing both OLM and cluster monitoring.
And in case of it is possible to use those two component, the Prometheus application instance will have to connect to the Alertmanager brought by cluster monitoring solutions which is in a dedicated namespace. Is it secure to allow network communications to the « openshiht-monitoring » namespace ?

**Comment by ecordell** [comment]
Hi @nabbdl - 

In 3.11, OLM installs namespace-scoped prometheus operators that you may use. This runs a prometheus operator that only watches its own namespace for prometheus CRDs, and operators over them in that one namespace. It is safe to install prometheus operator from OLM while also using cluster-monitoring-operator.
