### ISSUE TITLE
Non operator-sdk operators

### ISSUE THREAD

**Issue by smanpathak** [operator-framework/operator-lifecycle-manager#610]
To enable a new operator, the admin needs to
1. Install CRD and RBAC for that operator
2. Enable subscription.
To simplify this, can we have the 
1 catalog/OLM operator install CRD once an install plan is executed?

Many operators out there install CRDs on startup and don't have a separate CRD yaml. Is there a guide on how to use them with OLM?

**Comment by ecordell** [comment]
Hi @smanpathak 

To clarify - if you are creating a `Subscription`, then CRDs and RBAC will be configured automatically

> Many operators out there install CRDs on startup and don't have a separate CRD yaml. Is there a guide on how to use them with OLM?

There's not a way to do that directly - however, for any operator that creates CRDs on startup, it would not be hard to modify them to check for the existence of the CRD on startup as well. The operator should handle the existence gracefully anyone (for example, if the pod is rescheduled and must restart). Operators written like this can be easily packaged by OLM.

Thanks!
