### ISSUE TITLE
change catalog operator default namespace

### ISSUE THREAD

**Issue by smanpathak** [operator-framework/operator-lifecycle-manager#627]
currently it comes up expecting tectonic-system. There is no such namespace when you deploy the operator from git. Passing -namespace flag works, but this namespace is nowhere in the documentation.

**Comment by ecordell** [comment]
Hi @smanpathak - thanks for the report!

I agree that we should change the default namespace (`tectonic-system` is no longer a sensible default). 

None of the deploy artifacts that we build use the default, though - we set it explicitly. For example, https://github.com/operator-framework/operator-lifecycle-manager/tree/master/deploy/upstream/manifests/0.8.0 will create an `olm` namespace and the deploy OLM into that namespace.

**Comment by njhale** [comment]
Closing because the catalog-operator's default namespace has been changed - and as Evan mentioned, the namespace resource exists in our deploy manifests.
