### ISSUE TITLE
README links to CRDs, Descriptors, and Packages are broken

### ISSUE THREAD

**Issue by ron1** [operator-framework/operator-lifecycle-manager#694]
README links to CRDs, Descriptors, and Packages are broken now that rh-operators are no longer included in this git repo.

**Comment by njhale** [comment]
@ron1 closing this because your PR ([#695](https://github.com/operator-framework/operator-lifecycle-manager/pull/695)) that addresses this merged.

**Comment by njhale** [comment]
@ron1 closing this because your PR ([#695](https://github.com/operator-framework/operator-lifecycle-manager/pull/695)) that addresses this merged.
