### ISSUE TITLE
How to enable all workspaces so that OLM watches them?

### ISSUE THREAD

**Issue by ghost** [operator-framework/operator-lifecycle-manager#698]
I have not found any info on how to enable all workspaces to be watched by OLM. Or particular workspaces. The issue I am having that that in 4.0 by default only openshift-operators namespace is watched. But I cannot run the operator and resources it creates in this namespace due to certain reasons.

Is there a doc on how to enable a particular workspace in OLM?

**Comment by njhale** [comment]
@eivantsov By default, OLM watches all namespaces in OpenShift 4.0. As of now, a Subscription must exist in a namespace with CatalogSources that contain its dependencies (or they are available in the "global catalog" namespace, `openshift-operator-lifecycle-manager`). Additionally, a CSV requires a supported `OperatorGroup` be present in its namespace to provide some minimal multi-tenancy configuration. By supported, I mean that [the CSV's `InstallModes` must match the OperatorGroup's configuration](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/building-your-csv.md#operator-metadata).

If you have a CatalogSource that contains your operator dependencies, I suggest:
* Creating it in the namespace you want to install your operator in.
* Create an OperatorGroup that will support your CSV's InstallModes in that namespace.
* Creating a Subscription that targets your CSV and CatalogSource in that namespace.

**Comment by eivantsov** [comment]
@njhale thanks, that's helpful.  Perhaps you can suggest configuration for the following use case:

1. The operator is available in OperatorHub. 
2. I need this operator to be only installed in a particular namespace (say, an admin creates a namespace and an `OperatorGroup` in it)
3. I **do not** want the installed Operator to be copied to other namespaces once installed.

If in `InstallModes` I set:

```
        installModes:
          - supported: true
            type: OwnNamespace
          - supported: true
            type: SingleNamespace
          - supported: false
            type: MultiNamespace
          - supported: false
            type: AllNamespaces
```

Will I be able to achieve the above goals? The idea is to make the Operator admin only, since once installed, it will provision resources that will be available cluster wide anyway, and user won't need to do anything but click a route link to start using the service.

**Comment by njhale** [comment]
@eivantsov Yes, your InstallModes look correct - you should only need to create an OperatorGroup set to select its own namespace and tell OperatorHub to generate a new CatalogSource containing your operator in your OperatorGroup namespace. I'm not sure if OperatorHub is configured to watch all namespaces, but it it is I'm pretty sure this is achieved by creating a CatalogSourceConfig in the `operator-marketplace` namespace. From what I remember, this CatalogSourceConfig should select both your operator's package and dependent packages as well as the namespace you want the CatalogSource to be generated in (your OperatorGroup's namespace).

**Comment by aravindhp** [comment]
>I'm not sure if OperatorHub is configured to watch all namespaces,
OperatorHub only watches the `operator-marketplace` namespace. 

>From what I remember, this CatalogSourceConfig should select both your operator's package and dependent packages as well as the namespace you want the CatalogSource to be generated in (your OperatorGroup's namespace).
Confirming that this indeed the case. `targetNamespace` in the `CatalogSourceConfig` should be set to the namespace you want the `CatalogSource` to be generated in. This is also the namespace where you need to create the `Subscription` object for your operator.

**Comment by eivantsov** [comment]
@njhale @aravindhp I gave it a try with the above `InstallModes`.

1. oc create new-project eclipse-che
2. oc apply -f operatorgroup.yaml -n=eclipse-che

```
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: global-operators
```
3. Installed the operator from Operator Hub in eclipse-che namespace. The installation failed with:

![image](https://user-images.githubusercontent.com/5337267/52580067-3db39d00-2e30-11e9-9da1-ca90cb302049.png)

4. I can see that the installed operator showed up in all namespaces as failed:

![image](https://user-images.githubusercontent.com/5337267/52579953-fb8a5b80-2e2f-11e9-9beb-1e17e5b08053.png)

![image](https://user-images.githubusercontent.com/5337267/52580110-5a4fd500-2e30-11e9-9128-3db5b0c2bec3.png)

**Comment by njhale** [comment]
It looks like the operator was not actually installed. There should be no deployment for your operator running in the `eclipse-che` namespace. While the copied message is not all that helpful, the parent CSV is giving the correct failure message: "AllNamespaces InstallModeType not supported...". Which makes sense given that you created a global operatorgroup (omitting targetNamespaces or selector yields a global operatorgroup):
```
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: global-operators
```
And your CSV __does not__ support all namespaces:
```
installModes:
          .
          .
          .
          - supported: false
            type: AllNamespaces
```

I suggest updating your operatorgroup:
```
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: che-group
  namespace: eclipse-che
spec:
  targetNamespaces:
  - eclipse-che
```

**Comment by eivantsov** [comment]
@njhale thanks - that was it. I almost got to the stage of looking for OperatorGroup spec somewhere :)
