### ISSUE TITLE
Subscription stuck at Upgrading

### ISSUE THREAD

**Issue by eivantsov** [operator-framework/operator-lifecycle-manager#700]
I have installed OpenShift 4.0 (installer v0.11.0)

Luckily in this version OperatorHub console page is fixed, and I can see Operators.

However, upon installing an operator, a subscription is created, however, it is stuck at Upgrading phase, no matter what upgrade policy is chosen.

This happens to RH, certified and community operators, as well as the one I have added myself (by editing OperatorSource for community operators)

![image](https://user-images.githubusercontent.com/5337267/52196127-5259c900-2863-11e9-999c-c2360288c45a.png)
![image](https://user-images.githubusercontent.com/5337267/52196571-027c0180-2865-11e9-9e5a-72afa8565a51.png)

Which logs may I look at to try to figure out what's happening?

Sometimes, it takes 10-20 mins for status to become up-to-date.

**Comment by njhale** [comment]
@eivantsov When you first create a `Subscription`, an `InstallPlan` resource should be generated. You should be able run `kubectl -n openshift-operators get installplans ` to see if any have been created. You can also check if any CSVs have been created in openshift-operators by running `kubectl -n openshift-operators get csvs`.

**Comment by eivantsov** [comment]
@njhale thanks

somehow, I have got 1000s of install plans - `oc delete --all installplans -n=openshift-operators` is deleting them 10 mins already :) Not sure how I ended up with that many installplans objects. Re-provisioning a cluster sounds like the best way for me to proceed.

**Comment by eivantsov** [comment]
@njhale now on a fresh cluster, it worked for my custom operator.

Now, I have installed Prometheus operator, and this time status is unknown. No `installplan` is created at all

**Comment by njhale** [comment]
> @njhale thanks
> 
> somehow, I have got 1000s of install plans - `oc delete --all installplans -n=openshift-operators` is deleting them 10 mins already :) Not sure how I ended up with that many installplans objects. Re-provisioning a cluster sounds like the best way for me to proceed.

We merged a fix for this in OLM though I'm not sure it's made its way to the installer yet. You could run one of the `oc admin release` commands to figure out what OLM images are included.

> Now, I have installed Prometheus operator, and this time status is unknown. No `installplan` is created at all. There is no ClusterServiceVersion too.

Could you run `oc get packagemanifests -n openshift-operators -o yaml` ?

Also - how quickly did you generate the Subscription after creating the CatalogSource? Were they create at the same time?

**Comment by ecordell** [comment]
This bug has been fixed and is available in all of the latest releases (upstream and ocp). Closing, but feel free to re-open if there's still an issue somewhere.
