### ISSUE TITLE
Link to example CSVs is incorrect

### ISSUE THREAD

**Issue by jarcher** [operator-framework/operator-lifecycle-manager#737]
examples of CSV files are stored in Github link is incorrect...  current pointing to  https://github.com/operator-framework/operator-lifecycle-manager/tree/master/deploy/chart/catalog_resources/rh-operators

perhaps should point to

https://github.com/operator-framework/operator-lifecycle-manager/tree/4cd7c2e65e875241313b38e30b77249ac22e6066/vendor/github.com

**Comment by njhale** [comment]
@jarcher thanks for pointing this out! The [link](https://github.com/operator-framework/operator-lifecycle-manager/tree/4cd7c2e65e875241313b38e30b77249ac22e6066/vendor/github.com) you provided as a suggestion seems to just point to our top-level vendor directory. 

As an alternative, I think the [CSVs in the community-operators repo](https://github.com/operator-framework/community-operators/tree/master/community-operators) could serve as good examples.

Please let me know what you think.

**Comment by ecordell** [comment]
I think we've fixed up our links now - thanks!
