### ISSUE TITLE
Add 'operatorgroups' to edit and view clusterroles

### ISSUE THREAD

**Issue by aweiteka** [operator-framework/operator-lifecycle-manager#743]
Access to 'operatorgroups' resources is missing from clusterroles `aggregated-olm-edit` and `aggregated-olm-view`.

related to #742 

/cc @jewzaam

**Comment by ecordell** [comment]
We added operatorgroup get/list/watch to those roles, but not any of the write verbs. It requires higher-than-namespace-admin privileges to create an operatorgroup (because OperatorGroups target other namespaces and control how extensions are installed into the control plane)
