### ISSUE TITLE
Upstream quickstart and latest manifests should deploy same OLM image

### ISSUE THREAD

**Issue by ron1** [operator-framework/operator-lifecycle-manager#747]
Upstream quickstart (https://github.com/operator-framework/operator-lifecycle-manager/blob/master/deploy/upstream/quickstart/olm.yaml) deploys OLM image quay.io/openshift/origin-operator-lifecycle-manager:latest while Upstream manifests (https://github.com/operator-framework/operator-lifecycle-manager/blob/master/deploy/upstream/manifests/0.8.1/0000_50_olm_06-olm-operator.deployment.yaml) deploys OLM image quay.io/coreos/olm@sha256:995a181839f301585a0e115c083619b6d73812c58a8444d7b13b8e407010325f.

These two installation methods should be consistent and deploy the same images.

**Comment by njhale** [comment]
@ron1 Thanks for reporting! #752 and #771 resolve this issue. Closing this out.
