### ISSUE TITLE
Support for installing StatefulSets and PersistenVolumeClaims

### ISSUE THREAD

**Issue by calind** [operator-framework/operator-lifecycle-manager#767]
We are developing an operator (https://github.com/presslabs/mysql-operator) wich relies on stateful component (https://github.com/github/orchestrator).

Is there a way to describe such an operator using CSV? As far as I can tell, operators can only be described using deployments. For our case it would be very usefull to be able to use StatefulSets.

**Comment by ecordell** [comment]
Thanks for the feature request, @calind. We plan to support StatefulSets and Deamonsets in addition to deployments. Thanks for providing a good example operator to target for that feature.

**Comment by awgreene** [comment]
Closing this in favor of https://github.com/operator-framework/operator-lifecycle-manager/issues/1996.
