### ISSUE TITLE
Pull configmap-operator-registry from quay org "operator-framework" not "operatorframework" in 0.8.1 and master

### ISSUE THREAD

**Issue by ron1** [operator-framework/operator-lifecycle-manager#779]
Manifest https://github.com/operator-framework/operator-lifecycle-manager/blob/5019602532c5cd322815533674836b28d4308d78/manifests/0000_50_olm_07-catalog-operator.deployment.yaml#L28 pulls configmap-operator-registry image from quay org "operatorframework". Instead it should pull the image from organization "operator-framework" with a hyphen. This change should be at least applied to release 0.8.1 and master.

**Comment by njhale** [comment]
@ron1 Thanks for finding this! We'll get to this shortly.

**Comment by ron1** [comment]
Also consider at least relying on a sha-tag of that image as opposed to relying on the latest tag, especially for the 0.8.1 release.

**Comment by ecordell** [comment]
This is fixed in the chart and will be available when we cut the next release. Thanks for the report!

**Comment by ecordell** [comment]
Fixed in the latest releases. See: https://github.com/operator-framework/operator-lifecycle-manager/releases/tag/0.10.0
