### ISSUE TITLE
(doc) Link in the installation guide is not working

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lifecycle-manager#783]
## WHAT:

The link <https://github.com/operator-framework/operator-lifecycle-manager/blob/master/deploy/tectonic-alm-operator/values.yaml> is not working. 

## WHERE: 
https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/install/install.md

<img width="960" alt="Screenshot 2019-06-09 at 06 07 14" src="https://user-images.githubusercontent.com/7708031/59155243-eab7c280-8a7c-11e9-9f6a-5b78f20053ed.png">

**Comment by ecordell** [comment]
Our install docs should be up to snuff now. Thanks!
