### ISSUE TITLE
Unable to see operators after install/deploy the OML by following the installation guide

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lifecycle-manager#784]
## WHAT: 
Unable to see operators after install/deploy the OML by following the installation guide
Ref: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/install/install.md

## What was my expectation? 

After following it I would expect to have some default operators installed as an example. Following the OCP doc. 

<img width="877" alt="Screenshot 2019-03-25 at 20 28 38" src="https://user-images.githubusercontent.com/7708031/54951986-d1eb4680-4f3c-11e9-9cdd-3f210af40717.png">

## What is the current behaviour? 

<img width="1630" alt="Screenshot 2019-03-25 at 20 30 59" src="https://user-images.githubusercontent.com/7708031/54952037-eb8c8e00-4f3c-11e9-9e6c-1e3799ef0251.png">
 
Following some observations: 
* The installation guide does not make clear for who is getting started with it when and for what the user should do "Building deployment resources for any cluster". 
* The explanation of "Subscribe to a Package and Channel" is not clear for who is getting started with it. Why should someone do it? What are the steps exactly to do it?

**Comment by ecordell** [comment]
OLM comes installed by default in openshift clusters - but I'll leave this open to track the deficiencies in our docs.

**Comment by ecordell** [comment]
If you install with the instructions here: https://github.com/operator-framework/operator-lifecycle-manager/releases/tag/0.10.0

You should see the community operators from operatorhub by default. Or, if you get OLM by default with an openshift cluster, you should see a number of operators available for install via the marketplace. 

If you can replicate this, please re-open, but I believe that you always see some operators in kubernetes and openshift now.
