### ISSUE TITLE
After it be installed the URL to connect/use it should be informed to the user

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lifecycle-manager#785]
## WHAT
After it is installed the URL to connect/use it should be informed to the user

## WHY 
Make clear for the user what URL them should use to access it. In the output appears another URL and make it very confusing. 

## Example:

As it is done for Minishift. 

```
The OLM is accessible via web console at:
    https://localhost:9000/
```

**Comment by ecordell** [comment]
Are you referring to the `./scripts/run_console_local.sh` script? I believe it tells you where the UI is accessible?

**Comment by camilamacedo86** [comment]
HI @ecordell,

It is in the `$ ./scripts/run_console_local.sh`. No, it does no show the info/msg as was requested here which is a small improvement just to make better the usability. It is very common that the user will following the readme but will not see that it is accessible by `https://localhost:9000/`, so shows it at the end of the script appears really small effort and will be really helpful for them.

**Comment by camilamacedo86** [comment]
Following the PR made:
https://github.com/operator-framework/operator-lifecycle-manager/pull/858

**Comment by camilamacedo86** [comment]
Closing since the PR is merged 👍 tks for the review and support :-)
