### ISSUE TITLE
ClusterRoles with group/user subjects

### ISSUE THREAD

**Issue by jarifibrahim** [operator-framework/operator-lifecycle-manager#786]
## Feature Request

I have an operator which needs to create a `clusterRole` with read permission for all for all objects of a specific CR. The `subject` of the rolebinding should be `system:authenticated` user group but currently this is not supported. 

Currently, only a service account can be associated with a clusterrole.

```go
// StrategyDeploymentPermissions describe the rbac rules and service account needed by the install strategy
type StrategyDeploymentPermissions struct {
	ServiceAccountName string            `json:"serviceAccountName"`
	Rules              []rbac.PolicyRule `json:"rules"`
}
```

**Describe the solution you'd like**
There should be a way to declare clusterrole binding to specific `user/group` in the `clusterServiceVersion` file.

**Comment by ecordell** [comment]
Can you make a case for why this should be a thing that operators can request to happen automatically on install, and not just additional configuration that a cluster administrator performs? (how does your operator know that all authenticated users should be allowed to read the CRs in any given cluster?)

**Comment by ecordell** [comment]
This is now supported - you can include additional ClusterRoles/RoleBindings alongside your CSV and they will be created on install.

**Comment by jarifibrahim** [comment]
Thanks @ecordell
