### ISSUE TITLE
Seeing a consistent pattern of warnings installing OLM on OS3 cluster

### ISSUE THREAD

**Issue by ldimaggi** [operator-framework/operator-lifecycle-manager#803]
Steps to recreate:

git clone git@github.com:talamer/console.git
minishift start
oc login -u system:admin
oc adm policy add-cluster-role-to-user cluster-admin admin
oc login -u admin
source ./contrib/oc-environment.sh
./bin/bridge

oc apply -f https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/olm.yaml 

The results of the 'oc apply' command are:

oc apply -f https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/olm.yaml 
namespace/olm created
namespace/operators created
clusterrole.rbac.authorization.k8s.io/system:controller:operator-lifecycle-manager created
serviceaccount/olm-operator-serviceaccount created
clusterrolebinding.rbac.authorization.k8s.io/olm-operator-binding-olm created
customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/installplans.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/subscriptions.operators.coreos.com created
customresourcedefinition.apiextensions.k8s.io/catalogsources.operators.coreos.com created
deployment.apps/olm-operator created
deployment.apps/catalog-operator created
clusterrole.rbac.authorization.k8s.io/aggregate-olm-edit created
clusterrole.rbac.authorization.k8s.io/aggregate-olm-view created
customresourcedefinition.apiextensions.k8s.io/operatorgroups.operators.coreos.com created
configmap/olm-operators created
unable to recognize "https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/olm.yaml": no matches for kind "CatalogSource" in version "operators.coreos.com/v1alpha1"
unable to recognize "https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/olm.yaml": no matches for kind "OperatorGroup" in version "operators.coreos.com/v1alpha2"
unable to recognize "https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/olm.yaml": no matches for kind "OperatorGroup" in version "operators.coreos.com/v1alpha2"
unable to recognize "https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/olm.yaml": no matches for kind "Subscription" in version "operators.coreos.com/v1alpha1"
unable to recognize "https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/olm.yaml": no matches for kind "CatalogSource" in version "operators.coreos.com/v1alpha1"

**Comment by ldimaggi** [comment]
A workaround to this issue is to retry the 'oc apply' command - that seems to clear the problem:

[ldimaggi@ldimaggi operators]$ oc apply -f https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/olm.yaml 
namespace/olm configured
namespace/operators configured
clusterrole.rbac.authorization.k8s.io/system:controller:operator-lifecycle-manager configured
serviceaccount/olm-operator-serviceaccount unchanged
clusterrolebinding.rbac.authorization.k8s.io/olm-operator-binding-olm configured
customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/installplans.operators.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/subscriptions.operators.coreos.com configured
customresourcedefinition.apiextensions.k8s.io/catalogsources.operators.coreos.com configured
deployment.apps/olm-operator unchanged
deployment.apps/catalog-operator unchanged
clusterrole.rbac.authorization.k8s.io/aggregate-olm-edit configured
clusterrole.rbac.authorization.k8s.io/aggregate-olm-view configured
customresourcedefinition.apiextensions.k8s.io/operatorgroups.operators.coreos.com configured
configmap/olm-operators unchanged
catalogsource.operators.coreos.com/olm-operators created
operatorgroup.operators.coreos.com/global-operators created
operatorgroup.operators.coreos.com/olm-operators created
subscription.operators.coreos.com/packageserver created
catalogsource.operators.coreos.com/operatorhubio-catalog created

**Comment by ecordell** [comment]
We've added an install script which handles this, as well as a separate yaml file with just the CRDs, which should help prevent this issue. Check it out on our latest release: https://github.com/operator-framework/operator-lifecycle-manager/releases/tag/0.10.0
