### ISSUE TITLE
Doc for defining x-descriptors

### ISSUE THREAD

**Issue by mlbiam** [operator-framework/operator-lifecycle-manager#808]
There's no doc that tells me what x-descriptors are available, what they do, which ones are editable, etc.  I'm digging through existing CSVs but its pretty painful.  A doc that lists them out would make this much easier.

**Comment by alecmerdler** [comment]
Right now they are used to drive the OpenShift console (formerly CoreOS Tectonic console). Here is the documentation: https://github.com/openshift/console/tree/master/frontend/public/components/operator-lifecycle-manager/descriptors. We plan on adding more descriptors and capabilities in the near future.

**Comment by alecmerdler** [comment]
We don't have a table like that, but we should! Generally, `spec` is input and `status` is output. A text input would be a good addition, I think.

**Comment by alimobrem** [comment]
+1
