### ISSUE TITLE
Generated Subscriptions should have an owner reference to created Subscription

### ISSUE THREAD

**Issue by djzager** [operator-framework/operator-lifecycle-manager#832]
**Introduction:**

I have noticed that if you subscribe to an operator that depends on another operator. A `Subscription` will be generated for you but is not removed when the "parent" `Subscription` is deleted.

**Recreation Steps:**

1. Check out [this silly made up olm-catalog](https://github.com/djzager/olm-playground/tree/master/scenario1) that has two operators, one channel for each (`alpha`), and one version for each `v0.0.1`. Build and push the operator-registry image.
1. Create a `CatalogSource` pointing at this image
1. Subscribe to `example-operator-a`
1. See that a subscription to `example-operator-b` is generated (ie. `example-operator-b-stable-scenario3-openshift-operator-lifecycle-manager`)
1. Remove the `Subscription` to `example-operator-a` (leaving "Also completely remove the Operator from the selected namespace." checked)

**What I expected to happen:**
The subscription to `example-operator-a` and the generated subscription to be removed

**What happened:** 
only the subscription to `example-operator-a` is removed

**Edit History**

1. On the first go I submitted the issue before properly formatting.

**Comment by ecordell** [comment]
This is intentional behavior - just because an operator was installed because it was a dependency, doesn't mean there are no other consumers of that operator's apis.

Closing for now, please re-open if you feel there's more discussion to be had 😄
