### ISSUE TITLE
Feature Request: NodeAffinity for Operators

### ISSUE THREAD

**Issue by davi5e** [operator-framework/operator-lifecycle-manager#840]
It'd be really nice to use Pod/Node Affinity and Anti-affinity (or at least NodeSelector) to indicate where Pods created by the operator should be scheduled, possibly via a `Subscription` object.

**Comment by ecordell** [comment]
Thanks for the suggestion!

Completely agree, and it's on our roadmap. For now there are ways to direct workloads at the namespace level that we've been relying on.

**Comment by ecordell** [comment]
NodeSelector can be used in a subscription's `spec.config` block to direct workloads at runtime.

**Comment by jmhopla** [comment]
Hi!,
Not yet any option about nodeAffinity?, NodeSelector is a bit restricting in some use cases.
Thanks,

**Comment by dmesser** [comment]
@jmhopla what is your use case for setting node affinity on the operator controller pods?
