### ISSUE TITLE
Unable to install 2 operators in mixed installation modes

### ISSUE THREAD

**Issue by nicolaferraro** [operator-framework/operator-lifecycle-manager#873]
I've the following operators:

- Operator A: depends on custom resource CR1 provided by operator B. Can be installed on all namespaces only.
- Operator B: provides CR1. Can be installed in single namespace only.

Even if it's technically possible to install operator A to watch all namespaces and operator B only in a specific namespace "test" and use both operators in the namespace "test", OLM does not allow the combination: installation of Operator A remains stuck.

I've forced installation of operator B in all namespaces with a hack and both are installed normally, so there should be an issue when installing things in mixed modes.

Is there a way to make both operators be provisioned by OLM? They work really well together when installed manually.

**Comment by nicolaferraro** [comment]
Can you tell me if this scenario is supported?

**Comment by nicolaferraro** [comment]
![hay](https://user-images.githubusercontent.com/4151857/58865416-d0659980-86b6-11e9-8e84-29b42c086e6e.gif)

**Comment by dmesser** [comment]
I think it's expected that OLM does not allow to install the Operators in the way you describe, because they are not really usable. When you say "they work really well together" I assume this is because you happened to be in the right namespace?

**Comment by nicolaferraro** [comment]
Yeah, but even two operators that can be installed on a single namespace work if it happens that they are on the same one.

In my example, everything works correctly only in the namespaces where also operator B is installed, because A is installed everywhere.

I don't see technical/logical issues in the scenario. An operator can depend on CustomResourceDefinitions owned by another operator, not the other operator itself. CRD are cluster-wide objects, so they are installed cluster-wide, no matter the install mode.

A "AllNamespaces" operator CSV is "Copied" in all namespaces. It would be easy to set it into a kinda "NotInstalled" state in the namespaces where the other operator (operator B, in the example) is not present and changing the status of the CSV to an usable value only where operator B CSV is installed correctly.

**Comment by dmesser** [comment]
You are right that CRDs are global and we are kind of creating the impression that there is a tenancy-concept available to CRDs when really there is not. At this point it's more about RBAC and scoping down the privileges to a particular namespace.

There is a logical issue in your scenario where the Operator A that was written to depend on Operator B is only supporting watching all namespaces when B does not. You'd expect that this was taken into account when writing Operator A.

**Comment by nicolaferraro** [comment]
I've implemented some workarounds to make sure operator A can be also installed globally.

Anyway, I don't see a logical problem here if you think about services (or CSV if you want) and not operators. A service can be installed in 1, n or all namespaces. If it depends on another service B, in order to install it, you should also install service B in any namespace where you want to have service A installed.

Where you do install the operator or if there are one or more operators in the cluster, is just a fact of technical preference. The important aspect is where (in which namespaces) those operators provide a service.
