### ISSUE TITLE
Unable to run UI console for OLM

### ISSUE THREAD

**Issue by jdockter** [operator-framework/operator-lifecycle-manager#886]
When running latest run_console_local.sh get the following error

$ ./run_console_local.sh 
latest: Pulling from openshift/origin-console
Digest: sha256:ade20a34050642da950275a88a096c4e3f057119a96a939755f3a4f0d44285a6
Status: Image is up to date for quay.io/openshift/origin-console:latest
Using https://9.42.134.146:8001
Unable to run the console locally. May this port is in usage already. 
Check if the OLM is not accessible via web console at: https://localhost:9000/. 

If I revert back to prior version of  run_console_local.sh, git commit 37a12b9855e758e83eb537ebb7b0337067af713d from Sept 5th, it works fine.

@camilamacedo86

**Comment by camilamacedo86** [comment]
Hi @jdockter,

I am not sure why you ping me. However, did you `Check if the OLM is not accessible via web console at: https://localhost:9000/.` already? 

I am not able to face any problem with `male run-console-local`

**Comment by jdockter** [comment]
Ah okay the documentation I had, which I can't seem to find now, didn't have the use of a make command.  Everything is working fine now, thanks.
