### ISSUE TITLE
Unable to use OLM tool when the operator is cluster-scoped and has not the role

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lifecycle-manager#888]
## Error:

```shell
$ operator-sdk olm-catalog gen-csv --csv-version 0.1.0 --update-crds
INFO[0000] Generating CSV manifest version 0.1.0        
Error: catalog scaffold failed: (open deploy/role.yaml: no such file or directory)

```

## Note
Cluster-scoped ones will not have the role and instead of it will have the cluster_role. 

## Suggestions
The place which is looking for roles files should be able to also get:

- cluster_role.yaml
- cluster_role_binding.yaml

If some issue like this one occurs the process should still working for all files in the deploy dir.

**Comment by ecordell** [comment]
Did you mean to make this issue against `operator-sdk` instead? 

If not, I think that I misunderstand what the issue is. Could you explain it in a different way?

**Comment by camilamacedo86** [comment]
@ecordell make sense :-)
