### ISSUE TITLE
Deploying an operator without using a subscription object

### ISSUE THREAD

**Issue by philbrookes** [operator-framework/operator-lifecycle-manager#891]
**What did you do?**
Created a namespace 000-test and in there a clusterserviceversion, installplan for that clusterserviceversion and operatorgroup with targetnamespaces of 000-test.

**What did you expect to see?**
The roles / serviceaccounts / customresourcedefinitions and deployments described in the clusterserviceversion deployed / created in the 000-test namespace.

**What did you see instead? Under which circumstances?**
The clusterserviceversion status stated that the customresourcedefinition and serviceaccount - which were defined in the clusterserviceversion - were not present (note that this seems to be the case whether or not we create an installplan):
```
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      message: CRD is not present
      name: installations.integreatly.org
      status: NotPresent
      version: v1beta1
    - group: ''
      kind: ServiceAccount
      message: Service account does not exist
      name: integreatly-operator
      status: NotPresent
```

The installplan remained unprocessed (there was an error about it missing a plan in it's status in the olm-operator).

**Extra Information**
My real goal here is to deploy a specific version of an operator into a namespace, without creating a subscription to a channel in the catalog.

We have been able to get it to work by creating an installplan, and then editing it's status to add a plan with all the customresourcesdefinitions, serviceaccounts, etc described in there, but as we have to edit the status of this object, this does not feel like the correct solution to this problem.

**Comment by ecordell** [comment]
the operator can be installed by:

- directly creating the CSV
- directly creating rbac and CRDs

If done correctly, the CSV status will move to Succeeded. If something is missing, the status should indicate what it is.

There should be no reason to use an installplan for this

Please re-open if you have further questions, or open a new issue.
