### ISSUE TITLE
Wrong steps in the Release notes (0.10.0)

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lifecycle-manager#895]
## What

<img width="1002" alt="Screenshot 2019-06-08 at 19 10 10" src="https://user-images.githubusercontent.com/7708031/59150802-2755d080-8a21-11e9-8f63-61c1f546aa85.png">

## Fix
Replace `chmod +x ./install` for `chmod +x install.sh`

**Comment by njhale** [comment]
@camilamacedo86 thanks for pointing this out. I've updated the release notes with your suggestion!
