### ISSUE TITLE
[doc] - Installation and configuration process are not clear

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-lifecycle-manager#896]
## What:
If a dev tries to follow the install doc is not clear what steps are required to perform for each platform/type. Also, it shows not very accurate too. 

## Suggestin:
Something as the following example in the readme:

> ### In Minishiff/Minikube
> E.g 
> - Run `curl ` or pip install or brew install
> - Run `make install`
> ### In Kubernetes
> ### In OCP OSD 3.11
> ### Running locally
> - Run `make run-console`

And/or similar to https://github.com/operator-framework/operator-sdk/blob/master/doc/user/install-operator-sdk.md but with the info required for each scenario/platform/so supported if is not equals

## NOTES:
IMHO: 
- The many navigations are not a good experience for the users 
- The steps show not very clear and/or accurate
- The usage of scripts instead of commands is not a good experience for the users too. I'd like to suggest we use the Makefile to call the scripts which could be an easy/low-cost solution. 
- I'd like to suggest we add an index in the README generated with [DocToc](https://github.com/thlorenz/doctoc)

**Comment by camilamacedo86** [comment]
PR to solve it is: https://github.com/operator-framework/operator-lifecycle-manager/pull/898

**Comment by ecordell** [comment]
Thanks to your help, I think we have clear docs and scripts for install/uninstall now.
