### ISSUE TITLE
ImagePullPolicy for CatalogSources

### ISSUE THREAD

**Issue by ecordell** [operator-framework/operator-lifecycle-manager#903]
Right now, CatalogSources are set to IfNotPresent. For development purposes, it would be nice to be able to configure the pull policy on the CatalogSource that generates the pod.

**Comment by hardbone12** [comment]
+1

# oc explain catalogsource.spec
KIND:     CatalogSource
VERSION:  operators.coreos.com/v1alpha1

RESOURCE: spec <Object>

DESCRIPTION:
     Spec for a catalog source.

FIELDS:
   address      <string>
     An optional address. When set, directs OLM to connect to use a pre-existing
     registry server at this address.

   configMap    <string>
     The name of a ConfigMap that holds the entries for an in-memory catalog.

   displayName  <string>
     Pretty name for display

   image        <string>
     An image that serves a grpc registry. Only valid for `grpc` sourceType. If
     both image and address are set, OLM does not use the address field.

   publisher    <string>
     The name of an entity that publishes this catalog

   secrets      <[]string>
     A set of secrets that can be used to access the contents of the catalog. It
     is best to keep this list small, since each will need to be tried for every
     catalog entry.

   sourceType   <string> -required-
     The type of the source. `configmap` is the new name for `internal`

**Comment by AndrienkoAleksandr** [comment]
+1 For this issue. It is really useful for development.

**Comment by exdx** [comment]
As a hack you could take advantage of the new catalog polling feature described [here](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/catalog-polling.md) and set the update poll interval for the development catalog source pod to something really high, say 24h. If you enable catalog polling the pullpolicy for the catalog source pod is set to `Always`. Just a little workaround until we add proper support for this feature.

**Comment by squakez** [comment]
I was looking for the feature and found the following explanation:
```
  | Specify your index image. If you specify a tag after the image name, for example :v4.11, the catalog source pod uses an image pull policy of Always, meaning the pod always pulls the image prior to starting the container. If you specify a digest, for example @sha256:<id>, the image pull policy is IfNotPresent, meaning the pod pulls the image only if it does not already exist on the node.
-- | --
```
from https://docs.openshift.com/container-platform/4.11/operators/admin/olm-managing-custom-catalogs.html

I tested and it worked as expected.
