### ISSUE TITLE
Is there documentation for a ClusterServiceVersion install.strategy=image?

### ISSUE THREAD

**Issue by gobengo** [operator-framework/operator-lifecycle-manager#905]
https://github.com/operator-framework/operator-lifecycle-manager/blob/master/deploy/upstream/manifests/0.10.0/0000_50_olm_03-clusterserviceversion.crd.yaml#L602

What exactly are the semantics of this strategy? Is there a spec somewhere? It seems to have been in the CSV schema for many versions.

I'm wondering what gets done with the image indicated by this property. Is it invoked with arguments? with any volumes mounted (e.g. a kubeconfig)?

How do I make a good image that could be invoked by a CSV with install.strategy=image?

**Comment by njhale** [comment]
@gobengo If I recall correctly, `image` was added as a placeholder for a strategy that was never completely fleshed out. To my knowledge, there is no current implementation of, or documentation about it.

**Comment by gobengo** [comment]
@njhale Thank you!
