### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by aceeric** [operator-framework/operator-lifecycle-manager#908]
Regarding this page:
https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/operatorgroups.md

And this verbiage:

An operator is said to be a member of an OperatorGroup if its CSV exists in the same namespace as the OperatorGroup and its CSV's InstallModes support the set of namespaces targeted by the OperatorGroup ...

And this verbiage  right below:

An operator defined by CSV csv-a is said to be a member of OperatorGroup op-a in namespace ns-a if both of the following hold:
* op-a is the only OperatorGroup in ns-a
* csv-a's InstallModes support op-a's target namespace set

The first section seems to indicate the both the OperatorGroup and a CSV have to be in the same namespace as a requirement for membership. The second section omits this and so it seems contradictory. If both must be in the same namespace, then recommend the following verbiage:

An operator defined by CSV csv-a is said to be a member of OperatorGroup op-a in namespace ns-a if all of the following hold:
* op-a is the only OperatorGroup in ns-a
* csv-a's InstallModes support op-a's target namespace set
* op-a and csv-a are in the same namespace

The page also contains this verbiage: "The set of target namespaces is provided via a comma-delimited string stored in the olm.targetNamespaces annotation"

However the examples present a YAML array:
```
spec:
  targetNamespaces:
  - my-namespace
  - my-other-namespace
  - my-other-other-namespace
```
So the verbiage _comma-delimited string_ seems a little misleading. Maybe "The set of target namespaces is provided as an array in the olm.targetNamespaces annotation"

**Comment by njhale** [comment]
@aceeric Thank you for taking the time to read through our docs so thoroughly. Your suggestion for the wording of the definition of OperatorGroup membership definitely makes things more clear.

As for target namespaces, the examples show the _specification_ of target namespaces on an OperatorGroup, while the section you point out "The set of target namespaces is provided via a comma-delimited string stored in the olm.targetNamespaces annotation", is how OLM projects that spec to operator `Deployments`, which is actually via a comma-delimited annotation (e.g. "ns-a, ns-b") and not a YAML list.

**Comment by ecordell** [comment]
It seems like this question has been answered - please re-open (or open a new issue) to continue discussion if needed.
