### ISSUE TITLE
How to tell if OLM is ready after OpenShift install?

### ISSUE THREAD

**Issue by newgoliath** [operator-framework/operator-lifecycle-manager#934]
We deploy dozens of OpenShift 4s daily for our students.  Sometimes we need to deploy OLM based operators immediately after install.  We do all this with Ansible.  Oftentimes, we see that the OLM is not ready, and our playbooks that innocently deploy these operators time out and fail our deployments.  We'd like to add a service check for this.

What is the best indication that OLM is ready to service subscriptions, etc?

In [1] I see `kubectl -n local get deployments` - would this work with OCP4.1 reliably if I change to `oc get deployments -n openshift-operator-lifecycle-manager`?

[1] https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/install/install.md#run-locally-with-minikube

Thanks!

**Comment by ecordell** [comment]
Thanks for the question @newgoliath - 

For 4.1+ clusters, the cluster itself should not signal that it's ready unless OLM is up and ready to service requests. 

Can you give an example of some commands that are taking longer than you expect or failing?

**Comment by newgoliath** [comment]
This subscription for operator-metering has hung a few times:

https://github.com/redhat-cop/agnosticd/blob/development/ansible/roles/ocp4-workload-metering/templates/subscription.j2

Per the Ansible above, we give it 5 minutes.

I find that when I apply the same ansible role to a cluster that's been up for 1+ hours, it works flawlessly.

Unfortunately, our system immediately deletes failed clusters, so grabbing logs is a bit of a challenge.  A remote log collector is in our future.

**Comment by ecordell** [comment]
Is this still an issue? Please re-open if so.
