### ISSUE TITLE
CSV not found for CS in other namespace

### ISSUE THREAD

**Issue by philbrookes** [operator-framework/operator-lifecycle-manager#944]
I am attempting to manually create a subscription to a catalogsource(CS) in a seperate namespace.

If I do this through the UI, a CS is cloned into my namespace and the subscription points to that CS, e.g.
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: integreatly
  namespace: 000-catalog-test
spec:
  channel: integreatly
  installPlanApproval: Automatic
  name: integreatly
  source: installed-custom-000-catalog-test
  sourceNamespace: 000-catalog-test
  startingCSV: integreatlyoperator.1.0.1
```

However, when I create a subscription manually, I do not want to copy the CS into my namespace, I create a subscription like this:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: integreatly
  namespace: 001-catalog-test
spec:
  channel: integreatly
  installPlanApproval: Automatic
  name: integreatly
  source: integreatly-operators
  sourceNamespace: openshift-marketplace
  startingCSV: integreatlyoperator.1.0.1
```

The first example, created by the UI, works just fine.

However, the second example causes an error in the catalog-operator:
```
E0705 10:07:08.143297 1 queueinformer_operator.go:186] Sync "001-catalog-test" failed: {integreatly integreatly integreatlyoperator.1.0.1 {integreatly-operators openshift-marketplace}} not found: CatalogSource {integreatly-operators openshift-marketplace} not found 
```

However, the catalogSource definitely exists:
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  creationTimestamp: '2019-07-03T15:57:34Z'
  generation: 1
  labels:
    csc-owner-name: integreatly-operators
    csc-owner-namespace: openshift-marketplace
    olm-visibility: hidden
    openshift-marketplace: 'true'
    opsrc-datastore: 'true'
    opsrc-owner-name: integreatly-operators
    opsrc-owner-namespace: openshift-marketplace
  name: integreatly-operators
  namespace: openshift-marketplace
  resourceVersion: '190906'
  selfLink: >-
    /apis/operators.coreos.com/v1alpha1/namespaces/openshift-marketplace/catalogsources/integreatly-operators
  uid: 459ae979-9dab-11e9-9091-12085e70668a
spec:
  address: '172.30.239.69:50051'
  displayName: Integreatly Operators
  icon:
    base64data: ''
    mediatype: ''
  publisher: Integreatly Publisher
  sourceType: grpc
status:
  lastSync: '2019-07-03T15:57:54Z'
  registryService:
    createdAt: '2019-07-03T15:57:54Z'
    protocol: grpc
```

**Comment by philbrookes** [comment]
I found these docs, that appear to suggest that this should be working:
https://github.com/operator-framework/operator-marketplace#installing-an-operator-using-marketplace

**Comment by willholley** [comment]
I'm experiencing the same issue in OLM 0.11. It works fine with OLM 0.10.

**Comment by ecordell** [comment]
Subscriptions can be made to two types of catalogs: global and local.

There is one blessed namespace in a cluster where global catalogs reside. In openshift <4.2, that is `openshift-operator-lifecycle-manager`. In openshift >=4.2, that is `openshift-marketplace` and in upstream releases it is `olm`.

You can make a subscription to a global catalog from any namespace. Otherwise, the catalogsource must exist in the same namespace as the subscription.

The subscription status will show which catalogsources are available for resolution

**Comment by lagivan** [comment]
@ecordell is it possible to change the global catalog namespace when installing OLM? I want to set it to `openshift-marketplace` and not `olm` which is the default now.

**Comment by dmesser** [comment]
@lagivan this is possible, you can adjust the configuration here: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/deploy/upstream/manifests/0.18.3/0000_50_olm_08-catalog-operator.deployment.yaml#L29
