### ISSUE TITLE
Make fails when GOPATH contains more than one entry

### ISSUE THREAD

**Issue by bostrt** [operator-framework/operator-lifecycle-manager#956]
If `GOPATH` contains more than a single entry, the `dep` section in Makefile fails:
https://github.com/operator-framework/operator-lifecycle-manager/blob/7f78dc9900df26d0c1fbfa195f4ef61b91ac7b6b/Makefile#L75-L77

**Comment by njhale** [comment]
@bostrt - OLM now uses go modules for dependency resolution, so all make rules referencing `dep` have been removed in newer releases. 

Our `Makefile` is generally for development purposes, so it won't impact the release itself. Could you explain your use-case for using the `Makefile` with an older release? Is it possible for you to use a more recent release (with the failing rules removed)?

**Comment by bostrt** [comment]
@njhale 
> OLM now uses go modules for dependency resolution, so all make rules referencing dep have been removed in newer releases.
> Our Makefile is generally for development purposes, so it won't impact the release itself. Could you explain your use-case for using the Makefile with an older release? Is it possible for you to use a more recent release (with the failing rules removed)?

Ah, good to know! Yes, I'm building a version based on `0.6.0` [released by Red Hat](https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/openshift3/ose-operator-lifecycle-manager) for troubleshooting a [startup hang issue](https://bugzilla.redhat.com/show_bug.cgi?id=1709533). Just came across this Makefile issue while building a debug image.
