### ISSUE TITLE
The ability to pull CatalogSource images from private docker registries

### ISSUE THREAD

**Issue by alikor** [operator-framework/operator-lifecycle-manager#982]
It should be possible to pass in an optional imagePullSecrets field when creating CatalogSource of sourceType: grpc to be able to pull images that are hosted on private docker registries

**Comment by dmesser** [comment]
Did you try putting a pull secret in the namespace of your `CatalogSource` object?

**Comment by alikor** [comment]
I am not sure what you are suggesting?

I had a quick look at the code looks like imagepullsecrets are attached the the Pod the container is running in would need to change the CRD spec structure and a factory method

**Comment by ecordell** [comment]
This can be done "manually" by creating a deployment pointing to your image, and creating a catalogsource that uses the `spec.address` field to point to the running pod in the deployment.
