### ISSUE TITLE
Configuring deployment limits and environment

### ISSUE THREAD

**Issue by lulf** [operator-framework/operator-lifecycle-manager#999]
At present, any settings such as memory limits or environment variables of the deployments in the CSV cannot be configured. Although memory limits etc. is not very critical for operators that have a low footprint in general, api-servers configured in OLM may need to have limits increased, or even replicas changed. Having some way for making such settings configurable at operator install/apply time would be a useful feature in order to manage different settings for dev vs production for instance.

**Comment by ecordell** [comment]
Hi @lulf -

We have a proposal for this and have begun implementation on it:

This doc describes the feature: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/contributors/design-proposals/operator-config.md

Currently we have only implemented Env vars, but the rest will come soon (in the 4.3 timeframe)
